"""
Django settings for simulaciones_pequiven project.

Generated by 'django-admin startproject' using Django 4.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/

======================

A nivel de código el proyecto se llama 'simulaciones_pequiven' hasta que se decida un nombre oficial.
"""

from pathlib import Path
import os
# from django_auth_ldap.config import LDAPSearch
from .jobs import start_deleting_job

### CONFIGURACIÓN DE LDAP

# AUTH_LDAP_GLOBAL_OPTIONS = {
#     ldap.OPT_X_TLS_REQUIRE_CERT: True,
#     ldap.OPT_X_TLS_DEMAND: True,
#     ldap.OPT_REFERRALS: 0,
#     ldap.OPT_X_TLS_CACERTFILE: '/etc/ssl/certs/mycertfile.pem'
# }
# AUTH_LDAP_SERVER_URI = 'ldap:'
# AUTH_LDAP_BIND_DN = "CN=bind,CN=Users,DC=indesca,DC=local"
# AUTH_LDAP_BIND_PASSWORD = ""

# AUTH_LDAP_USER_SEARCH = LDAPSearch(
#     "dc=indesca,dc=local", ldap.SCOPE_SUBTREE, "sAMAccountName=%(user)s"
# )

# AUTH_LDAP_USER_ATTR_MAP = {
#     "username": "sAMAccountName",
#     "first_name": "givenName",
#     "last_name": "sn",
#     "email": "mail",
# }
# AUTH_LDAP_GROUP_CACHE_TIMEOUT = 1  # 1 hour cache

AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    # "django_auth_ldap.backend.LDAPBackend",
]

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Lee la clave secreta desde un archivo externo para evitar exponerla en el código fuente
""" with open(os.path.join(BASE_DIR, 'secret-key.txt')) as f:
    SECRET_KEY = f.read().strip() """
SECRET_KEY = os.environ.get("SECRET_KEY")

if not SECRET_KEY:
    raise Exception("La variable de entorno SECRET_KEY no está configurada.")
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False').lower() in ('1', 'true', 'yes')


ALLOWED_HOSTS = [
    'metor-b7dc6ss2aq-wl.a.run.app',
    'metor-410526246437.us-west2.run.app',
    '.run.app',
    'localhost',
    '127.0.0.1',
]

CSRF_TRUSTED_ORIGINS = [
    'https://metor-b7dc6ss2aq-wl.a.run.app',
    'https://metor-410526246437.us-west2.run.app',
]

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

LOGIN_URL = '/'

SESSION_COOKIE_AGE = 120 * 60 # 2 horas sin uso
SESSION_EXPIRE_AT_BROWSER_CLOSE= True
SESSION_SAVE_EVERY_REQUEST = True
AUTH_LDAP_ALWAYS_UPDATE_USER = False

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'intercambiadores',
    'auxiliares',
    'calderas',
    'compresores',
    'usuarios',
    'static',

    'django_db_logger',
    'pwa',
    'templatetags',
    'mathfilters',
    'widget_tweaks',
    # "debug_toolbar",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "simulaciones_pequiven.middleware.RequestLogMiddleware",
    # "debug_toolbar.middleware.DebugToolbarMiddleware",
]

ROOT_URLCONF = 'simulaciones_pequiven.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates')
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
            'libraries':{
                'templatetags': 'templatetags.tags',
            }
        },
    },
]

WSGI_APPLICATION = 'simulaciones_pequiven.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases
#
# Configuración robusta para:
# - Producción: Cloud Run + Cloud SQL para MySQL.
# - Desarrollo local: SQLite cuando DEBUG=True y no se suministran variables de BD.
#
# En Cloud Run deben existir estas variables:
# SECRET_KEY, DB_NAME, DB_USER, DB_PASS y DB_HOST.
# DB_HOST debe tener la forma:
# /cloudsql/PROJECT_ID:REGION:INSTANCE_NAME

DB_NAME = os.environ.get("DB_NAME")
DB_USER = os.environ.get("DB_USER")
DB_PASS = os.environ.get("DB_PASS")
DB_HOST = os.environ.get("DB_HOST")
DB_PORT = os.environ.get("DB_PORT", "3306")

if not DEBUG:
    missing_vars = [
        name for name, value in {
            "DB_NAME": DB_NAME,
            "DB_USER": DB_USER,
            "DB_PASS": DB_PASS,
            "DB_HOST": DB_HOST,
        }.items()
        if not value
    ]

    if missing_vars:
        raise Exception(
            "Faltan variables de entorno obligatorias para producción: "
            + ", ".join(missing_vars)
        )

    db_config = {
        "ENGINE": "django.db.backends.mysql",
        "NAME": DB_NAME,
        "USER": DB_USER,
        "PASSWORD": DB_PASS,
        "HOST": DB_HOST,
        "PORT": DB_PORT,
        "OPTIONS": {
            "init_command": "SET sql_mode='STRICT_TRANS_TABLES'",
        },
    }

    DATABASES = {
        "default": db_config,
        # Se conserva este alias para evitar errores si algún router,
        # paquete o migración intenta acceder a la conexión django_db_logger.
        "django_db_logger": db_config.copy(),
    }

else:
    if DB_NAME and DB_USER and DB_HOST:
        db_config = {
            "ENGINE": "django.db.backends.mysql",
            "NAME": DB_NAME,
            "USER": DB_USER,
            "PASSWORD": DB_PASS,
            "HOST": DB_HOST,
            "PORT": DB_PORT,
            "OPTIONS": {
                "init_command": "SET sql_mode='STRICT_TRANS_TABLES'",
            },
        }

        DATABASES = {
            "default": db_config,
            "django_db_logger": db_config.copy(),
        }
    else:
        DATABASES = {
            "default": {
                "ENGINE": "django.db.backends.sqlite3",
                "NAME": os.path.join(BASE_DIR, "db.sqlite3"),
            }
        }

# Configuración específica para django-db-logger.
# Se mantiene el alias por compatibilidad, pero el handler de logs se envía a consola.
DJANGO_DB_LOGGER_DATABASE = "default"

# Si tu router MyDBRouter envía modelos de django_db_logger al alias django_db_logger,
# esta línea puede conservarse porque el alias existe en producción.
DATABASE_ROUTERS = ("simulaciones_pequiven.dbrouters.MyDBRouter",)

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'es'

TIME_ZONE = 'America/Caracas'

USE_I18N = True

USE_TZ = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/


STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
WHITENOISE_MANIFEST_STRICT = False
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CONFIGURACIONES PWA
PWA_APP_NAME = 'SIEVEP'
PWA_APP_DESCRIPTION = "SIEVEP"
PWA_APP_THEME_COLOR = '#0A0302'
PWA_APP_BACKGROUND_COLOR = '#ffffff'
PWA_APP_DISPLAY = 'standalone'
PWA_APP_SCOPE = '/'
PWA_APP_ORIENTATION = 'any'
PWA_APP_START_URL = '/'
PWA_APP_STATUS_BAR_COLOR = 'default'
PWA_APP_ICONS = [
    {
        'src': '/static/img/logo.png',
        'sizes': '160x160'
    }
]
PWA_APP_ICONS_APPLE = [
    {
        'src': '/static/img/logo.png',
        'sizes': '160x160'
    }
]
PWA_APP_SPLASH_SCREEN = [
    {
        'src': '/static/img/logo.png',
        'media': '(device-width: 320px) and (device-height: 568px) and (-webkit-device-pixel-ratio: 2)'
    }
]
PWA_APP_DIR = 'ltr'
PWA_APP_LANG = 'en-US'
PWA_APP_SHORTCUTS = [
    {
        'name': 'Shortcut',
        'url': '/target',
        'description': 'Shortcut to a page in my application'
    }
]
PWA_APP_SCREENSHOTS = [
    {
      'src': '/static/img/logo.png',
      'sizes': '750x1334',
      "type": "image/png"
    }
]

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

INTERNAL_IPS = [
    "127.0.0.1",
]

# JOB CONFIGURATION
start_deleting_job()

# CONFIGURACIÓN DE LOS LOGS
#
# En Cloud Run es preferible escribir logs en stdout/stderr.
# Google Cloud Logging captura automáticamente lo que salga por consola.
# Esto evita el ciclo de error donde django_db_logger intenta escribir en BD
# justo cuando la conexión a la BD está fallando.

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "request_formatter": {
            "format": "%(asctime)s - %(name)s - %(levelname)s - %(module)s - %(process)s - %(thread)s - %(message)s",
            "datefmt": "%Y-%m-%d %H:%M:%S",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "request_formatter",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": os.getenv("DJANGO_LOG_LEVEL", "INFO"),
    },
    "loggers": {
        "django.request": {
            "handlers": ["console"],
            "level": os.getenv("DJANGO_LOG_LEVEL", "ERROR"),
            "propagate": False,
        },
        "simulaciones_pequiven": {
            "handlers": ["console"],
            "level": os.getenv("DJANGO_LOG_LEVEL", "INFO"),
            "propagate": False,
        },
    },
}