# Generated by Django 4.2.4 on 2024-05-06 11:56

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('intercambiadores', '0068_propiedadesdobletubo_altura_aletas_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Corriente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_corriente', models.CharField(max_length=10, verbose_name='Número Corriente')),
                ('flujo', models.FloatField()),
                ('entalpia', models.FloatField()),
                ('presion', models.FloatField()),
                ('temperatura', models.FloatField()),
                ('fase', models.CharField(choices=[('S', 'Saturado'), ('L', 'Líquido'), ('V', 'Vapor'), ('O', 'Sólido')], max_length=1)),
                ('entrada', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='DatosCorrientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entalpia_unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entalpia_unidad_corriente', to='intercambiadores.unidades')),
                ('flujo_unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flujo_unidad_corriente', to='intercambiadores.unidades')),
                ('presion_unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='presion_unidad_corriente', to='intercambiadores.unidades')),
                ('temperatura_unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='temperatura_unidad_corriente', to='intercambiadores.unidades')),
            ],
        ),
        migrations.CreateModel(
            name='EntradaEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flujo_entrada', models.FloatField(validators=[django.core.validators.MinValueValidator(1e-05)])),
                ('potencia_real', models.FloatField(validators=[django.core.validators.MinValueValidator(1e-05)])),
                ('flujo_entrada_unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flujo_entrada_unidad_entradaevaluacion', to='intercambiadores.unidades')),
                ('potencia_real_unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='intercambiadores.unidades')),
                ('presion_unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='presion_unidad_entrada_evaluacion_turbina', to='intercambiadores.unidades')),
                ('temperatura_unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='temperatura_unidad_entrada_evaluacion', to='intercambiadores.unidades')),
            ],
        ),
        migrations.CreateModel(
            name='EspecificacionesTurbinaVapor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('potencia', models.FloatField(validators=[django.core.validators.MinValueValidator(1e-06)])),
                ('potencia_max', models.FloatField(validators=[django.core.validators.MinValueValidator(1e-06)])),
                ('velocidad', models.FloatField(validators=[django.core.validators.MinValueValidator(1e-06)])),
                ('contra_presion', models.FloatField(validators=[django.core.validators.MinValueValidator(1e-06)])),
                ('eficiencia', models.FloatField(null=True)),
                ('contra_presion_unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contra_presion_unidad_turbinavapor', to='intercambiadores.unidades')),
                ('potencia_unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='potencia_unidad_turbinavapor', to='intercambiadores.unidades')),
                ('presion_entrada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='presion_entrada_turbinavapor', to='intercambiadores.unidades')),
                ('temperatura_entrada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='temperatura_entrada_turbinavapor', to='intercambiadores.unidades')),
                ('velocidad_unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='velocidad_unidad_turbinavapor', to='intercambiadores.unidades')),
            ],
        ),
        migrations.CreateModel(
            name='GeneradorElectrico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polos', models.PositiveSmallIntegerField()),
                ('fases', models.PositiveSmallIntegerField()),
                ('ciclos', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('potencia_real', models.FloatField(validators=[django.core.validators.MinValueValidator(1e-06)])),
                ('potencia_aparente', models.FloatField(validators=[django.core.validators.MinValueValidator(1e-06)])),
                ('velocidad', models.FloatField(validators=[django.core.validators.MinValueValidator(1e-06)])),
                ('voltaje', models.FloatField(validators=[django.core.validators.MinValueValidator(1e-06)])),
                ('ciclos_unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ciclos_unidad_generador', to='intercambiadores.unidades')),
                ('corriente_electrica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='corriente_electrica_generador', to='intercambiadores.unidades')),
                ('potencia_aparente_unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='potencia_aparente_unidad_generador', to='intercambiadores.unidades')),
                ('potencia_real_unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='potencia_real_unidad_generador', to='intercambiadores.unidades')),
                ('velocidad_unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='velocidad_unidad_generador', to='intercambiadores.unidades')),
                ('voltaje_unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='voltaje_unidad_generador', to='intercambiadores.unidades')),
            ],
        ),
        migrations.CreateModel(
            name='TurbinaVapor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=10, unique=True)),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripción')),
                ('fabricante', models.CharField(max_length=45)),
                ('modelo', models.CharField(max_length=45, null=True)),
                ('creado_al', models.DateTimeField(auto_now_add=True)),
                ('editado_al', models.DateTimeField(null=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turbina_creada_por', to=settings.AUTH_USER_MODEL)),
                ('datos_corrientes', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='turbinas.datoscorrientes')),
                ('editado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='turbina_editada_por', to=settings.AUTH_USER_MODEL)),
                ('especificaciones', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='turbinas.especificacionesturbinavapor')),
                ('generador_electrico', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='turbinas.generadorelectrico')),
                ('planta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='intercambiadores.planta')),
            ],
            options={
                'ordering': ('tag',),
            },
        ),
        migrations.CreateModel(
            name='SalidaEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eficiencia', models.FloatField()),
                ('potencia_calculada', models.FloatField()),
                ('entalpia_unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='intercambiadores.unidades')),
            ],
        ),
        migrations.CreateModel(
            name='SalidaCorriente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flujo', models.FloatField()),
                ('entalpia', models.FloatField()),
                ('fase', models.CharField(choices=[('S', 'Saturado'), ('L', 'Líquido'), ('V', 'Vapor'), ('O', 'Sólido')], max_length=1)),
                ('corriente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='turbinas.corriente')),
                ('salida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='turbinas.salidaevaluacion')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('entrada', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='turbinas.entradaevaluacion')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='turbinas.turbinavapor')),
                ('salida', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='turbinas.salidaevaluacion')),
            ],
            options={
                'ordering': ('-fecha',),
            },
        ),
        migrations.CreateModel(
            name='EntradaCorriente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presion', models.FloatField()),
                ('temperatura', models.FloatField(validators=[django.core.validators.MinValueValidator(-273.15)])),
                ('corriente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='turbinas.corriente')),
                ('entrada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='turbinas.entradaevaluacion')),
            ],
        ),
        migrations.AddField(
            model_name='corriente',
            name='datos_corriente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='turbinas.datoscorrientes'),
        ),
    ]
