# Generated by Django 4.2.4 on 2024-05-06 12:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turbinas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='corriente',
            name='descripcion_corriente',
            field=models.CharField(default=1, max_length=50, verbose_name='Descripción de la Corriente'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='corriente',
            name='entalpia',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1e-05)]),
        ),
        migrations.AlterField(
            model_name='corriente',
            name='flujo',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1e-05)]),
        ),
        migrations.AlterField(
            model_name='corriente',
            name='presion',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1e-05)]),
        ),
        migrations.AlterField(
            model_name='corriente',
            name='temperatura',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(-273.15)]),
        ),
    ]
