# Generated by Django 4.2.4 on 2024-05-07 08:47

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intercambiadores', '0068_propiedadesdobletubo_altura_aletas_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('turbinas', '0002_corriente_descripcion_corriente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='especificacionesturbinavapor',
            name='presion_entrada_unidad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='presion_entrada_turbinavapor', to='intercambiadores.unidades'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='especificacionesturbinavapor',
            name='temperatura_entrada_unidad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='temperatura_entrada_turbinavapor', to='intercambiadores.unidades'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='generadorelectrico',
            name='corriente_electrica_unidad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='corriente_electrica_generador', to='intercambiadores.unidades'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='especificacionesturbinavapor',
            name='presion_entrada',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1e-06)]),
        ),
        migrations.AlterField(
            model_name='especificacionesturbinavapor',
            name='temperatura_entrada',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1e-06)]),
        ),
        migrations.AlterField(
            model_name='generadorelectrico',
            name='corriente_electrica',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1e-06)], verbose_name='Corriente Eléctrica'),
        ),
        migrations.AlterField(
            model_name='turbinavapor',
            name='creado_por',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='turbina_creada_por', to=settings.AUTH_USER_MODEL),
        ),
    ]
