# Generated by Django 4.2.4 on 2024-05-07 09:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turbinas', '0003_especificacionesturbinavapor_presion_entrada_unidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corriente',
            name='presion',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(1e-05)]),
        ),
    ]
