# Generated by Django 4.2.4 on 2024-05-14 07:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('turbinas', '0004_alter_corriente_presion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='corriente',
            options={'ordering': ('-entrada', 'numero_corriente')},
        ),
        migrations.AlterField(
            model_name='corriente',
            name='datos_corriente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='corrientes', to='turbinas.datoscorrientes'),
        ),
        migrations.AlterField(
            model_name='corriente',
            name='entrada',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='corriente',
            name='fase',
            field=models.CharField(choices=[('S', 'Saturado'), ('L', 'Líquido'), ('V', 'Vapor'), ('O', 'Sólido'), ('F', 'Fluido Supercrítico')], max_length=1),
        ),
        migrations.AlterField(
            model_name='corriente',
            name='presion',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1e-05)]),
        ),
        migrations.AlterField(
            model_name='entradacorriente',
            name='entrada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entradas_corrientes', to='turbinas.entradaevaluacion'),
        ),
        migrations.AlterField(
            model_name='entradacorriente',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='entradacorriente',
            name='presion',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='entradaevaluacion',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='especificacionesturbinavapor',
            name='contra_presion',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1e-06)], verbose_name='Contra Presión'),
        ),
        migrations.AlterField(
            model_name='especificacionesturbinavapor',
            name='potencia_max',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1e-06)], verbose_name='Potencia Máxima'),
        ),
        migrations.AlterField(
            model_name='especificacionesturbinavapor',
            name='presion_entrada',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1e-06)], verbose_name='Presión de Entrada'),
        ),
        migrations.AlterField(
            model_name='especificacionesturbinavapor',
            name='temperatura_entrada',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1e-06)], verbose_name='Temperatura de Entrada'),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='generadorelectrico',
            name='potencia_aparente',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1e-06)], verbose_name='Potencia Aparente'),
        ),
        migrations.AlterField(
            model_name='generadorelectrico',
            name='potencia_real',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1e-06)], verbose_name='Potencia Real'),
        ),
        migrations.AlterField(
            model_name='salidacorriente',
            name='fase',
            field=models.CharField(choices=[('S', 'Saturado'), ('L', 'Líquido'), ('V', 'Vapor'), ('O', 'Sólido'), ('F', 'Fluido Supercrítico')], max_length=1),
        ),
        migrations.AlterField(
            model_name='salidacorriente',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='salidacorriente',
            name='salida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salidas_corrientes', to='turbinas.salidaevaluacion'),
        ),
        migrations.AlterField(
            model_name='salidaevaluacion',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='turbinavapor',
            name='modelo',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
