# Generated by Django 4.2.4 on 2024-05-14 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turbinas', '0006_alter_entradacorriente_presion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entradacorriente',
            name='corriente',
        ),
        migrations.RemoveField(
            model_name='salidacorriente',
            name='corriente',
        ),
        migrations.CreateModel(
            name='CorrienteEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corriente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='turbinas.corriente')),
                ('entrada', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='turbinas.entradacorriente')),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='corrientes_evaluacion', to='turbinas.evaluacion')),
                ('salida', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='turbinas.salidacorriente')),
            ],
        ),
    ]
