# Generated by Django 4.2.4 on 2024-05-14 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turbinas', '0007_remove_entradacorriente_corriente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entradacorriente',
            name='entrada',
        ),
        migrations.RemoveField(
            model_name='salidacorriente',
            name='salida',
        ),
    ]
