# Generated by Django 4.2.4 on 2024-05-15 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turbinas', '0008_remove_entradacorriente_entrada_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='corrienteevaluacion',
            table='turbinas_vapor_evaluacion_corriente',
        ),
        migrations.AlterModelTable(
            name='datoscorrientes',
            table='turbinas_vapor_datoscorrientes',
        ),
        migrations.AlterModelTable(
            name='entradacorriente',
            table='turbinas_vapor_evaluacion_entradacorriente',
        ),
        migrations.AlterModelTable(
            name='entradaevaluacion',
            table='turbinas_vapor_evaluacion_entrada',
        ),
        migrations.AlterModelTable(
            name='especificacionesturbinavapor',
            table='turbinas_vapor_gespecificaciones',
        ),
        migrations.AlterModelTable(
            name='evaluacion',
            table='turbinas_vapor_evaluacion',
        ),
        migrations.AlterModelTable(
            name='generadorelectrico',
            table='turbinas_vapor_generadorelectrico',
        ),
        migrations.AlterModelTable(
            name='salidacorriente',
            table='turbinas_vapor_evaluacion_salidacorriente',
        ),
        migrations.AlterModelTable(
            name='salidaevaluacion',
            table='turbinas_vapor_evaluacion_salida',
        ),
        migrations.AlterModelTable(
            name='turbinavapor',
            table='turbinas_vapor_turbinavapor',
        ),
    ]
