# Generated by Django 4.2.4 on 2024-05-15 10:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('turbinas', '0009_alter_corrienteevaluacion_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corrienteevaluacion',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
