# Generated by Django 4.2.4 on 2024-05-16 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turbinas', '0010_alter_corrienteevaluacion_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='corrienteevaluacion',
            options={'ordering': ('-corriente__entrada', 'corriente__numero_corriente')},
        ),
        migrations.AlterModelTable(
            name='especificacionesturbinavapor',
            table='turbinas_vapor_especificaciones',
        ),
    ]
