# Generated by Django 4.2.4 on 2024-08-07 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turbinas', '0012_alter_entradacorriente_presion'),
    ]

    operations = [
        migrations.AddField(
            model_name='turbinavapor',
            name='copia',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
