# Generated by Django 4.2.4 on 2024-08-07 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turbinas', '0013_turbinavapor_copia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turbinavapor',
            name='tag',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
