# Generated by Django 4.2.4 on 2024-08-07 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turbinas', '0014_alter_turbinavapor_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluacion',
            name='equipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluaciones_turbinasvapor', to='turbinas.turbinavapor'),
        ),
    ]
