# Generated by Django 4.2.4 on 2024-10-17 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turbinas', '0015_alter_evaluacion_equipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corriente',
            name='fase',
            field=models.CharField(choices=[('S', 'Saturado'), ('L', 'Líquido'), ('V', 'Vapor')], max_length=1),
        ),
        migrations.AlterField(
            model_name='salidacorriente',
            name='fase',
            field=models.CharField(choices=[('S', 'Saturado'), ('L', 'Líquido'), ('V', 'Vapor')], max_length=1),
        ),
    ]
