# Generated by Django 4.2.4 on 2024-10-21 09:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turbinas', '0016_alter_corriente_fase_alter_salidacorriente_fase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corriente',
            name='fase',
            field=models.CharField(choices=[('S', 'Vapor Saturado'), ('V', 'Vapor')], max_length=1),
        ),
        migrations.AlterField(
            model_name='especificacionesturbinavapor',
            name='contra_presion',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1e-06)], verbose_name='Contra Presión'),
        ),
        migrations.AlterField(
            model_name='especificacionesturbinavapor',
            name='eficiencia',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='especificacionesturbinavapor',
            name='potencia',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1e-06)]),
        ),
        migrations.AlterField(
            model_name='especificacionesturbinavapor',
            name='potencia_max',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1e-06)], verbose_name='Potencia Máxima'),
        ),
        migrations.AlterField(
            model_name='especificacionesturbinavapor',
            name='presion_entrada',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1e-06)], verbose_name='Presión de Entrada'),
        ),
        migrations.AlterField(
            model_name='especificacionesturbinavapor',
            name='temperatura_entrada',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1e-06)], verbose_name='Temperatura de Entrada'),
        ),
        migrations.AlterField(
            model_name='especificacionesturbinavapor',
            name='velocidad',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1e-06)]),
        ),
        migrations.AlterField(
            model_name='generadorelectrico',
            name='ciclos',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='generadorelectrico',
            name='corriente_electrica',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1e-06)], verbose_name='Corriente Eléctrica'),
        ),
        migrations.AlterField(
            model_name='generadorelectrico',
            name='fases',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='generadorelectrico',
            name='polos',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='generadorelectrico',
            name='potencia_aparente',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1e-06)], verbose_name='Potencia Aparente'),
        ),
        migrations.AlterField(
            model_name='generadorelectrico',
            name='potencia_real',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1e-06)], verbose_name='Potencia Real'),
        ),
        migrations.AlterField(
            model_name='generadorelectrico',
            name='velocidad',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1e-06)]),
        ),
        migrations.AlterField(
            model_name='generadorelectrico',
            name='voltaje',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1e-06)]),
        ),
        migrations.AlterField(
            model_name='salidacorriente',
            name='fase',
            field=models.CharField(choices=[('S', 'Vapor Saturado'), ('V', 'Vapor')], max_length=1),
        ),
    ]
