# Generated by Django 4.2.4 on 2024-10-21 09:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turbinas', '0017_alter_corriente_fase_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especificacionesturbinavapor',
            name='potencia',
            field=models.FloatField(default=100, validators=[django.core.validators.MinValueValidator(1e-06)]),
            preserve_default=False,
        ),
    ]
