# Generated by Django 4.2.4 on 2024-10-25 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turbinas', '0018_alter_especificacionesturbinavapor_potencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salidacorriente',
            name='entalpia',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salidacorriente',
            name='fase',
            field=models.CharField(choices=[('S', 'Vapor Saturado'), ('V', 'Vapor'), ('L', 'Líquido')], max_length=1),
        ),
    ]
