# Generated by Django 4.2.4 on 2024-10-25 14:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turbinas', '0019_alter_salidacorriente_entalpia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corriente',
            name='entalpia',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1e-05)]),
        ),
    ]
