# Generated by Django 4.2.4 on 2024-10-28 09:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turbinas', '0020_alter_corriente_entalpia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corriente',
            name='temperatura',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-273.15)]),
        ),
        migrations.AlterField(
            model_name='entradacorriente',
            name='temperatura',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-273.15)]),
        ),
    ]
