# Generated by Django 4.2.4 on 2024-10-31 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turbinas', '0021_alter_corriente_temperatura_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salidacorriente',
            name='fase',
            field=models.CharField(choices=[('S', 'Vapor Saturado'), ('V', 'Vapor'), ('L', 'Líquido'), ('F', 'Fluido Supercrítico')], max_length=1),
        ),
    ]
