# Generated by Django 4.2.4 on 2024-03-12 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliares', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Material',
            new_name='MaterialTuberia',
        ),
    ]
