# Generated by Django 4.2.4 on 2024-03-12 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intercambiadores', '0068_propiedadesdobletubo_altura_aletas_and_more'),
        ('auxiliares', '0002_rename_material_materialtuberia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bombas',
            name='especificaciones_instalacion',
        ),
        migrations.RemoveField(
            model_name='condicionesdisenobomba',
            name='presion_diferencial_descarga',
        ),
        migrations.RemoveField(
            model_name='condicionesdisenobomba',
            name='presion_diferencial_succion',
        ),
        migrations.RemoveField(
            model_name='especificacionesinstalacion',
            name='elevacion_succion',
        ),
        migrations.AddField(
            model_name='condicionesdisenobomba',
            name='capacidad_unidad',
            field=models.ForeignKey(default=34, on_delete=django.db.models.deletion.CASCADE, related_name='capacidad_unidad_condicionesdisenobomba', to='intercambiadores.unidades'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='condicionesdisenobomba',
            name='npsha_unidad',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='npsha_unidad_condicionesdisenobomba', to='intercambiadores.unidades'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='condicionesdisenobomba',
            name='presion_diferencial',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='condicionfluidobomba',
            name='temperatura_unidad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='temperatura_unidad_condicionesdisenobomba', to='intercambiadores.unidades'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='condicionfluidobomba',
            name='viscosidad_unidad',
            field=models.ForeignKey(default=35, on_delete=django.db.models.deletion.CASCADE, related_name='viscosidad_unidad_condicionesdisenobomba', to='intercambiadores.unidades'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='especificacionesinstalacion',
            name='bomba',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auxiliares.bombas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='especificacionesinstalacion',
            name='elevacion',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='bombas',
            name='creado_al',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='bombas',
            name='grafica',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='condicionesdisenobomba',
            name='npsha',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='condicionfluidobomba',
            name='concentracion_cloro',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='condicionfluidobomba',
            name='concentracion_h2s',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='condicionfluidobomba',
            name='densidad_relativa',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='condicionfluidobomba',
            name='presion_vapor',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='condicionfluidobomba',
            name='temperatura_presion_vapor',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='condicionfluidobomba',
            name='viscosidad',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='detallesconstruccionbomba',
            name='carcasa_dividida',
            field=models.CharField(choices=[('A', 'Axial'), ('R', 'Radial')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='detallesconstruccionbomba',
            name='tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auxiliares.tipobombaconstruccion'),
        ),
        migrations.AlterField(
            model_name='detallesconstruccionbomba',
            name='tipo_carcasa1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipo_carcasa_construccion1', to='auxiliares.tipocarcasabomba'),
        ),
        migrations.AlterField(
            model_name='detallesconstruccionbomba',
            name='tipo_carcasa2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipo_carcasa_construccion2', to='auxiliares.tipocarcasabomba'),
        ),
        migrations.AlterField(
            model_name='especificacionesbomba',
            name='material_tuberia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auxiliares.materialtuberia'),
        ),
        migrations.AlterField(
            model_name='especificacionesinstalacion',
            name='longitud_tuberia_unidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='longitud_tuberia_unidad_especificacionesinstalacion', to='intercambiadores.unidades'),
        ),
    ]
