# Generated by Django 4.2.4 on 2024-03-12 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intercambiadores', '0068_propiedadesdobletubo_altura_aletas_and_more'),
        ('auxiliares', '0003_remove_bombas_especificaciones_instalacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallesmotorbomba',
            name='velocidad_unidad',
            field=models.ForeignKey(default=38, on_delete=django.db.models.deletion.CASCADE, related_name='velocidad_unidad_detallesmotor', to='intercambiadores.unidades'),
            preserve_default=False,
        ),
    ]
