# Generated by Django 4.2.4 on 2024-03-12 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliares', '0004_detallesmotorbomba_velocidad_unidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especificacionesbomba',
            name='npshr',
            field=models.FloatField(null=True),
        ),
    ]
