# Generated by Django 4.2.4 on 2024-03-12 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intercambiadores', '0068_propiedadesdobletubo_altura_aletas_and_more'),
        ('auxiliares', '0005_alter_especificacionesbomba_npshr'),
    ]

    operations = [
        migrations.AddField(
            model_name='condicionfluidobomba',
            name='presion_unidad',
            field=models.ForeignKey(default=26, on_delete=django.db.models.deletion.CASCADE, related_name='presion_unidad_condicionesfluido', to='intercambiadores.unidades'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='condicionfluidobomba',
            name='concentracion_unidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concentracion_unidad_condicionesfluido', to='intercambiadores.unidades'),
        ),
    ]
