# Generated by Django 4.2.4 on 2024-03-13 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intercambiadores', '0068_propiedadesdobletubo_altura_aletas_and_more'),
        ('auxiliares', '0006_condicionfluidobomba_presion_unidad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='especificacionesinstalacion',
            name='bomba',
        ),
        migrations.RemoveField(
            model_name='especificacionesinstalacion',
            name='lado',
        ),
        migrations.AddField(
            model_name='bombas',
            name='instalacion_descarga',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='instalacion_descarga', to='auxiliares.especificacionesinstalacion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bombas',
            name='instalacion_succion',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='instalacion_succion', to='auxiliares.especificacionesinstalacion'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='condicionfluidobomba',
            name='corrosividad',
            field=models.CharField(choices=[('C', 'Corrosivo'), ('E', 'Erosivo'), ('N', 'No Errosivo ni Corrosivo'), ('A', 'Ambos'), ('D', 'Desconocido')], max_length=1),
        ),
        migrations.AlterField(
            model_name='condicionfluidobomba',
            name='fluido',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='intercambiadores.fluido'),
        ),
    ]
