# Generated by Django 4.2.4 on 2024-03-14 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliares', '0007_remove_especificacionesinstalacion_bomba_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='especificacionesinstalacion',
            name='numero_valvula_angulo_abiertas',
        ),
        migrations.RemoveField(
            model_name='especificacionesinstalacion',
            name='numero_valvula_globo_abiertas',
        ),
        migrations.RemoveField(
            model_name='especificacionesinstalacion',
            name='numero_valvulas_mariposa_10_14_abiertas',
        ),
        migrations.RemoveField(
            model_name='especificacionesinstalacion',
            name='numero_valvulas_mariposa_16_24_abiertas',
        ),
        migrations.RemoveField(
            model_name='especificacionesinstalacion',
            name='numero_valvulas_mariposa_2_8_abiertas',
        ),
        migrations.AddField(
            model_name='especificacionesinstalacion',
            name='diametro_tuberia',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='bombas',
            name='grafica',
            field=models.FileField(null=True, upload_to='C:\\Users\\dfaria\\Documents\\sievep\\sievep_indesca\\mediaauxiliares/bombas/'),
        ),
        migrations.AlterField(
            model_name='bombas',
            name='instalacion_descarga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instalacion_descarga', to='auxiliares.especificacionesinstalacion'),
        ),
        migrations.AlterField(
            model_name='bombas',
            name='instalacion_succion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instalacion_succion', to='auxiliares.especificacionesinstalacion'),
        ),
    ]
