# Generated by Django 4.2.4 on 2024-03-14 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intercambiadores', '0068_propiedadesdobletubo_altura_aletas_and_more'),
        ('auxiliares', '0008_remove_especificacionesinstalacion_numero_valvula_angulo_abiertas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='especificacionesinstalacion',
            name='diametro_tuberia_unidad',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='diametro_tuberia_unidad_especificacionesinstalacion', to='intercambiadores.unidades'),
            preserve_default=False,
        ),
    ]
