# Generated by Django 4.2.4 on 2024-03-14 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliares', '0009_especificacionesinstalacion_diametro_tuberia_unidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='especificacionesinstalacion',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
