# Generated by Django 4.2.4 on 2024-03-15 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliares', '0011_remove_especificacionesbomba_entrada_achaflamada_succion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bombas',
            options={'ordering': ('tag',)},
        ),
        migrations.AlterField(
            model_name='bombas',
            name='descripcion',
            field=models.CharField(max_length=80, verbose_name='Descripción del Equipo*'),
        ),
        migrations.AlterField(
            model_name='bombas',
            name='fabricante',
            field=models.CharField(max_length=45, verbose_name='Fabricante*'),
        ),
        migrations.AlterField(
            model_name='bombas',
            name='grafica',
            field=models.ImageField(null=True, upload_to='C:\\Users\\dfaria\\Documents\\sievep\\sievep_indesca\\mediaauxiliares/bombas/', verbose_name='Gráfica del Equipo'),
        ),
        migrations.AlterField(
            model_name='bombas',
            name='modelo',
            field=models.CharField(max_length=45, null=True, verbose_name='Modelo del Equipo'),
        ),
        migrations.AlterField(
            model_name='bombas',
            name='tag',
            field=models.CharField(max_length=45, unique=True, verbose_name='Tag del Equipo*'),
        ),
        migrations.AlterField(
            model_name='bombas',
            name='tipo_bomba',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auxiliares.tipobomba', verbose_name='Tipo de Bomba'),
        ),
        migrations.AlterField(
            model_name='especificacionesbomba',
            name='descarga_id',
            field=models.FloatField(verbose_name='Diámetro Interno Descarga'),
        ),
        migrations.AlterField(
            model_name='especificacionesbomba',
            name='npshr',
            field=models.FloatField(null=True, verbose_name='Altura Neta Positiva Succión (NPSHr)'),
        ),
        migrations.AlterField(
            model_name='especificacionesbomba',
            name='numero_curva',
            field=models.CharField(max_length=10, null=True, verbose_name='Número de Curva'),
        ),
        migrations.AlterField(
            model_name='especificacionesbomba',
            name='numero_etapas',
            field=models.SmallIntegerField(verbose_name='Número de Etapas'),
        ),
        migrations.AlterField(
            model_name='especificacionesbomba',
            name='potencia_maxima',
            field=models.FloatField(verbose_name='Potencia Máxima'),
        ),
        migrations.AlterField(
            model_name='especificacionesbomba',
            name='succion_id',
            field=models.FloatField(verbose_name='Diámetro Interno Succión'),
        ),
    ]
