# Generated by Django 4.2.4 on 2024-03-15 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliares', '0012_alter_bombas_options_alter_bombas_descripcion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='especificacionesbomba',
            name='material_tuberia',
        ),
        migrations.AddField(
            model_name='especificacionesinstalacion',
            name='material_tuberia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auxiliares.materialtuberia'),
        ),
    ]
