# Generated by Django 4.2.4 on 2024-03-15 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intercambiadores', '0068_propiedadesdobletubo_altura_aletas_and_more'),
        ('auxiliares', '0013_remove_especificacionesbomba_material_tuberia_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='condicionfluidobomba',
            old_name='presion_unidad',
            new_name='presion_vapor_unidad',
        ),
        migrations.AlterField(
            model_name='condicionesdisenobomba',
            name='capacidad',
            field=models.FloatField(verbose_name='Capacidad*'),
        ),
        migrations.AlterField(
            model_name='condicionesdisenobomba',
            name='npsha',
            field=models.FloatField(null=True, verbose_name='NPSHa'),
        ),
        migrations.AlterField(
            model_name='condicionesdisenobomba',
            name='presion_descarga',
            field=models.FloatField(verbose_name='Presión de la Descarga*'),
        ),
        migrations.AlterField(
            model_name='condicionesdisenobomba',
            name='presion_diferencial',
            field=models.FloatField(null=True, verbose_name='Presión Diferencial'),
        ),
        migrations.AlterField(
            model_name='condicionesdisenobomba',
            name='presion_succion',
            field=models.FloatField(verbose_name='Presión de la Succión*'),
        ),
        migrations.AlterField(
            model_name='condicionfluidobomba',
            name='calculo_propiedades',
            field=models.CharField(choices=[('M', 'Manual'), ('A', 'Automático')], default='M', max_length=1, verbose_name='Cálculo de Propiedades'),
        ),
        migrations.AlterField(
            model_name='condicionfluidobomba',
            name='concentracion_cloro',
            field=models.FloatField(null=True, verbose_name='Concentración de Cloro'),
        ),
        migrations.AlterField(
            model_name='condicionfluidobomba',
            name='concentracion_h2s',
            field=models.FloatField(null=True, verbose_name='Concentración de H₂S'),
        ),
        migrations.AlterField(
            model_name='condicionfluidobomba',
            name='corrosividad',
            field=models.CharField(choices=[('C', 'Corrosivo'), ('E', 'Erosivo'), ('N', 'No Errosivo ni Corrosivo'), ('A', 'Ambos'), ('D', 'Desconocido')], max_length=1, verbose_name='Corrosivo/Erosivo*'),
        ),
        migrations.AlterField(
            model_name='condicionfluidobomba',
            name='fluido',
            field=models.ForeignKey(default=73, on_delete=django.db.models.deletion.CASCADE, to='intercambiadores.fluido', verbose_name='Fluido*'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='condicionfluidobomba',
            name='inflamable',
            field=models.CharField(choices=[('S', 'Sí'), ('N', 'No'), ('D', 'Desconocido')], max_length=1, verbose_name='Inflamable*'),
        ),
        migrations.AlterField(
            model_name='condicionfluidobomba',
            name='peligroso',
            field=models.CharField(choices=[('S', 'Sí'), ('N', 'No'), ('D', 'Desconocido')], max_length=1, verbose_name='Peligroso*'),
        ),
        migrations.AlterField(
            model_name='condicionfluidobomba',
            name='temperatura_operacion',
            field=models.FloatField(verbose_name='Temperatura de Operación*'),
        ),
        migrations.AlterField(
            model_name='especificacionesbomba',
            name='npshr',
            field=models.FloatField(null=True, verbose_name='NPSHr'),
        ),
    ]
