# Generated by Django 4.2.4 on 2024-03-15 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intercambiadores', '0068_propiedadesdobletubo_altura_aletas_and_more'),
        ('auxiliares', '0014_rename_presion_unidad_condicionfluidobomba_presion_vapor_unidad_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='condicionfluidobomba',
            old_name='densidad_relativa',
            new_name='densidad',
        ),
        migrations.AddField(
            model_name='condicionfluidobomba',
            name='densidad_unidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='densidad_unidad_condicionesdisenobomba', to='intercambiadores.unidades'),
        ),
    ]
