# Generated by Django 4.2.4 on 2024-03-15 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliares', '0015_rename_densidad_relativa_condicionfluidobomba_densidad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallesconstruccionbomba',
            name='modelo',
        ),
        migrations.AddField(
            model_name='detallesconstruccionbomba',
            name='modelo_construccion',
            field=models.CharField(max_length=45, null=True, verbose_name='Modelo de Construcción'),
        ),
        migrations.AlterField(
            model_name='condicionesdisenobomba',
            name='presion_descarga',
            field=models.FloatField(verbose_name='Presión de Descarga*'),
        ),
        migrations.AlterField(
            model_name='condicionesdisenobomba',
            name='presion_succion',
            field=models.FloatField(verbose_name='Presión de Succión*'),
        ),
        migrations.AlterField(
            model_name='condicionfluidobomba',
            name='presion_vapor',
            field=models.FloatField(null=True, verbose_name='Presión de Vapor'),
        ),
        migrations.AlterField(
            model_name='condicionfluidobomba',
            name='temperatura_presion_vapor',
            field=models.FloatField(null=True, verbose_name='Temperatura a la Presión de Vapor'),
        ),
        migrations.AlterField(
            model_name='detallesconstruccionbomba',
            name='carcasa_dividida',
            field=models.CharField(choices=[('A', 'Axial'), ('R', 'Radial')], max_length=1, null=True, verbose_name='Carcasa Dividida'),
        ),
        migrations.AlterField(
            model_name='detallesconstruccionbomba',
            name='conexion_descarga',
            field=models.PositiveIntegerField(null=True, verbose_name='Conexión de Descarga'),
        ),
        migrations.AlterField(
            model_name='detallesconstruccionbomba',
            name='conexion_succion',
            field=models.PositiveIntegerField(null=True, verbose_name='Conexión de Succión'),
        ),
        migrations.AlterField(
            model_name='detallesconstruccionbomba',
            name='fabricante_sello',
            field=models.CharField(max_length=45, null=True, verbose_name='Fabricante de Sello'),
        ),
        migrations.AlterField(
            model_name='detallesconstruccionbomba',
            name='tamano_rating_descarga',
            field=models.FloatField(null=True, verbose_name='Tamaño Rating (Descarga)'),
        ),
        migrations.AlterField(
            model_name='detallesconstruccionbomba',
            name='tamano_rating_succion',
            field=models.FloatField(null=True, verbose_name='Tamaño Rating (Succión)'),
        ),
        migrations.AlterField(
            model_name='detallesconstruccionbomba',
            name='tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auxiliares.tipobombaconstruccion', verbose_name='Tipo por Construcción'),
        ),
        migrations.AlterField(
            model_name='detallesconstruccionbomba',
            name='tipo_carcasa1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipo_carcasa_construccion1', to='auxiliares.tipocarcasabomba', verbose_name='Tipo de Carcasa (1)'),
        ),
        migrations.AlterField(
            model_name='detallesconstruccionbomba',
            name='tipo_carcasa2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipo_carcasa_construccion2', to='auxiliares.tipocarcasabomba', verbose_name='Tipo de Carcasa (2)'),
        ),
        migrations.AlterField(
            model_name='detallesmotorbomba',
            name='factor_de_servicio',
            field=models.FloatField(null=True, verbose_name='Factor de Servicio'),
        ),
        migrations.AlterField(
            model_name='detallesmotorbomba',
            name='potencia',
            field=models.FloatField(null=True, verbose_name='Potencia del Motor'),
        ),
        migrations.AlterField(
            model_name='detallesmotorbomba',
            name='velocidad',
            field=models.FloatField(verbose_name='Velocidad del Motor'),
        ),
        migrations.AlterField(
            model_name='detallesmotorbomba',
            name='voltaje',
            field=models.FloatField(null=True, verbose_name='Voiltaje del Motor'),
        ),
    ]
