# Generated by Django 4.2.4 on 2024-03-19 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliares', '0016_remove_detallesconstruccionbomba_modelo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detallesmotorbomba',
            old_name='potencia',
            new_name='potencia_motor',
        ),
        migrations.RenameField(
            model_name='detallesmotorbomba',
            old_name='potencia_unidad',
            new_name='potencia_motor_unidad',
        ),
        migrations.RenameField(
            model_name='detallesmotorbomba',
            old_name='velocidad',
            new_name='velocidad_motor',
        ),
        migrations.RenameField(
            model_name='detallesmotorbomba',
            old_name='velocidad_unidad',
            new_name='velocidad_motor_unidad',
        ),
        migrations.AlterField(
            model_name='detallesmotorbomba',
            name='voltaje',
            field=models.FloatField(null=True, verbose_name='Voltaje del Motor'),
        ),
    ]
