# Generated by Django 4.2.4 on 2024-03-20 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intercambiadores', '0068_propiedadesdobletubo_altura_aletas_and_more'),
        ('auxiliares', '0017_rename_potencia_detallesmotorbomba_potencia_motor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bombas',
            name='grafica',
            field=models.ImageField(blank=True, null=True, upload_to='C:\\Users\\dfaria\\Documents\\sievep\\sievep_indesca\\mediaauxiliares/bombas/', verbose_name='Gráfica del Equipo'),
        ),
        migrations.AlterField(
            model_name='bombas',
            name='modelo',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Modelo del Equipo'),
        ),
        migrations.AlterField(
            model_name='condicionesdisenobomba',
            name='npsha',
            field=models.FloatField(blank=True, null=True, verbose_name='NPSHa'),
        ),
        migrations.AlterField(
            model_name='condicionesdisenobomba',
            name='presion_diferencial',
            field=models.FloatField(blank=True, null=True, verbose_name='Presión Diferencial'),
        ),
        migrations.AlterField(
            model_name='condicionfluidobomba',
            name='concentracion_cloro',
            field=models.FloatField(blank=True, null=True, verbose_name='Concentración de Cloro'),
        ),
        migrations.AlterField(
            model_name='condicionfluidobomba',
            name='concentracion_h2s',
            field=models.FloatField(blank=True, null=True, verbose_name='Concentración de H₂S'),
        ),
        migrations.AlterField(
            model_name='condicionfluidobomba',
            name='densidad',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='condicionfluidobomba',
            name='densidad_unidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='densidad_unidad_condicionesdisenobomba', to='intercambiadores.unidades'),
        ),
        migrations.AlterField(
            model_name='condicionfluidobomba',
            name='fluido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='intercambiadores.fluido', verbose_name='Fluido*'),
        ),
        migrations.AlterField(
            model_name='condicionfluidobomba',
            name='nombre_fluido',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='condicionfluidobomba',
            name='presion_vapor',
            field=models.FloatField(blank=True, null=True, verbose_name='Presión de Vapor'),
        ),
        migrations.AlterField(
            model_name='condicionfluidobomba',
            name='viscosidad',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detallesconstruccionbomba',
            name='carcasa_dividida',
            field=models.CharField(blank=True, choices=[('A', 'Axial'), ('R', 'Radial')], max_length=1, null=True, verbose_name='Carcasa Dividida'),
        ),
        migrations.AlterField(
            model_name='detallesconstruccionbomba',
            name='conexion_descarga',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Conexión de Descarga'),
        ),
        migrations.AlterField(
            model_name='detallesconstruccionbomba',
            name='conexion_succion',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Conexión de Succión'),
        ),
        migrations.AlterField(
            model_name='detallesconstruccionbomba',
            name='fabricante_sello',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Fabricante de Sello'),
        ),
        migrations.AlterField(
            model_name='detallesconstruccionbomba',
            name='modelo_construccion',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Modelo de Construcción'),
        ),
        migrations.AlterField(
            model_name='detallesconstruccionbomba',
            name='tamano_rating_descarga',
            field=models.FloatField(blank=True, null=True, verbose_name='Tamaño Rating (Descarga)'),
        ),
        migrations.AlterField(
            model_name='detallesconstruccionbomba',
            name='tamano_rating_succion',
            field=models.FloatField(blank=True, null=True, verbose_name='Tamaño Rating (Succión)'),
        ),
        migrations.AlterField(
            model_name='detallesconstruccionbomba',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auxiliares.tipobombaconstruccion', verbose_name='Tipo por Construcción'),
        ),
        migrations.AlterField(
            model_name='detallesconstruccionbomba',
            name='tipo_carcasa1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipo_carcasa_construccion1', to='auxiliares.tipocarcasabomba', verbose_name='Tipo de Carcasa (1)'),
        ),
        migrations.AlterField(
            model_name='detallesconstruccionbomba',
            name='tipo_carcasa2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipo_carcasa_construccion2', to='auxiliares.tipocarcasabomba', verbose_name='Tipo de Carcasa (2)'),
        ),
        migrations.AlterField(
            model_name='detallesmotorbomba',
            name='aislamiento',
            field=models.CharField(blank=True, choices=[('F', 'CLASE F')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='detallesmotorbomba',
            name='arranque',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='detallesmotorbomba',
            name='factor_de_servicio',
            field=models.FloatField(blank=True, null=True, verbose_name='Factor de Servicio'),
        ),
        migrations.AlterField(
            model_name='detallesmotorbomba',
            name='posicion',
            field=models.CharField(blank=True, choices=[('H', 'Horizontal'), ('V', 'Vertical')], max_length=1, null=True, verbose_name='Posición del Motor'),
        ),
        migrations.AlterField(
            model_name='detallesmotorbomba',
            name='potencia_motor',
            field=models.FloatField(blank=True, null=True, verbose_name='Potencia del Motor'),
        ),
        migrations.AlterField(
            model_name='especificacionesbomba',
            name='npshr',
            field=models.FloatField(blank=True, null=True, verbose_name='NPSHr'),
        ),
        migrations.AlterField(
            model_name='especificacionesbomba',
            name='numero_curva',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Número de Curva'),
        ),
        migrations.AlterField(
            model_name='especificacionesinstalacion',
            name='diametro_tuberia_unidad',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='diametro_tuberia_unidad_especificacionesinstalacion', to='intercambiadores.unidades'),
        ),
        migrations.AlterField(
            model_name='especificacionesinstalacion',
            name='elevacion_unidad',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='elevacion_unidad_especificacionesinstalacion', to='intercambiadores.unidades'),
        ),
        migrations.AlterField(
            model_name='especificacionesinstalacion',
            name='longitud_tuberia_unidad',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='longitud_tuberia_unidad_especificacionesinstalacion', to='intercambiadores.unidades'),
        ),
        migrations.AlterField(
            model_name='especificacionesinstalacion',
            name='numero_codos_90_rl',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Número de Codos a 90°'),
        ),
    ]
