# Generated by Django 4.2.4 on 2024-03-21 09:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intercambiadores', '0068_propiedadesdobletubo_altura_aletas_and_more'),
        ('auxiliares', '0018_alter_bombas_grafica_alter_bombas_modelo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='especificacionesinstalacion',
            name='diametro_tuberia',
        ),
        migrations.RemoveField(
            model_name='especificacionesinstalacion',
            name='diametro_tuberia_unidad',
        ),
        migrations.RemoveField(
            model_name='especificacionesinstalacion',
            name='longitud_tuberia',
        ),
        migrations.RemoveField(
            model_name='especificacionesinstalacion',
            name='longitud_tuberia_unidad',
        ),
        migrations.RemoveField(
            model_name='especificacionesinstalacion',
            name='material_tuberia',
        ),
        migrations.AlterField(
            model_name='bombas',
            name='grafica',
            field=models.ImageField(blank=True, null=True, upload_to='C:\\Users\\dfaria\\Documents\\sievep\\sievep_indesca\\media/auxiliares/bombas/', verbose_name='Gráfica del Equipo'),
        ),
        migrations.AlterField(
            model_name='detallesconstruccionbomba',
            name='tamano_rating_descarga',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Tamaño Rating (Descarga)'),
        ),
        migrations.AlterField(
            model_name='detallesconstruccionbomba',
            name='tamano_rating_succion',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Tamaño Rating (Succión)'),
        ),
        migrations.CreateModel(
            name='TuberiaInstalacionBomba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitud_tuberia', models.FloatField(null=True)),
                ('diametro_tuberia', models.FloatField(null=True)),
                ('numero_tubos', models.PositiveIntegerField(null=True)),
                ('diametro_tuberia_unidad', models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='diametro_tuberia_unidad_especificacionesinstalacion', to='intercambiadores.unidades')),
                ('instalacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auxiliares.especificacionesinstalacion')),
                ('longitud_tuberia_unidad', models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='longitud_tuberia_unidad_especificacionesinstalacion', to='intercambiadores.unidades')),
                ('material_tuberia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auxiliares.materialtuberia')),
            ],
        ),
    ]
