# Generated by Django 4.2.4 on 2024-03-21 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliares', '0019_remove_especificacionesinstalacion_diametro_tuberia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='especificacionesinstalacion',
            name='fecha',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='especificacionesinstalacion',
            name='conexiones_t_directo',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='especificacionesinstalacion',
            name='conexiones_t_ramal',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='especificacionesinstalacion',
            name='elevacion',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='especificacionesinstalacion',
            name='numero_codos_180',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='especificacionesinstalacion',
            name='numero_codos_45',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='especificacionesinstalacion',
            name='numero_codos_45_ros',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='especificacionesinstalacion',
            name='numero_codos_90',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='especificacionesinstalacion',
            name='numero_codos_90_ros',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='especificacionesinstalacion',
            name='numero_contracciones_linea',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='especificacionesinstalacion',
            name='numero_expansiones_linea',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='especificacionesinstalacion',
            name='numero_valvula_angulo',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='especificacionesinstalacion',
            name='numero_valvula_bisagra',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='especificacionesinstalacion',
            name='numero_valvula_bola',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='especificacionesinstalacion',
            name='numero_valvula_giratoria',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='especificacionesinstalacion',
            name='numero_valvula_globo',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='especificacionesinstalacion',
            name='numero_valvula_vastago',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='especificacionesinstalacion',
            name='numero_valvulas_compuerta',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='especificacionesinstalacion',
            name='numero_valvulas_compuerta_abierta_1_2',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='especificacionesinstalacion',
            name='numero_valvulas_compuerta_abierta_1_4',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='especificacionesinstalacion',
            name='numero_valvulas_compuerta_abierta_3_4',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='especificacionesinstalacion',
            name='numero_valvulas_mariposa_10_14',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='especificacionesinstalacion',
            name='numero_valvulas_mariposa_16_24',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='especificacionesinstalacion',
            name='numero_valvulas_mariposa_2_8',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
