# Generated by Django 4.2.4 on 2024-03-21 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auxiliares', '0020_especificacionesinstalacion_fecha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='especificacionesinstalacion',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='especificacionesinstalacion',
            name='conexiones_t_directo',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Conexiones T Flujo Directo'),
        ),
        migrations.AlterField(
            model_name='especificacionesinstalacion',
            name='conexiones_t_ramal',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Conexiones T Flujo Ramal°'),
        ),
        migrations.AlterField(
            model_name='especificacionesinstalacion',
            name='numero_codos_180',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Núm. de Codos a 180°'),
        ),
        migrations.AlterField(
            model_name='especificacionesinstalacion',
            name='numero_codos_45',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Núm. Codos a 45'),
        ),
        migrations.AlterField(
            model_name='especificacionesinstalacion',
            name='numero_codos_45_ros',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Núm. de Codos Roscados a 45°'),
        ),
        migrations.AlterField(
            model_name='especificacionesinstalacion',
            name='numero_codos_90',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Núm. Codos a 90°'),
        ),
        migrations.AlterField(
            model_name='especificacionesinstalacion',
            name='numero_codos_90_rl',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Núm. Codos a 90° Radio Largo'),
        ),
        migrations.AlterField(
            model_name='especificacionesinstalacion',
            name='numero_codos_90_ros',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Núm. Codos Roscados a 90°'),
        ),
        migrations.AlterField(
            model_name='especificacionesinstalacion',
            name='numero_contracciones_linea',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Núm. de Contracciones'),
        ),
        migrations.AlterField(
            model_name='especificacionesinstalacion',
            name='numero_expansiones_linea',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Núm. de Expansiones'),
        ),
        migrations.AlterField(
            model_name='especificacionesinstalacion',
            name='numero_valvula_angulo',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Núm. de Vál. Ángulo'),
        ),
        migrations.AlterField(
            model_name='especificacionesinstalacion',
            name='numero_valvula_bisagra',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Núm. de Vál. Bisagra'),
        ),
        migrations.AlterField(
            model_name='especificacionesinstalacion',
            name='numero_valvula_bola',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Núm. de Vál. Bola'),
        ),
        migrations.AlterField(
            model_name='especificacionesinstalacion',
            name='numero_valvula_giratoria',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Núm. de Vál. Giratorias'),
        ),
        migrations.AlterField(
            model_name='especificacionesinstalacion',
            name='numero_valvula_globo',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Núm. de Vál. Globo'),
        ),
        migrations.AlterField(
            model_name='especificacionesinstalacion',
            name='numero_valvula_vastago',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Núm. de Vál. Vástago'),
        ),
        migrations.AlterField(
            model_name='especificacionesinstalacion',
            name='numero_valvulas_compuerta',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Núm. de Vál. de Compuerta'),
        ),
        migrations.AlterField(
            model_name='especificacionesinstalacion',
            name='numero_valvulas_compuerta_abierta_1_2',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Núm. de Vál. Compuerta a 1/2'),
        ),
        migrations.AlterField(
            model_name='especificacionesinstalacion',
            name='numero_valvulas_compuerta_abierta_1_4',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Núm. de Vál. Compuerta a 1/4'),
        ),
        migrations.AlterField(
            model_name='especificacionesinstalacion',
            name='numero_valvulas_compuerta_abierta_3_4',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Núm. de Vál. Compuerta a 3/4'),
        ),
        migrations.AlterField(
            model_name='especificacionesinstalacion',
            name='numero_valvulas_mariposa_10_14',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Núm. de Vál. Mariposa 10"-14"'),
        ),
        migrations.AlterField(
            model_name='especificacionesinstalacion',
            name='numero_valvulas_mariposa_16_24',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Núm. de Vál. Mariposa 16"-24"'),
        ),
        migrations.AlterField(
            model_name='especificacionesinstalacion',
            name='numero_valvulas_mariposa_2_8',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Núm. de Vál. Mariposa 2"-8"'),
        ),
        migrations.AlterField(
            model_name='tuberiainstalacionbomba',
            name='diametro_tuberia',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tuberiainstalacionbomba',
            name='instalacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tuberias', to='auxiliares.especificacionesinstalacion'),
        ),
        migrations.AlterField(
            model_name='tuberiainstalacionbomba',
            name='longitud_tuberia',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tuberiainstalacionbomba',
            name='material_tuberia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auxiliares.materialtuberia'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tuberiainstalacionbomba',
            name='numero_tubos',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
