# Generated by Django 4.2.4 on 2024-03-21 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliares', '0021_especificacionesinstalacion_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuberiainstalacionbomba',
            name='diametro_tuberia',
            field=models.FloatField(verbose_name='Diámetro de la Tubería'),
        ),
        migrations.AlterField(
            model_name='tuberiainstalacionbomba',
            name='longitud_tuberia',
            field=models.FloatField(verbose_name='Longitud de la Tubería'),
        ),
        migrations.AlterField(
            model_name='tuberiainstalacionbomba',
            name='material_tuberia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auxiliares.materialtuberia', verbose_name='Material de la Tubería'),
        ),
        migrations.AlterField(
            model_name='tuberiainstalacionbomba',
            name='numero_tubos',
            field=models.PositiveIntegerField(verbose_name='Número de Tubos'),
        ),
    ]
