# Generated by Django 4.2.4 on 2024-03-26 11:59

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auxiliares', '0022_alter_tuberiainstalacionbomba_diametro_tuberia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluacionBomba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('fecha', models.DateField(auto_now=True)),
                ('tipo', models.CharField(choices=[('S', 'S'), ('U', 'U')], default='U', max_length=1)),
                ('activo', models.BooleanField(default=True)),
                ('bomba', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auxiliares.bombas')),
            ],
        ),
        migrations.AlterField(
            model_name='condicionesdisenobomba',
            name='npsha',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name='NPSHa'),
        ),
        migrations.AlterField(
            model_name='condicionesdisenobomba',
            name='presion_descarga',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name='Presión de Descarga*'),
        ),
        migrations.AlterField(
            model_name='condicionesdisenobomba',
            name='presion_diferencial',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name='Presión Diferencial'),
        ),
        migrations.AlterField(
            model_name='condicionesdisenobomba',
            name='presion_succion',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name='Presión de Succión*'),
        ),
        migrations.AlterField(
            model_name='condicionfluidobomba',
            name='concentracion_cloro',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name='Concentración de Cloro'),
        ),
        migrations.AlterField(
            model_name='condicionfluidobomba',
            name='concentracion_h2s',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name='Concentración de H₂S'),
        ),
        migrations.AlterField(
            model_name='condicionfluidobomba',
            name='densidad',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1e-06)]),
        ),
        migrations.AlterField(
            model_name='condicionfluidobomba',
            name='presion_vapor',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1e-06)], verbose_name='Presión de Vapor'),
        ),
        migrations.AlterField(
            model_name='condicionfluidobomba',
            name='temperatura_operacion',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name='Temperatura de Operación*'),
        ),
        migrations.AlterField(
            model_name='condicionfluidobomba',
            name='temperatura_presion_vapor',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name='Temperatura a la Presión de Vapor'),
        ),
        migrations.AlterField(
            model_name='condicionfluidobomba',
            name='viscosidad',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1e-06)]),
        ),
        migrations.AlterField(
            model_name='detallesmotorbomba',
            name='factor_de_servicio',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name='Factor de Servicio'),
        ),
        migrations.AlterField(
            model_name='detallesmotorbomba',
            name='frecuencia',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.0001)]),
        ),
        migrations.AlterField(
            model_name='detallesmotorbomba',
            name='potencia_motor',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name='Potencia del Motor'),
        ),
        migrations.AlterField(
            model_name='detallesmotorbomba',
            name='velocidad_motor',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name='Velocidad del Motor'),
        ),
        migrations.AlterField(
            model_name='detallesmotorbomba',
            name='voltaje',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name='Voltaje del Motor'),
        ),
        migrations.AlterField(
            model_name='especificacionesbomba',
            name='cabezal_total',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0001)]),
        ),
        migrations.AlterField(
            model_name='especificacionesbomba',
            name='descarga_id',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name='Diámetro Interno Descarga'),
        ),
        migrations.AlterField(
            model_name='especificacionesbomba',
            name='npshr',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name='NPSHr'),
        ),
        migrations.AlterField(
            model_name='especificacionesbomba',
            name='potencia_maxima',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name='Potencia Máxima'),
        ),
        migrations.AlterField(
            model_name='especificacionesbomba',
            name='succion_id',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name='Diámetro Interno Succión'),
        ),
        migrations.AlterField(
            model_name='especificacionesbomba',
            name='velocidad',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.0001)]),
        ),
        migrations.AlterField(
            model_name='especificacionesinstalacion',
            name='conexiones_t_ramal',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Conexiones T Flujo Ramal'),
        ),
        migrations.AlterField(
            model_name='especificacionesinstalacion',
            name='numero_codos_45_ros',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Núm. Codos Rosc. 45°'),
        ),
        migrations.AlterField(
            model_name='especificacionesinstalacion',
            name='numero_codos_90_rl',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Codos 90° Radio Largo'),
        ),
        migrations.AlterField(
            model_name='especificacionesinstalacion',
            name='numero_codos_90_ros',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Núm. Codos Rosc. 90°'),
        ),
        migrations.AlterField(
            model_name='especificacionesinstalacion',
            name='numero_valvulas_compuerta',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Núm. de Vál. de Compuerta Abierta'),
        ),
        migrations.AlterField(
            model_name='tuberiainstalacionbomba',
            name='diametro_tuberia',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Diámetro'),
        ),
        migrations.AlterField(
            model_name='tuberiainstalacionbomba',
            name='longitud_tuberia',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Longitud'),
        ),
        migrations.AlterField(
            model_name='tuberiainstalacionbomba',
            name='material_tuberia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auxiliares.materialtuberia', verbose_name='Material'),
        ),
        migrations.AlterField(
            model_name='tuberiainstalacionbomba',
            name='numero_tubos',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='# Tubos'),
        ),
        migrations.CreateModel(
            name='SalidaSeccionesEvaluacionBombaGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lado', models.CharField(choices=[('S', 'Succión'), ('D', 'Descarga')], max_length=1)),
                ('numero_reynolds', models.FloatField()),
                ('factor_friccion', models.FloatField()),
                ('factor_friccion_turbulento', models.FloatField()),
                ('tipo_flujo', models.CharField(choices=[('T', 'Turbulento'), ('L', 'Laminar'), ('R', 'Transitorio')], max_length=1)),
                ('perdida_carga_tuberia', models.FloatField()),
                ('perdida_carga_accesorios', models.FloatField(null=True)),
                ('perdida_carga_total', models.FloatField()),
                ('velocidad', models.FloatField()),
                ('area_interna_tuberias', models.FloatField()),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auxiliares.evaluacionbomba')),
            ],
        ),
        migrations.CreateModel(
            name='SalidaEvaluacionBombaGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cabezal_total', models.FloatField()),
                ('potencia', models.FloatField()),
                ('eficiencia', models.FloatField()),
                ('velocidad', models.FloatField()),
                ('npsha', models.FloatField()),
                ('cavita', models.BooleanField(blank=True, null=True)),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auxiliares.evaluacionbomba')),
            ],
        ),
        migrations.AddField(
            model_name='evaluacionbomba',
            name='instalacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auxiliares.especificacionesinstalacion'),
        ),
        migrations.AddField(
            model_name='evaluacionbomba',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='EntradaEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presion', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0001), django.core.validators.MaxValueValidator(9999999.99999)])),
                ('altura', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0001), django.core.validators.MaxValueValidator(9999999.99999)])),
                ('diametro_bomba', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0001), django.core.validators.MaxValueValidator(9999999.99999)])),
                ('flujo', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0001), django.core.validators.MaxValueValidator(9999999.99999)])),
                ('temperatura_operacion', models.FloatField(validators=[django.core.validators.MinValueValidator(-273.15), django.core.validators.MaxValueValidator(9999.99)])),
                ('potencia', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0001), django.core.validators.MaxValueValidator(9999999.99999)])),
                ('npshr', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0001), django.core.validators.MaxValueValidator(9999999.99999)])),
                ('densidad', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0001), django.core.validators.MaxValueValidator(9999999.99999)])),
                ('viscosidad', models.FloatField(verbose_name=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0001), django.core.validators.MaxValueValidator(9999999.99999)]))),
                ('presion_vapor', models.FloatField(verbose_name=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0001), django.core.validators.MaxValueValidator(9999999.99999)]))),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auxiliares.evaluacionbomba')),
            ],
        ),
    ]
