# Generated by Django 4.2.4 on 2024-03-26 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliares', '0023_evaluacionbomba_alter_condicionesdisenobomba_npsha_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='especificacionesinstalacion',
            name='conexiones_t_directo',
        ),
        migrations.RemoveField(
            model_name='especificacionesinstalacion',
            name='conexiones_t_ramal',
        ),
        migrations.RemoveField(
            model_name='especificacionesinstalacion',
            name='numero_codos_180',
        ),
        migrations.RemoveField(
            model_name='especificacionesinstalacion',
            name='numero_codos_45',
        ),
        migrations.RemoveField(
            model_name='especificacionesinstalacion',
            name='numero_codos_45_ros',
        ),
        migrations.RemoveField(
            model_name='especificacionesinstalacion',
            name='numero_codos_90',
        ),
        migrations.RemoveField(
            model_name='especificacionesinstalacion',
            name='numero_codos_90_rl',
        ),
        migrations.RemoveField(
            model_name='especificacionesinstalacion',
            name='numero_codos_90_ros',
        ),
        migrations.RemoveField(
            model_name='especificacionesinstalacion',
            name='numero_valvula_angulo',
        ),
        migrations.RemoveField(
            model_name='especificacionesinstalacion',
            name='numero_valvula_bisagra',
        ),
        migrations.RemoveField(
            model_name='especificacionesinstalacion',
            name='numero_valvula_bola',
        ),
        migrations.RemoveField(
            model_name='especificacionesinstalacion',
            name='numero_valvula_giratoria',
        ),
        migrations.RemoveField(
            model_name='especificacionesinstalacion',
            name='numero_valvula_globo',
        ),
        migrations.RemoveField(
            model_name='especificacionesinstalacion',
            name='numero_valvula_vastago',
        ),
        migrations.RemoveField(
            model_name='especificacionesinstalacion',
            name='numero_valvulas_compuerta',
        ),
        migrations.RemoveField(
            model_name='especificacionesinstalacion',
            name='numero_valvulas_compuerta_abierta_1_2',
        ),
        migrations.RemoveField(
            model_name='especificacionesinstalacion',
            name='numero_valvulas_compuerta_abierta_1_4',
        ),
        migrations.RemoveField(
            model_name='especificacionesinstalacion',
            name='numero_valvulas_compuerta_abierta_3_4',
        ),
        migrations.RemoveField(
            model_name='especificacionesinstalacion',
            name='numero_valvulas_mariposa_10_14',
        ),
        migrations.RemoveField(
            model_name='especificacionesinstalacion',
            name='numero_valvulas_mariposa_16_24',
        ),
        migrations.RemoveField(
            model_name='especificacionesinstalacion',
            name='numero_valvulas_mariposa_2_8',
        ),
        migrations.AddField(
            model_name='tuberiainstalacionbomba',
            name='conexiones_t_directo',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Conexiones T Flujo Directo'),
        ),
        migrations.AddField(
            model_name='tuberiainstalacionbomba',
            name='conexiones_t_ramal',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Conexiones T Flujo Ramal'),
        ),
        migrations.AddField(
            model_name='tuberiainstalacionbomba',
            name='numero_codos_180',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Núm. de Codos a 180°'),
        ),
        migrations.AddField(
            model_name='tuberiainstalacionbomba',
            name='numero_codos_45',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Núm. Codos a 45'),
        ),
        migrations.AddField(
            model_name='tuberiainstalacionbomba',
            name='numero_codos_45_ros',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Núm. Codos Rosc. 45°'),
        ),
        migrations.AddField(
            model_name='tuberiainstalacionbomba',
            name='numero_codos_90',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Núm. Codos a 90°'),
        ),
        migrations.AddField(
            model_name='tuberiainstalacionbomba',
            name='numero_codos_90_rl',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Codos 90° Radio Largo'),
        ),
        migrations.AddField(
            model_name='tuberiainstalacionbomba',
            name='numero_codos_90_ros',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Núm. Codos Rosc. 90°'),
        ),
        migrations.AddField(
            model_name='tuberiainstalacionbomba',
            name='numero_valvula_angulo',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Núm. de Vál. Ángulo'),
        ),
        migrations.AddField(
            model_name='tuberiainstalacionbomba',
            name='numero_valvula_bisagra',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Núm. de Vál. Bisagra'),
        ),
        migrations.AddField(
            model_name='tuberiainstalacionbomba',
            name='numero_valvula_bola',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Núm. de Vál. Bola'),
        ),
        migrations.AddField(
            model_name='tuberiainstalacionbomba',
            name='numero_valvula_giratoria',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Núm. de Vál. Giratorias'),
        ),
        migrations.AddField(
            model_name='tuberiainstalacionbomba',
            name='numero_valvula_globo',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Núm. de Vál. Globo'),
        ),
        migrations.AddField(
            model_name='tuberiainstalacionbomba',
            name='numero_valvula_vastago',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Núm. de Vál. Vástago'),
        ),
        migrations.AddField(
            model_name='tuberiainstalacionbomba',
            name='numero_valvulas_compuerta',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Núm. de Vál. de Compuerta Abierta'),
        ),
        migrations.AddField(
            model_name='tuberiainstalacionbomba',
            name='numero_valvulas_compuerta_abierta_1_2',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Núm. de Vál. Compuerta a 1/2'),
        ),
        migrations.AddField(
            model_name='tuberiainstalacionbomba',
            name='numero_valvulas_compuerta_abierta_1_4',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Núm. de Vál. Compuerta a 1/4'),
        ),
        migrations.AddField(
            model_name='tuberiainstalacionbomba',
            name='numero_valvulas_compuerta_abierta_3_4',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Núm. de Vál. Compuerta a 3/4'),
        ),
        migrations.AddField(
            model_name='tuberiainstalacionbomba',
            name='numero_valvulas_mariposa_10_14',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Núm. de Vál. Mariposa 10"-14"'),
        ),
        migrations.AddField(
            model_name='tuberiainstalacionbomba',
            name='numero_valvulas_mariposa_16_24',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Núm. de Vál. Mariposa 16"-24"'),
        ),
        migrations.AddField(
            model_name='tuberiainstalacionbomba',
            name='numero_valvulas_mariposa_2_8',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Núm. de Vál. Mariposa 2"-8"'),
        ),
    ]
