# Generated by Django 4.2.4 on 2024-03-26 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliares', '0024_remove_especificacionesinstalacion_conexiones_t_directo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tuberiainstalacionbomba',
            name='numero_tubos',
        ),
    ]
