# Generated by Django 4.2.4 on 2024-03-27 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliares', '0025_remove_tuberiainstalacionbomba_numero_tubos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materialtuberia',
            options={'ordering': ('nombre',)},
        ),
        migrations.RenameField(
            model_name='evaluacionbomba',
            old_name='bomba',
            new_name='equipo',
        ),
    ]
