# Generated by Django 4.2.4 on 2024-03-27 11:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intercambiadores', '0068_propiedadesdobletubo_altura_aletas_and_more'),
        ('auxiliares', '0026_alter_materialtuberia_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntradaEvaluacionBomba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presion', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0001), django.core.validators.MaxValueValidator(9999999.99999)])),
                ('altura', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0001), django.core.validators.MaxValueValidator(9999999.99999)])),
                ('diametro_bomba', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0001), django.core.validators.MaxValueValidator(9999999.99999)])),
                ('flujo', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0001), django.core.validators.MaxValueValidator(9999999.99999)])),
                ('temperatura_operacion', models.FloatField(validators=[django.core.validators.MinValueValidator(-273.15), django.core.validators.MaxValueValidator(9999.99)])),
                ('potencia', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0001), django.core.validators.MaxValueValidator(9999999.99999)])),
                ('npshr', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0001), django.core.validators.MaxValueValidator(9999999.99999)])),
                ('densidad', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0001), django.core.validators.MaxValueValidator(9999999.99999)])),
                ('viscosidad', models.FloatField(verbose_name=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0001), django.core.validators.MaxValueValidator(9999999.99999)]))),
                ('presion_vapor', models.FloatField(verbose_name=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0001), django.core.validators.MaxValueValidator(9999999.99999)]))),
                ('altura_unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='altura_unidad_evaluacionbomba', to='intercambiadores.unidades')),
                ('densidad_unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='densidad_unidad_evaluacionbomba', to='intercambiadores.unidades')),
                ('diametro_unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diametro_unidad_evaluacionbomba', to='intercambiadores.unidades')),
            ],
        ),
        migrations.RenameModel(
            old_name='SalidaSeccionesEvaluacionBombaGeneral',
            new_name='SalidaSeccionesEvaluacionBomba',
        ),
        migrations.RemoveField(
            model_name='evaluacionbomba',
            name='instalacion',
        ),
        migrations.AddField(
            model_name='evaluacionbomba',
            name='instalacion_descarga',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='instalacion_descarga_evaluacionbomba', to='auxiliares.especificacionesinstalacion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evaluacionbomba',
            name='instalacion_succion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='instalacion_succion_evaluacionbomba', to='auxiliares.especificacionesinstalacion'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='EntradaEvaluacion',
        ),
        migrations.AddField(
            model_name='entradaevaluacionbomba',
            name='evaluacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entrada_evaluacion_evaluacionbomba', to='auxiliares.evaluacionbomba'),
        ),
        migrations.AddField(
            model_name='entradaevaluacionbomba',
            name='flujo_unidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flujo_unidad_evaluacionbomba', to='intercambiadores.unidades'),
        ),
        migrations.AddField(
            model_name='entradaevaluacionbomba',
            name='npshr_unidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='npshr_unidad_evaluacionbomba', to='intercambiadores.unidades'),
        ),
        migrations.AddField(
            model_name='entradaevaluacionbomba',
            name='potencia_unidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='potencia_unidad_evaluacionbomba', to='intercambiadores.unidades'),
        ),
        migrations.AddField(
            model_name='entradaevaluacionbomba',
            name='presion_unidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='presion_unidad_evaluacionbomba', to='intercambiadores.unidades'),
        ),
        migrations.AddField(
            model_name='entradaevaluacionbomba',
            name='presion_vapor_unidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='presion_vapor_unidad_evaluacionbomba', to='intercambiadores.unidades'),
        ),
        migrations.AddField(
            model_name='entradaevaluacionbomba',
            name='temperatura_unidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='temperatura_unidad_evaluacionbomba', to='intercambiadores.unidades'),
        ),
        migrations.AddField(
            model_name='entradaevaluacionbomba',
            name='viscosidad_unidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='viscosidad_unidad_evaluacionbomba', to='intercambiadores.unidades'),
        ),
    ]
