# Generated by Django 4.2.4 on 2024-03-27 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliares', '0027_entradaevaluacionbomba_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salidaevaluacionbombageneral',
            name='evaluacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salida_general_evaluacionbomba', to='auxiliares.evaluacionbomba'),
        ),
        migrations.AlterField(
            model_name='salidaseccionesevaluacionbomba',
            name='evaluacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salida_secciones_evaluacionbomba', to='auxiliares.evaluacionbomba'),
        ),
    ]
