# Generated by Django 4.2.4 on 2024-03-27 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliares', '0028_alter_salidaevaluacionbombageneral_evaluacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluacionbomba',
            name='fecha',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
