# Generated by Django 4.2.4 on 2024-04-03 14:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intercambiadores', '0068_propiedadesdobletubo_altura_aletas_and_more'),
        ('auxiliares', '0029_alter_evaluacionbomba_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entradaevaluacionbomba',
            name='altura',
        ),
        migrations.RemoveField(
            model_name='entradaevaluacionbomba',
            name='diametro_bomba',
        ),
        migrations.RemoveField(
            model_name='entradaevaluacionbomba',
            name='presion',
        ),
        migrations.AddField(
            model_name='entradaevaluacionbomba',
            name='altura_descarga',
            field=models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(0.0001), django.core.validators.MaxValueValidator(9999999.99999)], verbose_name='Altura'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entradaevaluacionbomba',
            name='altura_succion',
            field=models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(0.0001), django.core.validators.MaxValueValidator(9999999.99999)], verbose_name='Altura'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entradaevaluacionbomba',
            name='calculo_propiedades',
            field=models.CharField(choices=[('M', 'Manual'), ('A', 'Automático'), ('F', 'Ficha')], default='M', max_length=1, verbose_name='Cálculo de Propiedades'),
        ),
        migrations.AddField(
            model_name='entradaevaluacionbomba',
            name='diametro_descarga',
            field=models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(0.0001), django.core.validators.MaxValueValidator(9999999.99999)], verbose_name='Diámetro Interno'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entradaevaluacionbomba',
            name='diametro_succion',
            field=models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(0.0001), django.core.validators.MaxValueValidator(9999999.99999)], verbose_name='Diámetro Interno'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entradaevaluacionbomba',
            name='presion_descarga',
            field=models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(0.0001), django.core.validators.MaxValueValidator(9999999.99999)], verbose_name='Presión'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entradaevaluacionbomba',
            name='presion_succion',
            field=models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(0.0001), django.core.validators.MaxValueValidator(9999999.99999)], verbose_name='Presión'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entradaevaluacionbomba',
            name='velocidad',
            field=models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(0.0001), django.core.validators.MaxValueValidator(9999999.99999)], verbose_name='Velocidad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entradaevaluacionbomba',
            name='velocidad_unidad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='velocidad_unidad_evaluacionbomba', to='intercambiadores.unidades'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='condicionfluidobomba',
            name='corrosividad',
            field=models.CharField(choices=[('C', 'Corrosivo'), ('E', 'Erosivo'), ('N', 'No Erosivo ni Corrosivo'), ('A', 'Ambos'), ('D', 'Desconocido')], max_length=1, verbose_name='Corrosivo/Erosivo*'),
        ),
        migrations.AlterField(
            model_name='entradaevaluacionbomba',
            name='densidad',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0001), django.core.validators.MaxValueValidator(9999999.99999)], verbose_name='Densidad'),
        ),
        migrations.AlterField(
            model_name='entradaevaluacionbomba',
            name='densidad_unidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='densidad_unidad_evaluacionbomba', to='intercambiadores.unidades'),
        ),
        migrations.AlterField(
            model_name='entradaevaluacionbomba',
            name='npshr',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0001), django.core.validators.MaxValueValidator(9999999.99999)], verbose_name='NPSHr'),
        ),
    ]
