# Generated by Django 4.2.4 on 2024-04-05 11:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliares', '0030_remove_entradaevaluacionbomba_altura_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entradaevaluacionbomba',
            name='diametro_descarga',
        ),
        migrations.RemoveField(
            model_name='entradaevaluacionbomba',
            name='diametro_succion',
        ),
        migrations.RemoveField(
            model_name='entradaevaluacionbomba',
            name='diametro_unidad',
        ),
        migrations.RemoveField(
            model_name='salidaseccionesevaluacionbomba',
            name='area_interna_tuberias',
        ),
        migrations.RemoveField(
            model_name='salidaseccionesevaluacionbomba',
            name='factor_friccion',
        ),
        migrations.RemoveField(
            model_name='salidaseccionesevaluacionbomba',
            name='factor_friccion_turbulento',
        ),
        migrations.RemoveField(
            model_name='salidaseccionesevaluacionbomba',
            name='numero_reynolds',
        ),
        migrations.RemoveField(
            model_name='salidaseccionesevaluacionbomba',
            name='tipo_flujo',
        ),
        migrations.RemoveField(
            model_name='salidaseccionesevaluacionbomba',
            name='velocidad',
        ),
        migrations.AlterField(
            model_name='entradaevaluacionbomba',
            name='npshr',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0001), django.core.validators.MaxValueValidator(9999999.99999)], verbose_name='NPSHr'),
        ),
        migrations.CreateModel(
            name='EntradaTramos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lado', models.CharField(choices=[('S', 'Succión'), ('D', 'Descarga')], max_length=1)),
                ('flujo', models.CharField(choices=[('T', 'Turbulento'), ('L', 'Laminar'), ('R', 'Transitorio')], max_length=1)),
                ('velocidad', models.FloatField()),
                ('tramo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tramos_entrada', to='auxiliares.tuberiainstalacionbomba')),
            ],
        ),
    ]
