# Generated by Django 4.2.4 on 2024-04-05 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliares', '0031_remove_entradaevaluacionbomba_diametro_descarga_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entradatramos',
            name='lado',
        ),
        migrations.AddField(
            model_name='entradatramos',
            name='salida',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='datos_tramos_seccion', to='auxiliares.salidaseccionesevaluacionbomba'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entradaevaluacionbomba',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='entradatramos',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='evaluacionbomba',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='salidaevaluacionbombageneral',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='salidaseccionesevaluacionbomba',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
