# Generated by Django 4.2.4 on 2024-04-08 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intercambiadores', '0068_propiedadesdobletubo_altura_aletas_and_more'),
        ('auxiliares', '0033_alter_evaluacionbomba_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salidaevaluacionbombageneral',
            name='cabezal_total_unidad',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.PROTECT, related_name='cabezal_total_unidad_salida_evaluacion_bomba', to='intercambiadores.unidades'),
        ),
        migrations.AddField(
            model_name='salidaevaluacionbombageneral',
            name='potencia_unidad',
            field=models.ForeignKey(default=40, on_delete=django.db.models.deletion.PROTECT, related_name='potencia_unidad_salida_evaluacion_bomba', to='intercambiadores.unidades'),
        ),
        migrations.AddField(
            model_name='salidaevaluacionbombageneral',
            name='velocidad_unidad',
            field=models.ForeignKey(default=38, on_delete=django.db.models.deletion.PROTECT, related_name='velocidad_unidad_salida_evaluacion_bomba', to='intercambiadores.unidades'),
        ),
    ]
