# Generated by Django 4.2.4 on 2024-04-08 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliares', '0034_salidaevaluacionbombageneral_cabezal_total_unidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacionbomba',
            name='entrada',
            field=models.ForeignKey(default='00c63834e4ba404f825a5febbfb8bc6b', on_delete=django.db.models.deletion.PROTECT, related_name='entrada_evaluacion_evaluacionbomba', to='auxiliares.entradaevaluacionbomba'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evaluacionbomba',
            name='salida',
            field=models.ForeignKey(default='13132a31146f4c81b611f7974311ab0b', on_delete=django.db.models.deletion.PROTECT, to='auxiliares.salidaevaluacionbombageneral'),
            preserve_default=False,
        ),
    ]
