# Generated by Django 4.2.4 on 2024-04-10 14:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intercambiadores', '0068_propiedadesdobletubo_altura_aletas_and_more'),
        ('auxiliares', '0037_remove_salidaevaluacionbombageneral_fluido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradaevaluacionbomba',
            name='nombre_fluido',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='entradaevaluacionbomba',
            name='fluido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fluido_salidaevaluacionbomba', to='intercambiadores.fluido'),
        ),
        migrations.AlterField(
            model_name='entradaevaluacionbomba',
            name='temperatura_operacion',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(-273.15), django.core.validators.MaxValueValidator(9999.99)], verbose_name='Temperatura de Operación'),
        ),
    ]
