# Generated by Django 4.2.4 on 2024-04-11 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliares', '0038_entradaevaluacionbomba_nombre_fluido_and_more'),
    ]

    operations = [
        migrations.RenameModel('EntradaTramos', 'SalidaTramosEvaluacionBomba')
    ]
