# Generated by Django 4.2.4 on 2024-04-22 09:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('intercambiadores', '0068_propiedadesdobletubo_altura_aletas_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auxiliares', '0039_auto_20240411_1116'),
    ]

    operations = [
        migrations.CreateModel(
            name='CondicionesTrabajoVentilador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caudal_volumetrico', models.FloatField()),
                ('presion_entrada', models.FloatField()),
                ('presion_salida', models.FloatField()),
                ('velocidad_funcionamiento', models.FloatField()),
                ('temperatura', models.FloatField()),
                ('densidad', models.FloatField()),
                ('potencia_freno', models.FloatField()),
                ('eficiencia', models.FloatField()),
                ('tipo_condicion', models.CharField(choices=[('P', 'Principal'), ('A', 'Adicional')], max_length=1)),
                ('calculo_densidad', models.CharField(choices=[('M', 'Manual'), ('A', 'Automático')], max_length=1)),
                ('caudal_volumetrico_unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='condicionestrabajoventilador_caudal_volumetrico_unidad', to='intercambiadores.unidades')),
                ('densidad_unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='condicionestrabajoventilador_densidad_unidad', to='intercambiadores.unidades')),
                ('potencia_freno_unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='condicionestrabajoventilador_potencia_freno_unidad', to='intercambiadores.unidades')),
                ('presion_unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='condicionestrabajoventilador_presion_unidad', to='intercambiadores.unidades')),
                ('temperatura_unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='condicionestrabajoventilador_temperatura_unidad', to='intercambiadores.unidades')),
                ('velocidad_funcionamiento_unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='condicionestrabajoventilador_velocidad_funcionamiento_unidad', to='intercambiadores.unidades')),
            ],
            options={
                'db_table': 'ventiladores_condicionestrabajo',
            },
        ),
        migrations.CreateModel(
            name='EntradaEvaluacionVentilador',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('presion_entrada', models.FloatField()),
                ('presion_salida', models.FloatField()),
                ('flujo', models.FloatField()),
                ('temperatura_operacion', models.FloatField()),
                ('potencia_ventilador', models.FloatField()),
                ('densidad_ficha', models.FloatField()),
                ('densidad_evaluacion', models.FloatField()),
                ('densidad_evaluacion_unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entradaevaluacion_densidad_evaluacion_unidad', to='intercambiadores.unidades')),
                ('flujo_unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entradaevaluacion_flujo_unidad', to='intercambiadores.unidades')),
                ('potencia_ventilador_unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entradaevaluacion_potencia_ventilador_unidad', to='intercambiadores.unidades')),
                ('presion_salida_unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entradaevaluacion_presion_salida_unidad', to='intercambiadores.unidades')),
                ('temperatura_operacion_unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entradaevaluacion_temperatura_operacion_unidad', to='intercambiadores.unidades')),
            ],
            options={
                'db_table': 'ventiladores_entradaevaluacion',
            },
        ),
        migrations.CreateModel(
            name='EspecificacionesVentilador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('espesor', models.FloatField(null=True)),
                ('espesor_caja', models.FloatField(null=True)),
                ('sello', models.CharField(max_length=45, null=True)),
                ('lubricante', models.CharField(max_length=45, null=True)),
                ('refrigerante', models.CharField(max_length=45, null=True)),
                ('diametro', models.CharField(max_length=45, null=True)),
                ('acceso_aire', models.CharField(max_length=45, null=True)),
                ('espesor_unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='especificacionesventilador_velocidad_diseno_unidad', to='intercambiadores.unidades')),
            ],
            options={
                'db_table': 'ventiladores_especificacionesventilador',
            },
        ),
        migrations.CreateModel(
            name='SalidaEvaluacionVentilador',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('potencia_calculada', models.FloatField()),
                ('eficiencia', models.FloatField()),
                ('relacion_densidad', models.FloatField()),
            ],
            options={
                'db_table': 'ventiladores_salidaevaluacion',
            },
        ),
        migrations.CreateModel(
            name='TipoVentilador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='evaluacionbomba',
            name='equipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluaciones_bomba', to='auxiliares.bombas'),
        ),
        migrations.AlterField(
            model_name='salidatramosevaluacionbomba',
            name='flujo',
            field=models.CharField(choices=[('T', 'Turbulento'), ('R', 'Transitorio'), ('L', 'Laminar')], max_length=1),
        ),
        migrations.CreateModel(
            name='Ventilador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_al', models.DateTimeField(auto_created=True)),
                ('tag', models.CharField(max_length=20, unique=True)),
                ('descripcion', models.CharField(max_length=100)),
                ('fabricante', models.CharField(max_length=45)),
                ('modelo', models.CharField(max_length=45, null=True)),
                ('editado_al', models.DateTimeField(null=True)),
                ('condiciones_diseno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auxiliares.condicionesdisenobomba')),
                ('condiciones_trabajo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auxiliares.condicionestrabajoventilador')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventilador_creado_por', to=settings.AUTH_USER_MODEL)),
                ('editado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ventilador_editado_por', to=settings.AUTH_USER_MODEL)),
                ('especificaciones', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auxiliares.especificacionesventilador')),
                ('planta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planta_ventilador', to='intercambiadores.planta')),
                ('tipo_ventilador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auxiliares.tipoventilador')),
            ],
            options={
                'db_table': 'ventiladores_ventilador',
            },
        ),
        migrations.CreateModel(
            name='EvaluacionVentilador',
            fields=[
                ('fecha', models.DateTimeField(auto_created=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('visible', models.BooleanField()),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluacionventilador_creado_por', to=settings.AUTH_USER_MODEL)),
                ('entrada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auxiliares.entradaevaluacionventilador')),
                ('salida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auxiliares.salidaevaluacionventilador')),
                ('ventilador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auxiliares.ventilador')),
            ],
            options={
                'db_table': 'ventiladores_evaluacion',
            },
        ),
        migrations.CreateModel(
            name='CondicionesGeneralesVentilador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presion_barometrica', models.FloatField()),
                ('temp_ambiente', models.FloatField()),
                ('velocidad_diseno', models.FloatField()),
                ('temp_diseno', models.FloatField(null=True)),
                ('presion_diseno', models.FloatField(null=True)),
                ('presion_barometrica_unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='condicionesgenerales_presion_barometrica_unidad', to='intercambiadores.unidades')),
                ('temp_ambiente_unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='condicionesgenerales_temp_ambiente_unidad', to='intercambiadores.unidades')),
                ('velocidad_diseno_unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='condicionesgenerales_velocidad_diseno_unidad', to='intercambiadores.unidades')),
            ],
            options={
                'db_table': 'ventiladores_condicionesgenerales',
            },
        ),
    ]
