# Generated by Django 4.2.4 on 2024-04-22 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliares', '0043_condicionestrabajoventilador_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tipoventilador',
            table='ventiladores_tipoventilador',
        ),
    ]
