# Generated by Django 4.2.4 on 2024-04-22 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliares', '0044_alter_tipoventilador_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='especificacionesventilador',
            name='motor',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
