# Generated by Django 4.2.4 on 2024-04-22 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliares', '0045_especificacionesventilador_motor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ventilador',
            old_name='condiciones_diseno',
            new_name='condiciones_generales',
        ),
        migrations.RemoveField(
            model_name='condicionestrabajoventilador',
            name='tipo_condicion',
        ),
        migrations.AlterField(
            model_name='condicionestrabajoventilador',
            name='eficiencia',
            field=models.FloatField(null=True),
        ),
    ]
