# Generated by Django 4.2.4 on 2024-04-22 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliares', '0047_alter_ventilador_condiciones_generales'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventilador',
            name='condiciones_adicionales',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='condicion_trabajo_adicional_ventilador', to='auxiliares.condicionestrabajoventilador'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ventilador',
            name='condiciones_generales',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='auxiliares.condicionesgeneralesventilador'),
        ),
        migrations.AlterField(
            model_name='ventilador',
            name='condiciones_trabajo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='condicion_trabajo_principal_ventilador', to='auxiliares.condicionestrabajoventilador'),
        ),
        migrations.AlterField(
            model_name='ventilador',
            name='creado_al',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='ventilador',
            name='especificaciones',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='auxiliares.especificacionesventilador'),
        ),
    ]
