# Generated by Django 4.2.4 on 2024-04-22 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intercambiadores', '0068_propiedadesdobletubo_altura_aletas_and_more'),
        ('auxiliares', '0048_ventilador_condiciones_adicionales_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='condicionestrabajoventilador',
            old_name='caudal_volumetrico',
            new_name='flujo',
        ),
        migrations.RemoveField(
            model_name='condicionestrabajoventilador',
            name='caudal_volumetrico_unidad',
        ),
        migrations.AddField(
            model_name='condicionestrabajoventilador',
            name='flujo_unidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='condicionestrabajoventilador_caudal_volumetrico_unidad', to='intercambiadores.unidades'),
        ),
        migrations.AddField(
            model_name='condicionestrabajoventilador',
            name='tipo_flujo',
            field=models.CharField(choices=[('M', 'Másico'), ('V', 'Volumétrico')], default='V', max_length=1),
        ),
        migrations.AddField(
            model_name='entradaevaluacionventilador',
            name='tipo_flujo',
            field=models.CharField(choices=[('M', 'Másico'), ('V', 'Volumétrico')], default='V', max_length=1),
        ),
    ]
