# Generated by Django 4.2.4 on 2024-04-23 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intercambiadores', '0068_propiedadesdobletubo_altura_aletas_and_more'),
        ('auxiliares', '0049_rename_caudal_volumetrico_condicionestrabajoventilador_flujo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='condicionestrabajoventilador',
            name='potencia',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='especificacionesventilador',
            name='potencia_motor',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='especificacionesventilador',
            name='potencia_motor_unidad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='especificacionesventilador_potencia_motor_unidad', to='intercambiadores.unidades'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='especificacionesventilador',
            name='velocidad_motor',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='especificacionesventilador',
            name='velocidad_motor_unidad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='especificacionesventilador_velocidad_motor_unidad', to='intercambiadores.unidades'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='condicionesgeneralesventilador',
            name='presion_barometrica',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='condicionesgeneralesventilador',
            name='temp_ambiente',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='condicionesgeneralesventilador',
            name='velocidad_diseno',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='condicionestrabajoventilador',
            name='densidad',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='condicionestrabajoventilador',
            name='potencia_freno',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='condicionestrabajoventilador',
            name='presion_entrada',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='condicionestrabajoventilador',
            name='presion_salida',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='condicionestrabajoventilador',
            name='temperatura',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='condicionestrabajoventilador',
            name='velocidad_funcionamiento',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='ventilador',
            name='descripcion',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ventilador',
            name='fabricante',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
