# Generated by Django 4.2.4 on 2024-04-25 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliares', '0051_alter_ventilador_condiciones_adicionales'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ventilador',
            options={'ordering': ('tag',)},
        ),
        migrations.AlterField(
            model_name='condicionesgeneralesventilador',
            name='presion_barometrica',
            field=models.FloatField(blank=True, null=True, verbose_name='Presión Barométrica'),
        ),
        migrations.AlterField(
            model_name='condicionesgeneralesventilador',
            name='presion_diseno',
            field=models.FloatField(blank=True, null=True, verbose_name='Presión de Diseño'),
        ),
        migrations.AlterField(
            model_name='condicionesgeneralesventilador',
            name='temp_ambiente',
            field=models.FloatField(blank=True, null=True, verbose_name='Temperatura Ambiente'),
        ),
        migrations.AlterField(
            model_name='condicionesgeneralesventilador',
            name='temp_diseno',
            field=models.FloatField(blank=True, null=True, verbose_name='Temperatura de Diseño'),
        ),
        migrations.AlterField(
            model_name='condicionesgeneralesventilador',
            name='velocidad_diseno',
            field=models.FloatField(blank=True, null=True, verbose_name='Velocidad de Diseño'),
        ),
        migrations.AlterField(
            model_name='condicionestrabajoventilador',
            name='calculo_densidad',
            field=models.CharField(choices=[('M', 'Manual'), ('A', 'Automático')], max_length=1, verbose_name='Cálculo de Densidad'),
        ),
        migrations.AlterField(
            model_name='condicionestrabajoventilador',
            name='densidad',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='condicionestrabajoventilador',
            name='flujo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='condicionestrabajoventilador',
            name='potencia',
            field=models.FloatField(blank=True, null=True, verbose_name='Potencia de Ventilador'),
        ),
        migrations.AlterField(
            model_name='condicionestrabajoventilador',
            name='potencia_freno',
            field=models.FloatField(blank=True, null=True, verbose_name='Potencia de Freno'),
        ),
        migrations.AlterField(
            model_name='condicionestrabajoventilador',
            name='presion_entrada',
            field=models.FloatField(blank=True, null=True, verbose_name='Presión de Entrada'),
        ),
        migrations.AlterField(
            model_name='condicionestrabajoventilador',
            name='presion_salida',
            field=models.FloatField(blank=True, null=True, verbose_name='Presión de Salida'),
        ),
        migrations.AlterField(
            model_name='condicionestrabajoventilador',
            name='temperatura',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='condicionestrabajoventilador',
            name='velocidad_funcionamiento',
            field=models.FloatField(blank=True, null=True, verbose_name='Velocidad de Funcionamiento'),
        ),
        migrations.AlterField(
            model_name='especificacionesventilador',
            name='acceso_aire',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Acceso del Aire al Ventilador'),
        ),
        migrations.AlterField(
            model_name='especificacionesventilador',
            name='diametro',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Diámetro del Ventilador'),
        ),
        migrations.AlterField(
            model_name='especificacionesventilador',
            name='espesor',
            field=models.FloatField(blank=True, null=True, verbose_name='Espesor de Carcasa'),
        ),
        migrations.AlterField(
            model_name='especificacionesventilador',
            name='espesor_caja',
            field=models.FloatField(blank=True, null=True, verbose_name='Espesor de Caja de Entrada'),
        ),
        migrations.AlterField(
            model_name='especificacionesventilador',
            name='lubricante',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='especificacionesventilador',
            name='motor',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='especificacionesventilador',
            name='potencia_motor',
            field=models.FloatField(blank=True, null=True, verbose_name='Potencia del Motor'),
        ),
        migrations.AlterField(
            model_name='especificacionesventilador',
            name='refrigerante',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='especificacionesventilador',
            name='sello',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Sello del Eje'),
        ),
        migrations.AlterField(
            model_name='especificacionesventilador',
            name='velocidad_motor',
            field=models.FloatField(blank=True, null=True, verbose_name='Velocidad del Motor'),
        ),
        migrations.AlterField(
            model_name='ventilador',
            name='descripcion',
            field=models.CharField(default='', max_length=100, verbose_name='Descripción'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ventilador',
            name='fabricante',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='ventilador',
            name='modelo',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='ventilador',
            name='tipo_ventilador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auxiliares.tipoventilador', verbose_name='Tipo de Ventilador'),
        ),
    ]
