# Generated by Django 4.2.4 on 2024-04-26 11:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intercambiadores', '0068_propiedadesdobletubo_altura_aletas_and_more'),
        ('auxiliares', '0052_alter_ventilador_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salidaseccionesevaluacionbomba',
            options={'ordering': ('-lado',)},
        ),
        migrations.RenameField(
            model_name='evaluacionventilador',
            old_name='visible',
            new_name='activo',
        ),
        migrations.AddField(
            model_name='salidaevaluacionventilador',
            name='potencia_calculada_unidad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='salidaevaluacionventilador_potencia_calculada_unidad', to='intercambiadores.unidades'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='condicionesgeneralesventilador',
            name='presion_barometrica',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1e-06)], verbose_name='Presión Barométrica'),
        ),
        migrations.AlterField(
            model_name='condicionesgeneralesventilador',
            name='presion_diseno',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Presión de Diseño'),
        ),
        migrations.AlterField(
            model_name='condicionesgeneralesventilador',
            name='temp_ambiente',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1e-06)], verbose_name='Temperatura Ambiente'),
        ),
        migrations.AlterField(
            model_name='condicionesgeneralesventilador',
            name='temp_diseno',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-273.15)], verbose_name='Temperatura de Diseño'),
        ),
        migrations.AlterField(
            model_name='condicionesgeneralesventilador',
            name='velocidad_diseno',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1e-06)], verbose_name='Velocidad de Diseño'),
        ),
        migrations.AlterField(
            model_name='condicionestrabajoventilador',
            name='densidad',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1e-06)]),
        ),
        migrations.AlterField(
            model_name='condicionestrabajoventilador',
            name='flujo',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1e-06)]),
        ),
        migrations.AlterField(
            model_name='condicionestrabajoventilador',
            name='potencia',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1e-06)], verbose_name='Potencia de Ventilador'),
        ),
        migrations.AlterField(
            model_name='condicionestrabajoventilador',
            name='potencia_freno',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1e-06)], verbose_name='Potencia de Freno'),
        ),
        migrations.AlterField(
            model_name='condicionestrabajoventilador',
            name='temperatura',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-273.15)]),
        ),
        migrations.AlterField(
            model_name='condicionestrabajoventilador',
            name='velocidad_funcionamiento',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1e-06)], verbose_name='Velocidad de Funcionamiento'),
        ),
        migrations.AlterField(
            model_name='especificacionesventilador',
            name='espesor',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1e-06)], verbose_name='Espesor de Carcasa'),
        ),
        migrations.AlterField(
            model_name='especificacionesventilador',
            name='espesor_caja',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1e-06)], verbose_name='Espesor de Caja de Entrada'),
        ),
        migrations.AlterField(
            model_name='especificacionesventilador',
            name='potencia_motor',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1e-06)], verbose_name='Potencia del Motor'),
        ),
        migrations.AlterField(
            model_name='especificacionesventilador',
            name='velocidad_motor',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1e-06)], verbose_name='Velocidad del Motor'),
        ),
        migrations.AlterField(
            model_name='tuberiainstalacionbomba',
            name='numero_codos_45',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Núm. Codos a 45°'),
        ),
    ]
