# Generated by Django 4.2.4 on 2024-04-26 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliares', '0053_alter_salidaseccionesevaluacionbomba_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evaluacionventilador',
            old_name='ventilador',
            new_name='equipo',
        ),
    ]
