# Generated by Django 4.2.4 on 2024-04-26 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliares', '0054_rename_ventilador_evaluacionventilador_equipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacionventilador',
            name='nombre',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
