# Generated by Django 4.2.4 on 2024-04-26 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intercambiadores', '0068_propiedadesdobletubo_altura_aletas_and_more'),
        ('auxiliares', '0055_evaluacionventilador_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradaevaluacionventilador',
            name='densidad_ficha_unidad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='entradaevaluacion_densidad_ficha_unidad', to='intercambiadores.unidades'),
            preserve_default=False,
        ),
    ]
