# Generated by Django 4.2.4 on 2024-04-29 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intercambiadores', '0068_propiedadesdobletubo_altura_aletas_and_more'),
        ('auxiliares', '0056_entradaevaluacionventilador_densidad_ficha_unidad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evaluacionventilador',
            options={'ordering': ('-fecha',)},
        ),
        migrations.AlterField(
            model_name='entradaevaluacionventilador',
            name='densidad_evaluacion',
            field=models.FloatField(verbose_name='Densidad Calculada'),
        ),
        migrations.AlterField(
            model_name='entradaevaluacionventilador',
            name='densidad_ficha_unidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entradaevaluacion_densidad_ficha_unidad', to='intercambiadores.unidades'),
        ),
        migrations.AlterField(
            model_name='entradaevaluacionventilador',
            name='potencia_ventilador',
            field=models.FloatField(verbose_name='Potencia del Ventilador'),
        ),
        migrations.AlterField(
            model_name='entradaevaluacionventilador',
            name='presion_entrada',
            field=models.FloatField(verbose_name='Presión Entrada'),
        ),
        migrations.AlterField(
            model_name='entradaevaluacionventilador',
            name='presion_salida',
            field=models.FloatField(verbose_name='Presión Salida'),
        ),
        migrations.AlterField(
            model_name='entradaevaluacionventilador',
            name='temperatura_operacion',
            field=models.FloatField(verbose_name='Temperatura de Operación'),
        ),
        migrations.AlterField(
            model_name='evaluacionventilador',
            name='fecha',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
