# Generated by Django 4.2.4 on 2024-04-29 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intercambiadores', '0068_propiedadesdobletubo_altura_aletas_and_more'),
        ('auxiliares', '0057_alter_evaluacionventilador_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradaevaluacionventilador',
            name='densidad_evaluacion',
            field=models.FloatField(blank=True, verbose_name='Densidad Calculada'),
        ),
        migrations.AlterField(
            model_name='entradaevaluacionventilador',
            name='densidad_ficha',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='entradaevaluacionventilador',
            name='densidad_ficha_unidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entradaevaluacion_densidad_ficha_unidad', to='intercambiadores.unidades'),
        ),
    ]
