# Generated by Django 4.2.4 on 2024-05-06 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliares', '0058_alter_entradaevaluacionventilador_densidad_evaluacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluacionventilador',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='ventilador',
            name='creado_al',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
