# Generated by Django 4.2.4 on 2024-05-14 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliares', '0059_alter_evaluacionventilador_activo_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bombas',
            table='bombas_bomba',
        ),
        migrations.AlterModelTable(
            name='condicionesdisenobomba',
            table='bombas_condiciondiseno',
        ),
        migrations.AlterModelTable(
            name='condicionfluidobomba',
            table='bombas_condicionfluido',
        ),
        migrations.AlterModelTable(
            name='detallesconstruccionbomba',
            table='bombas_detallesconstruccion',
        ),
        migrations.AlterModelTable(
            name='detallesmotorbomba',
            table='bombas_detallesmotor',
        ),
        migrations.AlterModelTable(
            name='entradaevaluacionbomba',
            table='bombas_evaluacion_entrada',
        ),
        migrations.AlterModelTable(
            name='especificacionesbomba',
            table='bombas_especificacionesbomba',
        ),
        migrations.AlterModelTable(
            name='especificacionesinstalacion',
            table='bombas_especificacionesinstalacion',
        ),
        migrations.AlterModelTable(
            name='evaluacionbomba',
            table='bombas_evaluacion',
        ),
        migrations.AlterModelTable(
            name='materialtuberia',
            table='bombas_materialtuberia',
        ),
        migrations.AlterModelTable(
            name='salidaevaluacionbombageneral',
            table='bombas_evaluacion_salida',
        ),
        migrations.AlterModelTable(
            name='salidaseccionesevaluacionbomba',
            table='bombas_evaluacion_salidasecciones',
        ),
        migrations.AlterModelTable(
            name='salidatramosevaluacionbomba',
            table='bombas_evaluacion_salidatramos',
        ),
        migrations.AlterModelTable(
            name='tipobomba',
            table='bombas_tipo',
        ),
        migrations.AlterModelTable(
            name='tipobombaconstruccion',
            table='bombas_tipobombaconstruccion',
        ),
        migrations.AlterModelTable(
            name='tipocarcasabomba',
            table='bombas_tipocarcasa',
        ),
        migrations.AlterModelTable(
            name='tuberiainstalacionbomba',
            table='bombas_tuberiainstalacion',
        ),
    ]
