# Generated by Django 4.2.4 on 2024-05-15 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliares', '0060_alter_bombas_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='entradaevaluacionventilador',
            table='ventiladores_evaluacion_entrada',
        ),
        migrations.AlterModelTable(
            name='salidaevaluacionventilador',
            table='ventiladores_evaluacion_salida',
        ),
    ]
