# Generated by Django 4.2.4 on 2024-05-27 09:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliares', '0061_alter_entradaevaluacionventilador_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bombas',
            name='grafica',
            field=models.ImageField(blank=True, null=True, upload_to='media/auxiliares/bombas/', verbose_name='Gráfica del Equipo'),
        ),
        migrations.AlterField(
            model_name='condicionesgeneralesventilador',
            name='presion_barometrica',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name='Presión Barométrica'),
        ),
        migrations.AlterField(
            model_name='condicionesgeneralesventilador',
            name='presion_diseno',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name='Presión de Diseño'),
        ),
        migrations.AlterField(
            model_name='condicionesgeneralesventilador',
            name='temp_ambiente',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-273.15)], verbose_name='Temperatura Ambiente'),
        ),
        migrations.AlterField(
            model_name='condicionesgeneralesventilador',
            name='velocidad_diseno',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name='Velocidad de Diseño'),
        ),
        migrations.AlterField(
            model_name='condicionestrabajoventilador',
            name='presion_entrada',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1e-06)], verbose_name='Presión de Entrada'),
        ),
        migrations.AlterField(
            model_name='condicionestrabajoventilador',
            name='presion_salida',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1e-06)], verbose_name='Presión de Salida'),
        ),
        migrations.AlterField(
            model_name='entradaevaluacionventilador',
            name='densidad_evaluacion',
            field=models.FloatField(blank=True, validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name='Densidad Calculada'),
        ),
        migrations.AlterField(
            model_name='entradaevaluacionventilador',
            name='flujo',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0001)]),
        ),
        migrations.AlterField(
            model_name='entradaevaluacionventilador',
            name='potencia_ventilador',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name='Potencia del Ventilador'),
        ),
        migrations.AlterField(
            model_name='entradaevaluacionventilador',
            name='presion_entrada',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name='Presión Entrada'),
        ),
        migrations.AlterField(
            model_name='entradaevaluacionventilador',
            name='presion_salida',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name='Presión Salida'),
        ),
        migrations.AlterField(
            model_name='entradaevaluacionventilador',
            name='temperatura_operacion',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(-273.15)], verbose_name='Temperatura de Operación'),
        ),
        migrations.AlterField(
            model_name='especificacionesventilador',
            name='espesor',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name='Espesor de Carcasa'),
        ),
        migrations.AlterField(
            model_name='especificacionesventilador',
            name='espesor_caja',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name='Espesor de Caja de Entrada'),
        ),
        migrations.AlterField(
            model_name='especificacionesventilador',
            name='potencia_motor',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name='Potencia del Motor'),
        ),
        migrations.AlterField(
            model_name='especificacionesventilador',
            name='velocidad_motor',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name='Velocidad del Motor'),
        ),
    ]
