# Generated by Django 4.2.4 on 2024-05-28 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliares', '0063_alter_condicionestrabajoventilador_presion_entrada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bombas',
            name='grafica',
            field=models.ImageField(blank=True, null=True, upload_to='auxiliares/bombas/', verbose_name='Gráfica del Equipo'),
        ),
    ]
