# Generated by Django 4.2.4 on 2024-05-28 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliares', '0064_alter_bombas_grafica'),
    ]

    operations = [
        migrations.AddField(
            model_name='especificacionesventilador',
            name='factor_servicio',
            field=models.FloatField(blank=True, null=True, verbose_name='Factor de Servicio'),
        ),
    ]
