# Generated by Django 4.2.4 on 2024-08-02 07:35

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intercambiadores', '0072_alter_clasesunidades_table'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auxiliares', '0065_especificacionesventilador_factor_servicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrecalentadorAgua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=45, unique=True)),
                ('descripcion', models.CharField(max_length=80)),
                ('fabricante', models.CharField(max_length=45)),
                ('creado_al', models.DateTimeField(auto_now_add=True)),
                ('editado_al', models.DateTimeField(null=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='precalentador_agua_creado_por', to=settings.AUTH_USER_MODEL)),
                ('editado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='precalentador_agua_editado_por', to=settings.AUTH_USER_MODEL)),
                ('planta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='intercambiadores.planta')),
            ],
            options={
                'db_table': 'precalentador_agua',
                'ordering': ('tag',),
            },
        ),
        migrations.CreateModel(
            name='SeccionesPrecalentadorAgua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presion_entrada', models.FloatField()),
                ('caida_presion', models.FloatField(null=True)),
                ('entalpia_entrada', models.FloatField()),
                ('entalpia_salida', models.FloatField(null=True)),
                ('flujo_masico_entrada', models.FloatField()),
                ('flujo_masico_salida', models.FloatField()),
                ('temp_entrada', models.FloatField()),
                ('temp_salida', models.FloatField(null=True)),
                ('velocidad_promedio', models.FloatField(null=True)),
                ('tipo', models.CharField(choices=[('A', 'Agua'), ('V', 'Vapor'), ('D', 'Drenaje')], max_length=1)),
                ('entalpia_unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entalpia_unidad_seccion_precalentador_agua', to='intercambiadores.unidades')),
                ('flujo_unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flujo_unidad_seccion_precalentador_agua', to='intercambiadores.unidades')),
                ('precalentador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='secciones_precalentador', to='auxiliares.precalentadoragua')),
                ('presion_unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='presion_unidad_seccion_precalentador_agua', to='intercambiadores.unidades')),
                ('temp_unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='temperatura_unidad_seccion_precalentador_agua', to='intercambiadores.unidades')),
                ('velocidad_unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='velocidad_unidad_seccion_precalentador_agua', to='intercambiadores.unidades')),
            ],
            options={
                'db_table': 'precalentador_agua_secciones',
                'ordering': ('tipo',),
            },
        ),
        migrations.CreateModel(
            name='EspecificacionesPrecalentadorAgua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calor', models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.0001)])),
                ('area', models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.0001)])),
                ('coeficiente_transferencia', models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.0001)])),
                ('mtd', models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.0001)])),
                ('caida_presion', models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.0001)])),
                ('tipo', models.CharField(choices=[('D', 'Drenaje'), ('R', 'Reducción de Desobrecalentamiento'), ('C', 'Condensado')], max_length=1)),
                ('area_unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='area_unidad_especificaciones_precalentador_agua', to='intercambiadores.unidades')),
                ('caida_presion_unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='caida_presion_unidad_especificaciones_precalentador_agua', to='intercambiadores.unidades')),
                ('calor_unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calor_unidad_especificaciones_precalentador_agua', to='intercambiadores.unidades')),
                ('coeficiente_unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coeficiente_unidad_especificaciones_precalentador_agua', to='intercambiadores.unidades')),
                ('mtd_unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mtd_unidad_especificaciones_precalentador_agua', to='intercambiadores.unidades')),
                ('precalentador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='especificaciones_precalentador', to='auxiliares.precalentadoragua')),
            ],
            options={
                'db_table': 'precalentador_agua_especificaciones',
                'ordering': ('tipo',),
            },
        ),
    ]
