# Generated by Django 4.2.4 on 2024-08-02 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intercambiadores', '0072_alter_clasesunidades_table'),
        ('auxiliares', '0066_precalentadoragua_seccionesprecalentadoragua_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especificacionesprecalentadoragua',
            name='caida_presion_unidad',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.PROTECT, related_name='caida_presion_unidad_especificaciones_precalentador_agua', to='intercambiadores.unidades'),
        ),
        migrations.AlterField(
            model_name='especificacionesprecalentadoragua',
            name='calor_unidad',
            field=models.ForeignKey(default=88, on_delete=django.db.models.deletion.PROTECT, related_name='calor_unidad_especificaciones_precalentador_agua', to='intercambiadores.unidades'),
        ),
        migrations.AlterField(
            model_name='especificacionesprecalentadoragua',
            name='coeficiente_unidad',
            field=models.ForeignKey(default=27, on_delete=django.db.models.deletion.PROTECT, related_name='coeficiente_unidad_especificaciones_precalentador_agua', to='intercambiadores.unidades'),
        ),
        migrations.AlterField(
            model_name='especificacionesprecalentadoragua',
            name='mtd_unidad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='mtd_unidad_especificaciones_precalentador_agua', to='intercambiadores.unidades'),
        ),
        migrations.AlterField(
            model_name='seccionesprecalentadoragua',
            name='entalpia_unidad',
            field=models.ForeignKey(default=88, on_delete=django.db.models.deletion.PROTECT, related_name='entalpia_unidad_seccion_precalentador_agua', to='intercambiadores.unidades'),
        ),
        migrations.AlterField(
            model_name='seccionesprecalentadoragua',
            name='flujo_masico_entrada',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='seccionesprecalentadoragua',
            name='flujo_masico_salida',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='seccionesprecalentadoragua',
            name='flujo_unidad',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.PROTECT, related_name='flujo_unidad_seccion_precalentador_agua', to='intercambiadores.unidades'),
        ),
        migrations.AlterField(
            model_name='seccionesprecalentadoragua',
            name='precalentador',
            field=models.ForeignKey(default=89, on_delete=django.db.models.deletion.PROTECT, related_name='secciones_precalentador', to='auxiliares.precalentadoragua'),
        ),
        migrations.AlterField(
            model_name='seccionesprecalentadoragua',
            name='presion_unidad',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.PROTECT, related_name='presion_unidad_seccion_precalentador_agua', to='intercambiadores.unidades'),
        ),
        migrations.AlterField(
            model_name='seccionesprecalentadoragua',
            name='temp_unidad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='temperatura_unidad_seccion_precalentador_agua', to='intercambiadores.unidades'),
        ),
        migrations.AlterField(
            model_name='seccionesprecalentadoragua',
            name='velocidad_unidad',
            field=models.ForeignKey(default=89, on_delete=django.db.models.deletion.PROTECT, related_name='velocidad_unidad_seccion_precalentador_agua', to='intercambiadores.unidades'),
        ),
    ]
