# Generated by Django 4.2.4 on 2024-08-02 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliares', '0067_alter_especificacionesprecalentadoragua_caida_presion_unidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seccionesprecalentadoragua',
            name='temp_entrada',
            field=models.FloatField(null=True),
        ),
    ]
