# Generated by Django 4.2.4 on 2024-08-02 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intercambiadores', '0072_alter_clasesunidades_table'),
        ('auxiliares', '0068_alter_seccionesprecalentadoragua_temp_entrada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especificacionesprecalentadoragua',
            name='area_unidad',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, related_name='area_unidad_especificaciones_precalentador_agua', to='intercambiadores.unidades'),
        ),
        migrations.AlterField(
            model_name='seccionesprecalentadoragua',
            name='entalpia_entrada',
            field=models.FloatField(null=True),
        ),
    ]
