# Generated by Django 4.2.4 on 2024-08-06 12:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intercambiadores', '0072_alter_clasesunidades_table'),
        ('auxiliares', '0069_alter_especificacionesprecalentadoragua_area_unidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventilador',
            name='copia',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='especificacionesprecalentadoragua',
            name='area',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name='Área'),
        ),
        migrations.AlterField(
            model_name='especificacionesprecalentadoragua',
            name='caida_presion',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name='Caída de Presión'),
        ),
        migrations.AlterField(
            model_name='especificacionesprecalentadoragua',
            name='calor',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0001)]),
        ),
        migrations.AlterField(
            model_name='especificacionesprecalentadoragua',
            name='calor_unidad',
            field=models.ForeignKey(default=91, on_delete=django.db.models.deletion.PROTECT, related_name='calor_unidad_especificaciones_precalentador_agua', to='intercambiadores.unidades'),
        ),
        migrations.AlterField(
            model_name='especificacionesprecalentadoragua',
            name='coeficiente_transferencia',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name='Coeficiente Global de Transferencia'),
        ),
        migrations.AlterField(
            model_name='especificacionesprecalentadoragua',
            name='mtd',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name='Delta T Medio de Referencia'),
        ),
        migrations.AlterField(
            model_name='precalentadoragua',
            name='descripcion',
            field=models.CharField(max_length=80, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='precalentadoragua',
            name='fabricante',
            field=models.CharField(max_length=45, verbose_name='Fabricante'),
        ),
        migrations.AlterField(
            model_name='precalentadoragua',
            name='tag',
            field=models.CharField(max_length=45, unique=True, verbose_name='Tag'),
        ),
        migrations.AlterField(
            model_name='seccionesprecalentadoragua',
            name='caida_presion',
            field=models.FloatField(blank=True, null=True, verbose_name='Caída de Presión'),
        ),
        migrations.AlterField(
            model_name='seccionesprecalentadoragua',
            name='entalpia_entrada',
            field=models.FloatField(blank=True, null=True, verbose_name='Entalpía Entrada'),
        ),
        migrations.AlterField(
            model_name='seccionesprecalentadoragua',
            name='entalpia_salida',
            field=models.FloatField(blank=True, null=True, verbose_name='Entalpía Salida'),
        ),
        migrations.AlterField(
            model_name='seccionesprecalentadoragua',
            name='flujo_masico_entrada',
            field=models.FloatField(blank=True, null=True, verbose_name='Flujo Másico Entrada'),
        ),
        migrations.AlterField(
            model_name='seccionesprecalentadoragua',
            name='flujo_masico_salida',
            field=models.FloatField(blank=True, null=True, verbose_name='Flujo Másico Salida'),
        ),
        migrations.AlterField(
            model_name='seccionesprecalentadoragua',
            name='presion_entrada',
            field=models.FloatField(verbose_name='Presión de Entrada'),
        ),
        migrations.AlterField(
            model_name='seccionesprecalentadoragua',
            name='temp_entrada',
            field=models.FloatField(blank=True, null=True, verbose_name='Temperatura Entrada'),
        ),
        migrations.AlterField(
            model_name='seccionesprecalentadoragua',
            name='temp_salida',
            field=models.FloatField(blank=True, null=True, verbose_name='Temperatura Salida'),
        ),
        migrations.AlterField(
            model_name='seccionesprecalentadoragua',
            name='velocidad_promedio',
            field=models.FloatField(blank=True, null=True, verbose_name='Velocidad Promedio'),
        ),
        migrations.AlterField(
            model_name='seccionesprecalentadoragua',
            name='velocidad_unidad',
            field=models.ForeignKey(blank=True, default=89, on_delete=django.db.models.deletion.PROTECT, related_name='velocidad_unidad_seccion_precalentador_agua', to='intercambiadores.unidades'),
        ),
    ]
