# Generated by Django 4.2.4 on 2024-08-06 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliares', '0070_ventilador_copia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bombas',
            name='copia',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='precalentadoragua',
            name='copia',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
