# Generated by Django 4.2.4 on 2024-08-07 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliares', '0071_bombas_copia_precalentadoragua_copia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluacionventilador',
            name='equipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluaciones_ventilador', to='auxiliares.ventilador'),
        ),
    ]
