# Generated by Django 4.2.4 on 2024-08-15 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intercambiadores', '0073_intercambiador_copia'),
        ('auxiliares', '0073_corrienteprecalentadoragua_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacionprecalentadoragua',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='DatosCorrientesPrecalentadorAgua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('densidad_unidad', models.ForeignKey(default=5, on_delete=django.db.models.deletion.PROTECT, related_name='densidad_unidad_corrientes_precalentador_agua', to='intercambiadores.unidades')),
                ('entalpia_unidad', models.ForeignKey(default=9, on_delete=django.db.models.deletion.PROTECT, related_name='entalpia_unidad_corrientes_precalentador_agua', to='intercambiadores.unidades')),
                ('flujo_unidad', models.ForeignKey(default=6, on_delete=django.db.models.deletion.PROTECT, related_name='flujo_unidad_corrientes_precalentador_agua', to='intercambiadores.unidades')),
                ('presion_unidad', models.ForeignKey(default=7, on_delete=django.db.models.deletion.PROTECT, related_name='presion_unidad_corrientes_precalentador_agua', to='intercambiadores.unidades')),
                ('temperatura_unidad', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='temperatura_unidad_corrientes_precalentador_agua', to='intercambiadores.unidades')),
            ],
        ),
        migrations.AddField(
            model_name='corrienteprecalentadoragua',
            name='datos_corriente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='corrientes_precalentador_agua', to='auxiliares.datoscorrientesprecalentadoragua'),
            preserve_default=False,
        ),
    ]
