# Generated by Django 4.2.4 on 2024-08-15 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliares', '0074_evaluacionprecalentadoragua_activo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evaluacionprecalentadoragua',
            old_name='precalentador',
            new_name='equipo',
        ),
    ]
