# Generated by Django 4.2.4 on 2024-08-16 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliares', '0075_rename_precalentador_evaluacionprecalentadoragua_equipo'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='datoscorrientesprecalentadoragua',
            table='precalentador_agua_datos_corriente',
        ),
    ]
