# Generated by Django 4.2.4 on 2024-08-16 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliares', '0076_alter_datoscorrientesprecalentadoragua_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='precalentadoragua',
            name='datos_corrientes',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='precalentador_agua', to='auxiliares.datoscorrientesprecalentadoragua'),
        ),
    ]
