# Generated by Django 4.2.4 on 2024-08-20 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intercambiadores', '0073_intercambiador_copia'),
        ('auxiliares', '0077_precalentadoragua_datos_corrientes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='corrienteprecalentadoragua',
            options={'ordering': ('lado', 'rol')},
        ),
        migrations.AlterModelOptions(
            name='evaluacionprecalentadoragua',
            options={'ordering': ('-fecha',)},
        ),
        migrations.RemoveField(
            model_name='salidageneralprecalentadoragua',
            name='calor_unidad',
        ),
        migrations.RemoveField(
            model_name='salidageneralprecalentadoragua',
            name='cmin_unidad',
        ),
        migrations.RemoveField(
            model_name='salidageneralprecalentadoragua',
            name='factor_ensuciamiento_unidad',
        ),
        migrations.RemoveField(
            model_name='salidageneralprecalentadoragua',
            name='u_unidad',
        ),
        migrations.AddField(
            model_name='corrientesevaluacionprecalentadoragua',
            name='evaluacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='corrientes_evaluacion_precalentador_agua', to='auxiliares.evaluacionprecalentadoragua'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salidageneralprecalentadoragua',
            name='delta_t_carcasa',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salidageneralprecalentadoragua',
            name='delta_t_tubos',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='corrienteprecalentadoragua',
            name='datos_corriente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='corrientes_precalentador_agua', to='auxiliares.datoscorrientesprecalentadoragua'),
        ),
        migrations.AlterField(
            model_name='corrienteprecalentadoragua',
            name='rol',
            field=models.CharField(choices=[('E', 'Entra'), ('S', 'Sale')], max_length=1),
        ),
        migrations.CreateModel(
            name='DatosCorrientesEvaluacionPrecalentadorAgua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('densidad_unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='densidad_unidad_corriente_evaluacion_precalentador_agua', to='intercambiadores.unidades')),
                ('entalpia_unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entalpia_unidad_corriente_evaluacion_precalentador_agua', to='intercambiadores.unidades')),
                ('flujo_unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flujo_unidad_corriente_evaluacion_precalentador_agua', to='intercambiadores.unidades')),
                ('presion_unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='presion_unidad_corriente_evaluacion_precalentador_agua', to='intercambiadores.unidades')),
                ('temperatura_unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='temperatura_unidad_corriente_evaluacion_precalentador_agua', to='intercambiadores.unidades')),
            ],
        ),
    ]
