# Generated by Django 4.2.4 on 2024-08-20 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliares', '0078_alter_corrienteprecalentadoragua_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='corrientesevaluacionprecalentadoragua',
            name='datos_corrientes',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='corrientes_evaluacion', to='auxiliares.datoscorrientesevaluacionprecalentadoragua'),
            preserve_default=False,
        ),
    ]
