# Generated by Django 4.2.4 on 2024-08-20 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliares', '0079_corrientesevaluacionprecalentadoragua_datos_corrientes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salidageneralprecalentadoragua',
            name='mtd_unidad',
        ),
    ]
