# Generated by Django 4.2.4 on 2024-08-20 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliares', '0080_remove_salidageneralprecalentadoragua_mtd_unidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corrientesevaluacionprecalentadoragua',
            name='evaluacion',
        ),
        migrations.AddField(
            model_name='datoscorrientesevaluacionprecalentadoragua',
            name='evaluacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='evaluaciones_datos_corrientes_precalentador_agua', to='auxiliares.evaluacionprecalentadoragua'),
            preserve_default=False,
        ),
    ]
