# Generated by Django 4.2.4 on 2024-08-20 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliares', '0081_remove_corrientesevaluacionprecalentadoragua_evaluacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datoscorrientesevaluacionprecalentadoragua',
            name='evaluacion',
        ),
        migrations.AddField(
            model_name='evaluacionprecalentadoragua',
            name='datos_corrientes',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, to='auxiliares.datoscorrientesevaluacionprecalentadoragua'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='datoscorrientesevaluacionprecalentadoragua',
            table='precalentador_agua_evaluacion_datos_corrientes',
        ),
    ]
