# Generated by Django 4.2.4 on 2024-08-21 09:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliares', '0082_remove_datoscorrientesevaluacionprecalentadoragua_evaluacion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='corrientesevaluacionprecalentadoragua',
            options={'ordering': ('corriente__rol',)},
        ),
        migrations.AddField(
            model_name='corrientesevaluacionprecalentadoragua',
            name='cp',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='corrienteprecalentadoragua',
            name='fase',
            field=models.CharField(choices=[('L', 'Líquido'), ('G', 'Vapor'), ('S', 'Saturado')], max_length=1),
        ),
        migrations.AlterField(
            model_name='corrienteprecalentadoragua',
            name='flujo',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1e-05)]),
        ),
        migrations.AlterField(
            model_name='corrienteprecalentadoragua',
            name='presion',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1e-05)]),
        ),
        migrations.AlterField(
            model_name='corrientesevaluacionprecalentadoragua',
            name='fase',
            field=models.CharField(choices=[('L', 'Líquido'), ('G', 'Vapor'), ('S', 'Saturado')], max_length=1),
        ),
        migrations.AlterField(
            model_name='corrientesevaluacionprecalentadoragua',
            name='flujo',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1e-05)]),
        ),
        migrations.AlterField(
            model_name='corrientesevaluacionprecalentadoragua',
            name='presion',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1e-05)]),
        ),
        migrations.AlterField(
            model_name='evaluacionprecalentadoragua',
            name='datos_corrientes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='datos_corrientes_evaluacion', to='auxiliares.datoscorrientesevaluacionprecalentadoragua'),
        ),
    ]
