# Generated by Django 4.2.4 on 2024-08-22 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intercambiadores', '0073_intercambiador_copia'),
        ('auxiliares', '0083_alter_corrientesevaluacionprecalentadoragua_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='precalentadoragua',
            name='u',
            field=models.FloatField(default=1, verbose_name='Coeficiente Global de Transferencia General'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='precalentadoragua',
            name='u_unidad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='precalentador_agua_u_unidad', to='intercambiadores.unidades'),
            preserve_default=False,
        ),
    ]
