# Generated by Django 4.2.4 on 2024-08-22 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliares', '0084_precalentadoragua_u_precalentadoragua_u_unidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='salidageneralprecalentadoragua',
            name='invalido',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='salidageneralprecalentadoragua',
            name='perdida_ambiente',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='precalentadoragua',
            name='u',
            field=models.FloatField(verbose_name='Coeficiente Global de Transferencia por Balance General'),
        ),
    ]
