# Generated by Django 4.2.4 on 2024-08-22 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliares', '0085_salidageneralprecalentadoragua_invalido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='precalentadoragua',
            name='u',
            field=models.FloatField(blank=True, null=True, verbose_name='Coeficiente Global de Transferencia por Balance General'),
        ),
    ]
