# Generated by Django 4.2.4 on 2024-08-28 10:21

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('intercambiadores', '0073_intercambiador_copia'),
        ('auxiliares', '0086_alter_precalentadoragua_u'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntradaLado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flujo', models.FloatField()),
                ('temp_entrada', models.FloatField()),
                ('temp_salida', models.FloatField()),
                ('cp_prom', models.FloatField()),
                ('lado', models.CharField(choices=[('A', 'Aire'), ('G', 'Gases')], max_length=1)),
            ],
            options={
                'db_table': 'precalentador_aire_entradalado',
            },
        ),
        migrations.CreateModel(
            name='EspecificacionesPrecalentadorAire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=45)),
                ('espesor', models.FloatField()),
                ('diametro', models.FloatField()),
                ('altura', models.FloatField()),
                ('superficie_calentamiento', models.FloatField(blank=True, null=True)),
                ('area_transferencia', models.FloatField(blank=True, null=True)),
                ('temp_operacion', models.FloatField(blank=True, null=True)),
                ('presion_operacion', models.FloatField(blank=True, null=True)),
                ('u', models.FloatField(blank=True, null=True)),
                ('area_unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='especificaciones_precalentador_aire_area_unidad', to='intercambiadores.unidades')),
                ('longitud_unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='especificaciones_precalentador_aire_longitud_unidad', to='intercambiadores.unidades')),
                ('temp_unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='especificaciones_precalentador_aire_temp_unidad', to='intercambiadores.unidades')),
                ('u_unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='especificaciones_precalentador_aire_u_unidad', to='intercambiadores.unidades')),
            ],
            options={
                'db_table': 'precalentador_aire_especificaciones',
            },
        ),
        migrations.CreateModel(
            name='SalidaEvaluacionPrecalentadorAire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calor_aire', models.FloatField()),
                ('calor_gas', models.FloatField()),
                ('calor_perdido', models.FloatField()),
                ('lmtd', models.FloatField()),
                ('u', models.FloatField()),
                ('ensuciamiento', models.FloatField()),
                ('ntu', models.FloatField()),
                ('eficiencia', models.FloatField()),
                ('u_diseno', models.FloatField()),
                ('cp_aire_entrada', models.FloatField()),
                ('cp_gas_entrada', models.FloatField()),
                ('cp_aire_salida', models.FloatField()),
            ],
            options={
                'db_table': 'precalentador_aire_evaluacion_salida',
            },
        ),
        migrations.CreateModel(
            name='SalidaLado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('entrada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salida_lado', to='auxiliares.entradalado')),
                ('fluido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salida_lado', to='intercambiadores.fluido')),
            ],
            options={
                'db_table': 'precalentador_aire_salidalado',
            },
        ),
        migrations.CreateModel(
            name='PrecalentadorAire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=45)),
                ('descripcion', models.CharField(max_length=80, verbose_name='Descripción del Equipo')),
                ('fabricante', models.CharField(blank=True, max_length=45, null=True)),
                ('modelo', models.CharField(blank=True, max_length=45, null=True)),
                ('tipo', models.CharField(blank=True, max_length=45, null=True)),
                ('copia', models.BooleanField(blank=True, default=False)),
                ('creado_al', models.DateTimeField(auto_now_add=True)),
                ('editado_al', models.DateTimeField(null=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='precalentador_aire_creado_por', to=settings.AUTH_USER_MODEL)),
                ('editado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='precalentador_aire_editado_por', to=settings.AUTH_USER_MODEL)),
                ('especificaciones', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='especificaciones_precalentador_aire', to='auxiliares.especificacionesprecalentadoraire')),
                ('planta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='intercambiadores.planta')),
            ],
            options={
                'db_table': 'precalentador_aire',
                'ordering': ('tag',),
            },
        ),
        migrations.CreateModel(
            name='EvaluacionPrecalentadorAire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('precalentador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluacion_precalentador', to='auxiliares.precalentadoraire')),
                ('salida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluacion_precalentador', to='auxiliares.salidaevaluacionprecalentadoraire')),
            ],
            options={
                'db_table': 'precalentador_aire_evaluacion',
            },
        ),
        migrations.AddField(
            model_name='entradalado',
            name='evaluacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrada_lado', to='auxiliares.evaluacionprecalentadoraire'),
        ),
        migrations.CreateModel(
            name='CondicionFluido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fluido', models.CharField(choices=[('A', 'Aire'), ('G', 'Gases')], max_length=1)),
                ('flujo', models.FloatField(blank=True, null=True)),
                ('temp_entrada', models.FloatField(blank=True, null=True)),
                ('temp_salida', models.FloatField(blank=True, null=True)),
                ('presion_entrada', models.FloatField(blank=True, null=True)),
                ('presion_salida', models.FloatField(blank=True, null=True)),
                ('caida_presion', models.FloatField(blank=True, null=True)),
                ('flujo_unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condicion_fluido_flujo_unidad', to='intercambiadores.unidades')),
                ('precalentador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condicion_fluido', to='auxiliares.precalentadoraire')),
                ('presion_unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condicion_fluido_presion_unidad', to='intercambiadores.unidades')),
                ('temp_unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condicion_fluido_temp_unidad', to='intercambiadores.unidades')),
            ],
            options={
                'db_table': 'precalentador_aire_condicionfluido',
            },
        ),
        migrations.CreateModel(
            name='Composicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('condicion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='composicion', to='auxiliares.condicionfluido')),
                ('fluido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='composicion', to='intercambiadores.fluido')),
            ],
            options={
                'db_table': 'precalentador_aire_composicion',
            },
        ),
    ]
