# Generated by Django 4.2.4 on 2024-09-03 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intercambiadores', '0073_intercambiador_copia'),
        ('auxiliares', '0088_alter_condicionfluido_flujo_unidad_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='condicionfluido',
            options={'ordering': ('fluido',)},
        ),
        migrations.AddField(
            model_name='especificacionesprecalentadoraire',
            name='presion_unidad',
            field=models.ForeignKey(default=33, on_delete=django.db.models.deletion.CASCADE, related_name='especificaciones_precalentador_aire_presion_unidad', to='intercambiadores.unidades'),
        ),
        migrations.AlterField(
            model_name='composicion',
            name='condicion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='composiciones', to='auxiliares.condicionfluido'),
        ),
        migrations.AlterField(
            model_name='especificacionesprecalentadoraire',
            name='longitud_unidad',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.PROTECT, related_name='especificaciones_precalentador_aire_longitud_unidad', to='intercambiadores.unidades'),
        ),
        migrations.AlterField(
            model_name='precalentadoraire',
            name='tag',
            field=models.CharField(max_length=45, unique=True),
        ),
        migrations.AlterModelTable(
            name='entradalado',
            table='precalentador_aire_evaluacion_entradalado',
        ),
        migrations.AlterModelTable(
            name='salidalado',
            table='precalentador_aire_evaluacion_salidalado',
        ),
    ]
