# Generated by Django 4.2.4 on 2024-09-03 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliares', '0089_alter_condicionfluido_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condicionfluido',
            name='flujo',
            field=models.FloatField(blank=True, null=True, verbose_name='Flujo Másico'),
        ),
        migrations.AlterField(
            model_name='condicionfluido',
            name='temp_entrada',
            field=models.FloatField(blank=True, null=True, verbose_name='Temp. de Entrada'),
        ),
        migrations.AlterField(
            model_name='condicionfluido',
            name='temp_salida',
            field=models.FloatField(blank=True, null=True, verbose_name='Temp. de Salida'),
        ),
        migrations.AlterField(
            model_name='especificacionesprecalentadoraire',
            name='area_transferencia',
            field=models.FloatField(blank=True, null=True, verbose_name='Área de Transferecia'),
        ),
        migrations.AlterField(
            model_name='especificacionesprecalentadoraire',
            name='diametro',
            field=models.FloatField(blank=True, null=True, verbose_name='Diámetro de las Tuberías'),
        ),
        migrations.AlterField(
            model_name='especificacionesprecalentadoraire',
            name='espesor',
            field=models.FloatField(blank=True, null=True, verbose_name='Espesor de las Tuberías'),
        ),
        migrations.AlterField(
            model_name='especificacionesprecalentadoraire',
            name='presion_operacion',
            field=models.FloatField(blank=True, null=True, verbose_name='Presión de Operación'),
        ),
        migrations.AlterField(
            model_name='especificacionesprecalentadoraire',
            name='superficie_calentamiento',
            field=models.FloatField(blank=True, null=True, verbose_name='Superficie Calentamiento'),
        ),
        migrations.AlterField(
            model_name='especificacionesprecalentadoraire',
            name='temp_operacion',
            field=models.FloatField(blank=True, null=True, verbose_name='Temperatura de Operación'),
        ),
        migrations.AlterField(
            model_name='especificacionesprecalentadoraire',
            name='u',
            field=models.FloatField(blank=True, null=True, verbose_name='Coeficiente Global de Transferencia'),
        ),
    ]
