# Generated by Django 4.2.4 on 2024-09-04 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('intercambiadores', '0073_intercambiador_copia'),
        ('auxiliares', '0090_alter_condicionfluido_flujo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradalado',
            name='flujo_unidad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='entrada_lado_flujo_unidad', to='intercambiadores.unidades'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entradalado',
            name='temp_unidad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='entrada_lado_temp_unidad', to='intercambiadores.unidades'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evaluacionprecalentadoraire',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='evaluacionprecalentadoraire',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='evaluacion_precalentador_aire_usuario', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
