# Generated by Django 4.2.4 on 2024-09-05 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliares', '0091_entradalado_flujo_unidad_entradalado_temp_unidad_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evaluacionprecalentadoraire',
            old_name='precalentador',
            new_name='equipo',
        ),
    ]
