# Generated by Django 4.2.4 on 2024-09-05 14:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliares', '0094_composicionesevaluacionprecalentadoraire_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='composicionesevaluacionprecalentadoraire',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='entradalado',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='evaluacionprecalentadoraire',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='salidaevaluacionprecalentadoraire',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
