# Generated by Django 4.2.4 on 2024-09-06 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliares', '0095_alter_composicionesevaluacionprecalentadoraire_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entradalado',
            old_name='cp_prom',
            new_name='cp_entrada',
        ),
        migrations.AddField(
            model_name='entradalado',
            name='cp_salida',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entradalado',
            name='flujo',
            field=models.FloatField(verbose_name='Flujo Másico'),
        ),
        migrations.AlterField(
            model_name='entradalado',
            name='temp_entrada',
            field=models.FloatField(verbose_name='Temperatura de Entrada'),
        ),
        migrations.AlterField(
            model_name='entradalado',
            name='temp_salida',
            field=models.FloatField(verbose_name='Temperatura de Salida'),
        ),
        migrations.AlterField(
            model_name='salidaevaluacionprecalentadoraire',
            name='u_diseno',
            field=models.FloatField(null=True),
        ),
    ]
