# Generated by Django 4.2.4 on 2024-09-06 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliares', '0096_rename_cp_prom_entradalado_cp_entrada_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entradalado',
            name='cp_entrada',
        ),
        migrations.RemoveField(
            model_name='entradalado',
            name='cp_salida',
        ),
        migrations.AddField(
            model_name='salidaevaluacionprecalentadoraire',
            name='cp_gas_salida',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
