# Generated by Django 4.2.4 on 2024-09-12 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intercambiadores', '0073_intercambiador_copia'),
        ('auxiliares', '0097_remove_entradalado_cp_entrada_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entradalado',
            options={'ordering': ('lado',)},
        ),
        migrations.AlterModelOptions(
            name='evaluacionprecalentadoraire',
            options={'ordering': ('-fecha',)},
        ),
        migrations.AlterField(
            model_name='composicionesevaluacionprecalentadoraire',
            name='fluido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intercambiadores.fluido'),
        ),
        migrations.AlterField(
            model_name='corrienteprecalentadoragua',
            name='lado',
            field=models.CharField(choices=[('C', 'Carcasa'), ('T', 'Tubos'), ('A', 'Aire'), ('G', 'Gases')], max_length=1),
        ),
    ]
