# Generated by Django 4.2.4 on 2024-10-10 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliares', '0098_alter_entradalado_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallesmotorbomba',
            name='aislamiento',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
