# Generated by Django 4.2.4 on 2024-11-09 17:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliares', '0098_alter_entradalado_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bombas',
            name='fabricante',
            field=models.CharField(max_length=45, null=True, verbose_name='Fabricante*'),
        ),
        migrations.AlterField(
            model_name='condicionesdisenobomba',
            name='capacidad',
            field=models.FloatField(null=True, verbose_name='Capacidad*'),
        ),
        migrations.AlterField(
            model_name='condicionesdisenobomba',
            name='presion_descarga',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name='Presión de Descarga*'),
        ),
        migrations.AlterField(
            model_name='condicionesdisenobomba',
            name='presion_succion',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name='Presión de Succión*'),
        ),
        migrations.AlterField(
            model_name='condicionfluidobomba',
            name='temperatura_operacion',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name='Temperatura de Operación*'),
        ),
        migrations.AlterField(
            model_name='entradaevaluacionbomba',
            name='temperatura_operacion',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(-273.15), django.core.validators.MaxValueValidator(9999.99)], verbose_name='Temperatura de Operación'),
        ),
        migrations.AlterField(
            model_name='especificacionesbomba',
            name='cabezal_total',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.0001)]),
        ),
        migrations.AlterField(
            model_name='especificacionesbomba',
            name='descarga_id',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name='Diámetro Interno Descarga'),
        ),
        migrations.AlterField(
            model_name='especificacionesbomba',
            name='potencia_maxima',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name='Potencia Máxima'),
        ),
        migrations.AlterField(
            model_name='especificacionesbomba',
            name='succion_id',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name='Diámetro Interno Succión'),
        ),
        migrations.AlterField(
            model_name='especificacionesbomba',
            name='velocidad',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name='Velocidad'),
        ),
    ]
