# Generated by Django 4.2.4 on 2024-10-17 13:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliares', '0099_alter_detallesmotorbomba_aislamiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradaevaluacionbomba',
            name='altura_descarga',
            field=models.FloatField(validators=[django.core.validators.MaxValueValidator(9999999.99999)], verbose_name='Altura'),
        ),
        migrations.AlterField(
            model_name='entradaevaluacionbomba',
            name='altura_succion',
            field=models.FloatField(validators=[django.core.validators.MaxValueValidator(9999999.99999)], verbose_name='Altura'),
        ),
    ]
