# Generated by Django 4.2.4 on 2024-10-21 10:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliares', '0100_alter_entradaevaluacionbomba_altura_descarga_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condicionesdisenobomba',
            name='presion_diferencial',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Presión Diferencial'),
        ),
        migrations.AlterField(
            model_name='condicionfluidobomba',
            name='corrosividad',
            field=models.CharField(blank=True, choices=[('C', 'Corrosivo'), ('E', 'Erosivo'), ('N', 'No Erosivo ni Corrosivo'), ('A', 'Ambos'), ('D', 'Desconocido')], max_length=1, null=True, verbose_name='Corrosivo/Erosivo*'),
        ),
        migrations.AlterField(
            model_name='condicionfluidobomba',
            name='inflamable',
            field=models.CharField(blank=True, choices=[('S', 'Sí'), ('N', 'No'), ('D', 'Desconocido')], max_length=1, null=True, verbose_name='Inflamable*'),
        ),
        migrations.AlterField(
            model_name='condicionfluidobomba',
            name='peligroso',
            field=models.CharField(blank=True, choices=[('S', 'Sí'), ('N', 'No'), ('D', 'Desconocido')], max_length=1, null=True, verbose_name='Peligroso*'),
        ),
        migrations.AlterField(
            model_name='detallesmotorbomba',
            name='fases',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detallesmotorbomba',
            name='frecuencia',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0001)]),
        ),
        migrations.AlterField(
            model_name='detallesmotorbomba',
            name='velocidad_motor',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name='Velocidad del Motor'),
        ),
        migrations.AlterField(
            model_name='detallesmotorbomba',
            name='voltaje',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name='Voltaje del Motor'),
        ),
        migrations.AlterField(
            model_name='especificacionesbomba',
            name='eficiencia',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='especificacionesbomba',
            name='velocidad',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0001)]),
        ),
    ]
