# Generated by Django 4.2.4 on 2024-10-21 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliares', '0101_alter_condicionesdisenobomba_presion_diferencial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especificacionesbomba',
            name='numero_etapas',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Número de Etapas'),
        ),
    ]
