# Generated by Django 4.2.4 on 2024-10-25 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliares', '0103_alter_especificacionesbomba_velocidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condicionfluidobomba',
            name='corrosividad',
            field=models.CharField(blank=True, choices=[('C', 'Corrosivo'), ('E', 'Erosivo'), ('N', 'No Erosivo ni Corrosivo'), ('A', 'Ambos'), ('D', 'Desconocido')], max_length=1, null=True, verbose_name='Corrosivo/Erosivo'),
        ),
        migrations.AlterField(
            model_name='condicionfluidobomba',
            name='inflamable',
            field=models.CharField(blank=True, choices=[('S', 'Sí'), ('N', 'No'), ('D', 'Desconocido')], max_length=1, null=True, verbose_name='Inflamable'),
        ),
        migrations.AlterField(
            model_name='condicionfluidobomba',
            name='peligroso',
            field=models.CharField(blank=True, choices=[('S', 'Sí'), ('N', 'No'), ('D', 'Desconocido')], max_length=1, null=True, verbose_name='Peligroso'),
        ),
    ]
