# Generated by Django 4.2.4 on 2024-11-14 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliares', '0099_alter_bombas_fabricante_and_more'),
        ('auxiliares', '0104_alter_condicionfluidobomba_corrosividad_and_more'),
    ]

    operations = [
    ]
