# Generated by Django 4.2.4 on 2024-11-14 09:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliares', '0105_merge_20241114_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condicionesdisenobomba',
            name='presion_diferencial',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name='Presión Diferencial'),
        ),
        migrations.AlterField(
            model_name='especificacionesbomba',
            name='potencia_maxima',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name='Potencia Máxima*'),
        ),
        migrations.AlterField(
            model_name='especificacionesbomba',
            name='velocidad',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name='Velocidad*'),
        ),
    ]
