# Generated by Django 4.2.4 on 2024-12-13 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxiliares', '0106_alter_condicionesdisenobomba_presion_diferencial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condicionfluido',
            name='caida_presion',
            field=models.FloatField(blank=True, null=True, verbose_name='Caída de Presión'),
        ),
        migrations.AlterField(
            model_name='condicionfluido',
            name='presion_entrada',
            field=models.FloatField(blank=True, null=True, verbose_name='Presión de Entrada'),
        ),
        migrations.AlterField(
            model_name='condicionfluido',
            name='presion_salida',
            field=models.FloatField(blank=True, null=True, verbose_name='Presión de Salida'),
        ),
    ]
