# Generated by Django 4.2.4 on 2024-09-13 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_envio_id_alter_respuesta_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respuesta',
            name='nombre',
        ),
        migrations.AddField(
            model_name='respuesta',
            name='respuesta',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='seccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='usuarios.seccion'),
        ),
        migrations.AlterField(
            model_name='seccion',
            name='encuesta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secciones', to='usuarios.encuesta'),
        ),
    ]
