# Generated by Django 4.2.4 on 2024-09-13 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_remove_respuesta_nombre_respuesta_respuesta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuesta',
            name='respuesta',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
