# Generated by Django 4.2.4 on 2024-09-18 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_respuesta_respuesta'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='envio',
            options={'ordering': ('-fecha',)},
        ),
        migrations.AlterField(
            model_name='envio',
            name='encuesta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envios', to='usuarios.encuesta'),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='envio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='usuarios.envio'),
        ),
        migrations.AlterUniqueTogether(
            name='respuesta',
            unique_together={('envio', 'pregunta')},
        ),
    ]
