# Generated by Django 4.2.4 on 2024-10-31 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('intercambiadores', '0074_alter_planta_options'),
        ('usuarios', '0005_alter_envio_options_alter_envio_encuesta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantaAccesible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planta_usuario', to='intercambiadores.planta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_planta', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
