# Generated by Django 4.2.4 on 2024-11-14 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_plantaaccesible'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantaaccesible',
            name='crear',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plantaaccesible',
            name='duplicacion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plantaaccesible',
            name='edicion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plantaaccesible',
            name='edicion_instalacion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plantaaccesible',
            name='eliminacion_evaluaciones',
            field=models.BooleanField(default=False),
        ),
    ]
