# Generated by Django 4.2.4 on 2024-11-16 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_plantaaccesible_crear_plantaaccesible_duplicacion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plantaaccesible',
            old_name='eliminacion_evaluaciones',
            new_name='crear_evaluaciones',
        ),
        migrations.AddField(
            model_name='plantaaccesible',
            name='eliminar_evaluaciones',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plantaaccesible',
            name='ver_evaluaciones',
            field=models.BooleanField(default=False),
        ),
    ]
