# Generated by Django 4.2.4 on 2024-12-03 11:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('intercambiadores', '0079_alter_intercambiador_criticidad'),
        ('usuarios', '0008_rename_eliminacion_evaluaciones_plantaaccesible_crear_evaluaciones_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermisoPorComplejo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('complejo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intercambiadores.complejo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
