# Generated by Django 4.2.4 on 2024-12-04 08:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuarios', '0009_permisoporcomplejo'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantaaccesible',
            name='administrar_usuarios',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='permisoporcomplejo',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos_complejo', to=settings.AUTH_USER_MODEL),
        ),
    ]
