# Generated by Django 4.2.4 on 2024-12-06 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_usuariored'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariored',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
