# Generated by Django 4.2.4 on 2024-12-06 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0012_alter_usuariored_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariored',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
