# Generated by Django 4.2.4 on 2024-12-13 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0015_alter_usuariored_usuario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plantaaccesible',
            options={'ordering': ('-planta__complejo__pk',)},
        ),
    ]
