# Generated by Django 4.2.4 on 2025-02-11 13:38

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('intercambiadores', '0083_alter_evaluacionesintercambiador_ensuciamiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compresor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=20, unique=True)),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripción')),
                ('fabricante', models.CharField(blank=True, max_length=45, null=True)),
                ('modelo', models.CharField(blank=True, max_length=45, null=True)),
                ('creado_al', models.DateTimeField(auto_now_add=True)),
                ('editado_al', models.DateTimeField(null=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compresor_creado_por', to=settings.AUTH_USER_MODEL)),
                ('editado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compresor_editado_por', to=settings.AUTH_USER_MODEL)),
                ('planta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='intercambiadores.planta')),
            ],
        ),
        migrations.CreateModel(
            name='EtapaCompresor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('nombre_fluido', models.CharField(blank=True, max_length=45, null=True)),
                ('flujo_masico', models.FloatField(blank=True, null=True)),
                ('flujo_molar', models.FloatField(blank=True, null=True)),
                ('densidad', models.FloatField(blank=True, null=True)),
                ('aumento_estimado', models.FloatField(blank=True, null=True)),
                ('rel_compresion', models.FloatField(blank=True, null=True)),
                ('potencial_nominal', models.FloatField(blank=True, null=True)),
                ('potencia_req', models.FloatField(blank=True, null=True, verbose_name='Potencia Requerida')),
                ('eficiencia_isentropica', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('eficiencia_politropica', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('cabezal_politropico', models.FloatField(blank=True, null=True)),
                ('humedad_relativa', models.FloatField(blank=True, null=True)),
                ('volumen_diseno', models.FloatField(blank=True, null=True)),
                ('volumen_normal', models.FloatField(blank=True, null=True)),
                ('curva_caracteristica', models.FileField(blank=True, null=True, upload_to='')),
                ('cabezal_unidad', models.ForeignKey(blank=True, default=4, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unidad_cabezal_compresor', to='intercambiadores.unidades')),
            ],
        ),
        migrations.CreateModel(
            name='TipoCompresor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoLubricacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PropiedadesCompresor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_impulsores', models.IntegerField(blank=True, null=True)),
                ('material_carcasa', models.CharField(blank=True, max_length=45, null=True)),
                ('tipo_lubricante', models.CharField(blank=True, max_length=45, null=True, verbose_name='Tipo de lubricante(ROT)')),
                ('tipo_sello', models.CharField(blank=True, max_length=45, null=True)),
                ('velocidad_max_continua', models.FloatField(blank=True, null=True)),
                ('velocidad_rotacion', models.FloatField(blank=True, null=True)),
                ('potencia_requerida', models.FloatField(blank=True, null=True)),
                ('compresor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='compresores.compresor')),
                ('tipo_lubricacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='compresores.tipolubricacion')),
                ('unidad_potencia', models.ForeignKey(blank=True, default=53, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unidad_potencia_compresor', to='intercambiadores.unidades')),
                ('unidad_velocidad', models.ForeignKey(blank=True, default=52, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unidad_velocidad_compresor', to='intercambiadores.unidades')),
            ],
        ),
        migrations.CreateModel(
            name='LadoEtapaCompresor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lado', models.CharField(choices=[('I', 'Entrada'), ('E', 'Salida')], max_length=1)),
                ('temp', models.FloatField(blank=True, null=True)),
                ('presion', models.FloatField(blank=True, null=True)),
                ('cp_cv', models.FloatField(blank=True, null=True)),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='compresores.etapacompresor')),
                ('presion_unidad', models.ForeignKey(blank=True, default=7, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unidad_presion_etapa_compresor', to='intercambiadores.unidades')),
                ('temp_unidad', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unidad_temp_etapa_compresor', to='intercambiadores.unidades')),
            ],
        ),
        migrations.AddField(
            model_name='etapacompresor',
            name='compresor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='compresores.propiedadescompresor'),
        ),
        migrations.AddField(
            model_name='etapacompresor',
            name='densidad_unidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unidad_densidad_compresor', to='intercambiadores.unidades'),
        ),
        migrations.AddField(
            model_name='etapacompresor',
            name='flujo_masico_unidad',
            field=models.ForeignKey(blank=True, default=54, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unidad_flujo_masico_compresor', to='intercambiadores.unidades'),
        ),
        migrations.AddField(
            model_name='etapacompresor',
            name='flujo_molar_unidad',
            field=models.ForeignKey(blank=True, default=94, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unidad_flujo_molar_compresor', to='intercambiadores.unidades'),
        ),
        migrations.AddField(
            model_name='etapacompresor',
            name='potencia_unidad',
            field=models.ForeignKey(blank=True, default=53, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unidad_potencia_etapa_compresor', to='intercambiadores.unidades'),
        ),
        migrations.AddField(
            model_name='etapacompresor',
            name='volumen_unidad',
            field=models.ForeignKey(blank=True, default=34, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unidad_volumen_etapa_compresor', to='intercambiadores.unidades'),
        ),
        migrations.AddField(
            model_name='compresor',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='compresores.tipocompresor'),
        ),
        migrations.CreateModel(
            name='ComposicionGases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porc_molar', models.FloatField(blank=True, null=True)),
                ('compuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intercambiadores.fluido')),
            ],
        ),
    ]
