# Generated by Django 4.2.4 on 2025-02-11 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compresores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ladoetapacompresor',
            name='compresibilidad',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
