# Generated by Django 4.2.4 on 2025-02-12 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compresores', '0002_ladoetapacompresor_compresibilidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='composiciongases',
            name='etapa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='composiciones', to='compresores.etapacompresor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='compresor',
            name='copia',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='etapacompresor',
            name='compresor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='etapas', to='compresores.propiedadescompresor'),
        ),
        migrations.AlterField(
            model_name='ladoetapacompresor',
            name='etapa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lados', to='compresores.etapacompresor'),
        ),
        migrations.AlterField(
            model_name='propiedadescompresor',
            name='compresor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='casos', to='compresores.compresor'),
        ),
    ]
