# Generated by Django 4.2.4 on 2025-02-12 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compresores', '0003_composiciongases_etapa_compresor_copia_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compresor',
            options={'ordering': ('tag',)},
        ),
        migrations.RemoveField(
            model_name='propiedadescompresor',
            name='tipo_lubricante',
        ),
    ]
