# Generated by Django 4.2.4 on 2025-02-12 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compresores', '0004_alter_compresor_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='etapacompresor',
            options={'ordering': ('numero',)},
        ),
    ]
