# Generated by Django 4.2.4 on 2025-02-12 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compresores', '0005_alter_etapacompresor_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='etapacompresor',
            old_name='potencial_nominal',
            new_name='potencia_nominal',
        ),
    ]
