# Generated by Django 4.2.4 on 2025-02-14 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intercambiadores', '0083_alter_evaluacionesintercambiador_ensuciamiento'),
        ('compresores', '0006_rename_potencial_nominal_etapacompresor_potencia_nominal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etapacompresor',
            name='densidad_unidad',
            field=models.ForeignKey(blank=True, default=43, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unidad_densidad_compresor', to='intercambiadores.unidades'),
        ),
    ]
