# Generated by Django 4.2.4 on 2025-02-14 12:10

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intercambiadores', '0083_alter_evaluacionesintercambiador_ensuciamiento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('compresores', '0007_alter_etapacompresor_densidad_unidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='compresor',
            name='curva_caracteristica',
            field=models.FileField(blank=True, null=True, upload_to='compresores/curvas-compresores/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg'])], verbose_name='Curva de Característica'),
        ),
        migrations.AlterField(
            model_name='composiciongases',
            name='compuesto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intercambiadores.fluido', verbose_name='Compuesto'),
        ),
        migrations.AlterField(
            model_name='composiciongases',
            name='etapa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='composiciones', to='compresores.etapacompresor', verbose_name='Etapa del Compresor'),
        ),
        migrations.AlterField(
            model_name='composiciongases',
            name='porc_molar',
            field=models.FloatField(blank=True, null=True, verbose_name='Porcentaje Molar'),
        ),
        migrations.AlterField(
            model_name='compresor',
            name='copia',
            field=models.BooleanField(blank=True, default=False, verbose_name='Es Copia'),
        ),
        migrations.AlterField(
            model_name='compresor',
            name='creado_al',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='compresor',
            name='creado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compresor_creado_por', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AlterField(
            model_name='compresor',
            name='descripcion',
            field=models.CharField(max_length=100, verbose_name='Descripción del Compresor'),
        ),
        migrations.AlterField(
            model_name='compresor',
            name='editado_al',
            field=models.DateTimeField(null=True, verbose_name='Fecha de Última Edición'),
        ),
        migrations.AlterField(
            model_name='compresor',
            name='editado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compresor_editado_por', to=settings.AUTH_USER_MODEL, verbose_name='Editado por'),
        ),
        migrations.AlterField(
            model_name='compresor',
            name='fabricante',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Fabricante'),
        ),
        migrations.AlterField(
            model_name='compresor',
            name='modelo',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Modelo del Compresor'),
        ),
        migrations.AlterField(
            model_name='compresor',
            name='planta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='intercambiadores.planta', verbose_name='Planta'),
        ),
        migrations.AlterField(
            model_name='compresor',
            name='tag',
            field=models.CharField(max_length=20, unique=True, verbose_name='Tag'),
        ),
        migrations.AlterField(
            model_name='compresor',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='compresores.tipocompresor', verbose_name='Tipo de Compresor'),
        ),
        migrations.AlterField(
            model_name='etapacompresor',
            name='aumento_estimado',
            field=models.FloatField(blank=True, null=True, verbose_name='Aumento Estimado'),
        ),
        migrations.AlterField(
            model_name='etapacompresor',
            name='cabezal_politropico',
            field=models.FloatField(blank=True, null=True, verbose_name='Cabezal Politrópico'),
        ),
        migrations.AlterField(
            model_name='etapacompresor',
            name='cabezal_unidad',
            field=models.ForeignKey(blank=True, default=4, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unidad_cabezal_compresor', to='intercambiadores.unidades', verbose_name='Unidad'),
        ),
        migrations.AlterField(
            model_name='etapacompresor',
            name='compresor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='etapas', to='compresores.propiedadescompresor', verbose_name='Compresor'),
        ),
        migrations.AlterField(
            model_name='etapacompresor',
            name='curva_caracteristica',
            field=models.FileField(blank=True, null=True, upload_to='compresores/curvas-etapas/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg'])], verbose_name='Curva Característica'),
        ),
        migrations.AlterField(
            model_name='etapacompresor',
            name='densidad',
            field=models.FloatField(blank=True, null=True, verbose_name='Densidad'),
        ),
        migrations.AlterField(
            model_name='etapacompresor',
            name='densidad_unidad',
            field=models.ForeignKey(blank=True, default=43, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unidad_densidad_compresor', to='intercambiadores.unidades', verbose_name='Unidad'),
        ),
        migrations.AlterField(
            model_name='etapacompresor',
            name='eficiencia_isentropica',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Eficiencia Isentrópica'),
        ),
        migrations.AlterField(
            model_name='etapacompresor',
            name='eficiencia_politropica',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Eficiencia Politrópica'),
        ),
        migrations.AlterField(
            model_name='etapacompresor',
            name='flujo_masico',
            field=models.FloatField(blank=True, null=True, verbose_name='Flujo Másico'),
        ),
        migrations.AlterField(
            model_name='etapacompresor',
            name='flujo_masico_unidad',
            field=models.ForeignKey(blank=True, default=54, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unidad_flujo_masico_compresor', to='intercambiadores.unidades', verbose_name='Unidad'),
        ),
        migrations.AlterField(
            model_name='etapacompresor',
            name='flujo_molar',
            field=models.FloatField(blank=True, null=True, verbose_name='Flujo Molar'),
        ),
        migrations.AlterField(
            model_name='etapacompresor',
            name='flujo_molar_unidad',
            field=models.ForeignKey(blank=True, default=94, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unidad_flujo_molar_compresor', to='intercambiadores.unidades', verbose_name='Unidad'),
        ),
        migrations.AlterField(
            model_name='etapacompresor',
            name='humedad_relativa',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Humedad Relativa (%)'),
        ),
        migrations.AlterField(
            model_name='etapacompresor',
            name='nombre_fluido',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Nombre del Gas'),
        ),
        migrations.AlterField(
            model_name='etapacompresor',
            name='numero',
            field=models.IntegerField(verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='etapacompresor',
            name='potencia_nominal',
            field=models.FloatField(blank=True, null=True, verbose_name='Potencia Nominal'),
        ),
        migrations.AlterField(
            model_name='etapacompresor',
            name='potencia_unidad',
            field=models.ForeignKey(blank=True, default=53, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unidad_potencia_etapa_compresor', to='intercambiadores.unidades', verbose_name='Unidad'),
        ),
        migrations.AlterField(
            model_name='etapacompresor',
            name='rel_compresion',
            field=models.FloatField(blank=True, null=True, verbose_name='Relación de Compresión'),
        ),
        migrations.AlterField(
            model_name='etapacompresor',
            name='volumen_diseno',
            field=models.FloatField(blank=True, null=True, verbose_name='Volumen de Diseño'),
        ),
        migrations.AlterField(
            model_name='etapacompresor',
            name='volumen_normal',
            field=models.FloatField(blank=True, null=True, verbose_name='Volumen Normal'),
        ),
        migrations.AlterField(
            model_name='etapacompresor',
            name='volumen_unidad',
            field=models.ForeignKey(blank=True, default=34, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unidad_volumen_etapa_compresor', to='intercambiadores.unidades', verbose_name='Unidad'),
        ),
        migrations.AlterField(
            model_name='ladoetapacompresor',
            name='compresibilidad',
            field=models.FloatField(blank=True, null=True, verbose_name='Compresibilidad'),
        ),
        migrations.AlterField(
            model_name='ladoetapacompresor',
            name='cp_cv',
            field=models.FloatField(blank=True, null=True, verbose_name='Relación Cp/Cv'),
        ),
        migrations.AlterField(
            model_name='ladoetapacompresor',
            name='etapa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lados', to='compresores.etapacompresor', verbose_name='Etapa del Compresor'),
        ),
        migrations.AlterField(
            model_name='ladoetapacompresor',
            name='lado',
            field=models.CharField(choices=[('I', 'Entrada'), ('E', 'Salida')], max_length=1, verbose_name='Lado del Compresor'),
        ),
        migrations.AlterField(
            model_name='ladoetapacompresor',
            name='presion',
            field=models.FloatField(blank=True, null=True, verbose_name='Presión'),
        ),
        migrations.AlterField(
            model_name='ladoetapacompresor',
            name='presion_unidad',
            field=models.ForeignKey(blank=True, default=7, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unidad_presion_etapa_compresor', to='intercambiadores.unidades', verbose_name='Unidad de Presión'),
        ),
        migrations.AlterField(
            model_name='ladoetapacompresor',
            name='temp',
            field=models.FloatField(blank=True, null=True, verbose_name='Temperatura'),
        ),
        migrations.AlterField(
            model_name='ladoetapacompresor',
            name='temp_unidad',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unidad_temp_etapa_compresor', to='intercambiadores.unidades', verbose_name='Unidad de Temperatura'),
        ),
        migrations.AlterField(
            model_name='propiedadescompresor',
            name='compresor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='casos', to='compresores.compresor', verbose_name='Compresor'),
        ),
        migrations.AlterField(
            model_name='propiedadescompresor',
            name='material_carcasa',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Material de la Carcasa'),
        ),
        migrations.AlterField(
            model_name='propiedadescompresor',
            name='numero_impulsores',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número de Impulsores'),
        ),
        migrations.AlterField(
            model_name='propiedadescompresor',
            name='potencia_requerida',
            field=models.FloatField(blank=True, null=True, verbose_name='Potencia Requerida'),
        ),
        migrations.AlterField(
            model_name='propiedadescompresor',
            name='tipo_lubricacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='compresores.tipolubricacion', verbose_name='Tipo de Lubricación'),
        ),
        migrations.AlterField(
            model_name='propiedadescompresor',
            name='tipo_sello',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Tipo de Sello'),
        ),
        migrations.AlterField(
            model_name='propiedadescompresor',
            name='unidad_potencia',
            field=models.ForeignKey(blank=True, default=53, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unidad_potencia_compresor', to='intercambiadores.unidades', verbose_name='Unidad de la Potencia'),
        ),
        migrations.AlterField(
            model_name='propiedadescompresor',
            name='unidad_velocidad',
            field=models.ForeignKey(blank=True, default=52, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unidad_velocidad_compresor', to='intercambiadores.unidades', verbose_name='Unidad de la Velocidad'),
        ),
        migrations.AlterField(
            model_name='propiedadescompresor',
            name='velocidad_max_continua',
            field=models.FloatField(blank=True, null=True, verbose_name='Velocidad Máxima Continua'),
        ),
        migrations.AlterField(
            model_name='propiedadescompresor',
            name='velocidad_rotacion',
            field=models.FloatField(blank=True, null=True, verbose_name='Velocidad de Rotación'),
        ),
    ]
