# Generated by Django 4.2.4 on 2025-02-19 11:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compresores', '0008_compresor_curva_caracteristica_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compresor',
            name='curva_caracteristica',
        ),
        migrations.AddField(
            model_name='propiedadescompresor',
            name='curva_caracteristica',
            field=models.FileField(blank=True, null=True, upload_to='compresores/curvas-compresores/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg'])], verbose_name='Curva de Característica'),
        ),
        migrations.AlterField(
            model_name='etapacompresor',
            name='curva_caracteristica',
            field=models.FileField(blank=True, null=True, upload_to='compresores/curvas-etapas/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'pdf'])], verbose_name='Curva Característica'),
        ),
    ]
