# Generated by Django 4.2.4 on 2025-02-26 15:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('compresores', '0009_remove_compresor_curva_caracteristica_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('-fecha',),
            },
        ),
    ]
