# Generated by Django 4.2.4 on 2025-02-26 15:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('compresores', '0010_evaluacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacion',
            name='creado_por',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='evaluaciones_compresor_usuario', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='equipo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='evaluaciones_compresor', to='compresores.compresor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='nombre',
            field=models.CharField(max_length=45),
        ),
    ]
