# Generated by Django 4.2.4 on 2025-02-27 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compresores', '0011_evaluacion_creado_por_evaluacion_equipo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedadescompresor',
            name='tipo_lubricante',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Tipo de Lubricante'),
        ),
    ]
