# Generated by Django 4.2.4 on 2025-03-17 15:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intercambiadores', '0083_alter_evaluacionesintercambiador_ensuciamiento'),
        ('compresores', '0013_entradaetapaevaluacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradaetapaevaluacion',
            name='velocidad',
            field=models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(1e-05)], verbose_name='Velocidad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entradaetapaevaluacion',
            name='velocidad_unidad',
            field=models.ForeignKey(blank=True, default=55, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unidad_velocidad_evaluacion', to='intercambiadores.unidades', verbose_name='Unidad'),
        ),
        migrations.AlterField(
            model_name='composiciongases',
            name='porc_molar',
            field=models.FloatField(blank=True, default=0.0, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Porcentaje Molar'),
        ),
    ]
