# Generated by Django 4.2.4 on 2025-03-17 15:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compresores', '0014_entradaetapaevaluacion_velocidad_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entradaetapaevaluacion',
            old_name='k',
            new_name='k_in',
        ),
        migrations.RemoveField(
            model_name='entradaetapaevaluacion',
            name='presion',
        ),
        migrations.AddField(
            model_name='entradaetapaevaluacion',
            name='k_out',
            field=models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(1e-05)], verbose_name='Relación de Compresión'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entradaetapaevaluacion',
            name='presion_in',
            field=models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(1e-05)], verbose_name='Presión de Entrada'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entradaetapaevaluacion',
            name='presion_out',
            field=models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(1e-05)], verbose_name='Presión de Salida'),
            preserve_default=False,
        ),
    ]
