# Generated by Django 4.2.4 on 2025-03-20 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compresores', '0015_rename_k_entradaetapaevaluacion_k_in_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salidaetapaevaluacion',
            old_name='k_calculada',
            new_name='k_in',
        ),
        migrations.AddField(
            model_name='salidaetapaevaluacion',
            name='energia_ret',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='salidaetapaevaluacion',
            name='k_out',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salidaetapaevaluacion',
            name='pm_calculado',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salidaetapaevaluacion',
            name='caida_presion',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='salidaetapaevaluacion',
            name='caida_temp',
            field=models.FloatField(null=True),
        ),
    ]
