# Generated by Django 4.2.4 on 2025-03-25 10:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compresores', '0016_rename_k_calculada_salidaetapaevaluacion_k_in_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salidaetapaevaluacion',
            name='he',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salidaetapaevaluacion',
            name='hs',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='composicionevaluacion',
            name='porc_molar',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Porcentaje'),
        ),
        migrations.AlterField(
            model_name='salidaetapaevaluacion',
            name='entrada_etapa',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='salidas', to='compresores.entradaetapaevaluacion'),
        ),
    ]
