# Generated by Django 4.2.4 on 2025-03-27 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intercambiadores', '0083_alter_evaluacionesintercambiador_ensuciamiento'),
        ('compresores', '0017_salidaetapaevaluacion_he_salidaetapaevaluacion_hs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salidaetapaevaluacion',
            name='caida_presion_unidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unidad_caida_presion_evaluacion', to='intercambiadores.unidades', verbose_name='Unidad'),
        ),
        migrations.AddField(
            model_name='salidaetapaevaluacion',
            name='caida_temp_unidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unidad_caida_temp_evaluacion', to='intercambiadores.unidades', verbose_name='Unidad'),
        ),
        migrations.AlterField(
            model_name='entradaetapaevaluacion',
            name='cabezal_politropico_unidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unidad_cabezal_politropico_evaluacion', to='intercambiadores.unidades', verbose_name='Unidad'),
        ),
        migrations.AlterField(
            model_name='entradaetapaevaluacion',
            name='flujo_gas_unidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unidad_flujo_gas_evaluacion', to='intercambiadores.unidades', verbose_name='Unidad'),
        ),
        migrations.AlterField(
            model_name='entradaetapaevaluacion',
            name='flujo_volumetrico_unidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unidad_flujo_volumetrico_evaluacion', to='intercambiadores.unidades', verbose_name='Unidad'),
        ),
        migrations.AlterField(
            model_name='entradaetapaevaluacion',
            name='pm_ficha_unidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unidad_pm_ficha_evaluacion', to='intercambiadores.unidades', verbose_name='Unidad'),
        ),
        migrations.AlterField(
            model_name='entradaetapaevaluacion',
            name='potencia_generada_unidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unidad_potencia_generada_evaluacion', to='intercambiadores.unidades', verbose_name='Unidad'),
        ),
        migrations.AlterField(
            model_name='entradaetapaevaluacion',
            name='presion_unidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unidad_presion_evaluacion', to='intercambiadores.unidades', verbose_name='Unidad'),
        ),
        migrations.AlterField(
            model_name='entradaetapaevaluacion',
            name='temperatura_unidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unidad_temperatura_out_evaluacion', to='intercambiadores.unidades', verbose_name='Unidad'),
        ),
        migrations.AlterField(
            model_name='entradaetapaevaluacion',
            name='velocidad_unidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unidad_velocidad_evaluacion', to='intercambiadores.unidades', verbose_name='Unidad'),
        ),
    ]
