# Generated by Django 4.2.20 on 2025-04-02 14:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compresores', '0019_remove_salidaetapaevaluacion_caida_presion_unidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salidaetapaevaluacion',
            name='hss',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entradaetapaevaluacion',
            name='temperatura_in',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(-273.15)], verbose_name='Temperatura de Entrada'),
        ),
        migrations.AlterField(
            model_name='entradaetapaevaluacion',
            name='temperatura_out',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(-273.15)], verbose_name='Temperatura de Salida'),
        ),
    ]
