# Generated by Django 4.2.20 on 2025-04-04 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compresores', '0020_salidaetapaevaluacion_hss_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entradaetapaevaluacion',
            name='pm_ficha',
        ),
        migrations.RemoveField(
            model_name='entradaetapaevaluacion',
            name='pm_ficha_unidad',
        ),
    ]
