# Generated by Django 4.2.20 on 2025-04-04 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intercambiadores', '0083_alter_evaluacionesintercambiador_ensuciamiento'),
        ('compresores', '0021_remove_entradaetapaevaluacion_pm_ficha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedadescompresor',
            name='pm',
            field=models.FloatField(blank=True, null=True, verbose_name='PM (gr/mol)'),
        ),
        migrations.AddField(
            model_name='propiedadescompresor',
            name='pm_unidad',
            field=models.ForeignKey(blank=True, default=54, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unidad_pm_compresor', to='intercambiadores.unidades', verbose_name='Unidad del PM'),
        ),
    ]
