# Generated by Django 4.2.20 on 2025-04-04 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compresores', '0022_propiedadescompresor_pm_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propiedadescompresor',
            name='pm_unidad',
        ),
    ]
