# Generated by Django 4.2.20 on 2025-04-04 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compresores', '0023_remove_propiedadescompresor_pm_unidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propiedadescompresor',
            name='pm',
        ),
        migrations.AddField(
            model_name='etapacompresor',
            name='pm',
            field=models.FloatField(blank=True, null=True, verbose_name='PM (gr/mol)'),
        ),
    ]
