# Generated by Django 4.2.4 on 2025-04-08 15:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intercambiadores', '0083_alter_evaluacionesintercambiador_ensuciamiento'),
        ('compresores', '0025_alter_entradaetapaevaluacion_k_in_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradaetapaevaluacion',
            name='potencia_generada',
            field=models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(1e-05)], verbose_name='Potencia Generada'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entradaetapaevaluacion',
            name='potencia_generada_unidad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='unidad_potencia_generada_evaluacion', to='intercambiadores.unidades', verbose_name='Unidad'),
            preserve_default=False,
        ),
    ]
