# Generated by Django 4.2.4 on 2025-04-14 11:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intercambiadores', '0083_alter_evaluacionesintercambiador_ensuciamiento'),
        ('compresores', '0026_alter_entradaetapaevaluacion_potencia_generada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradaetapaevaluacion',
            name='flujo_surge',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1e-05)], verbose_name='Flujo Surge'),
        ),
        migrations.AlterField(
            model_name='etapacompresor',
            name='aumento_estimado',
            field=models.FloatField(blank=True, null=True, verbose_name='Flujo Surge'),
        ),
        migrations.AlterField(
            model_name='etapacompresor',
            name='eficiencia_isentropica',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Eficiencia Isentrópica'),
        ),
        migrations.AlterField(
            model_name='etapacompresor',
            name='flujo_masico_unidad',
            field=models.ForeignKey(blank=True, default=6, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unidad_flujo_masico_compresor', to='intercambiadores.unidades', verbose_name='Unidad'),
        ),
    ]
