# Generated by Django 4.2.4 on 2025-04-15 11:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compresores', '0027_alter_entradaetapaevaluacion_flujo_surge_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etapacompresor',
            name='aumento_estimado',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Flujo Surge'),
        ),
        migrations.AlterField(
            model_name='etapacompresor',
            name='cabezal_politropico',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name='Cabezal Politrópico'),
        ),
        migrations.AlterField(
            model_name='etapacompresor',
            name='densidad',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name='Densidad'),
        ),
        migrations.AlterField(
            model_name='etapacompresor',
            name='eficiencia_isentropica',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Eficiencia Isentrópica'),
        ),
        migrations.AlterField(
            model_name='etapacompresor',
            name='eficiencia_politropica',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Eficiencia Politrópica'),
        ),
        migrations.AlterField(
            model_name='etapacompresor',
            name='flujo_masico',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name='Flujo Másico'),
        ),
        migrations.AlterField(
            model_name='etapacompresor',
            name='flujo_molar',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name='Flujo Molar'),
        ),
        migrations.AlterField(
            model_name='etapacompresor',
            name='pm',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='PM (gr/mol)'),
        ),
        migrations.AlterField(
            model_name='etapacompresor',
            name='potencia_nominal',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name='Potencia Nominal'),
        ),
        migrations.AlterField(
            model_name='etapacompresor',
            name='potencia_req',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name='Potencia Requerida'),
        ),
        migrations.AlterField(
            model_name='etapacompresor',
            name='rel_compresion',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Relación de Compresión'),
        ),
        migrations.AlterField(
            model_name='etapacompresor',
            name='volumen_diseno',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name='Volumen de Diseño'),
        ),
        migrations.AlterField(
            model_name='etapacompresor',
            name='volumen_normal',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name='Volumen Normal'),
        ),
        migrations.AlterField(
            model_name='ladoetapacompresor',
            name='compresibilidad',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Compresibilidad'),
        ),
        migrations.AlterField(
            model_name='ladoetapacompresor',
            name='cp_cv',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Relación Cp/Cv'),
        ),
        migrations.AlterField(
            model_name='ladoetapacompresor',
            name='presion',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name='Presión'),
        ),
        migrations.AlterField(
            model_name='ladoetapacompresor',
            name='temp',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-273.15)], verbose_name='Temperatura'),
        ),
    ]
