# Generated by Django 4.2.4 on 2025-04-15 15:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compresores', '0028_alter_etapacompresor_aumento_estimado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etapacompresor',
            name='eficiencia_isentropica',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Eficiencia Isentrópica (%)'),
        ),
        migrations.AlterField(
            model_name='etapacompresor',
            name='eficiencia_politropica',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Eficiencia Politrópica (%)'),
        ),
        migrations.AlterField(
            model_name='propiedadescompresor',
            name='numero_impulsores',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Número de Impulsores'),
        ),
        migrations.AlterField(
            model_name='propiedadescompresor',
            name='potencia_requerida',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name='Potencia Requerida Total'),
        ),
        migrations.AlterField(
            model_name='propiedadescompresor',
            name='velocidad_max_continua',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name='Velocidad Máxima Continua'),
        ),
        migrations.AlterField(
            model_name='propiedadescompresor',
            name='velocidad_rotacion',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name='Velocidad de Rotación'),
        ),
    ]
