# Generated by Django 4.2.4 on 2023-09-18 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complejo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'complejo',
            },
        ),
        migrations.CreateModel(
            name='CondicionesTuboCarcasa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lado', models.TextField(choices=[('T', 'Tubo'), ('C', 'Carcasa')], max_length=1)),
                ('temp_entrada', models.DecimalField(decimal_places=2, max_digits=7)),
                ('temp_salida', models.DecimalField(decimal_places=2, max_digits=7)),
                ('flujo_masico', models.DecimalField(decimal_places=5, max_digits=12)),
                ('flujo_vapor_entrada', models.DecimalField(decimal_places=5, default=0, max_digits=12)),
                ('flujo_vapor_salida', models.DecimalField(decimal_places=5, default=0, max_digits=12)),
                ('flujo_liquido_salida', models.DecimalField(decimal_places=5, default=0, max_digits=12)),
                ('cambio_de_fase', models.CharField(choices=[('S', 'Sin cambio de fase'), ('P', 'Cambio de Fase Parcial'), ('T', 'Cambio de Fase Total')], max_length=1)),
                ('presion_entrada', models.DecimalField(decimal_places=4, max_digits=10)),
                ('caida_presion_max', models.DecimalField(decimal_places=5, max_digits=7)),
                ('caida_presion_min', models.DecimalField(decimal_places=5, max_digits=7)),
                ('fouling', models.DecimalField(decimal_places=9, max_digits=10)),
            ],
            options={
                'db_table': 'condiciones_tubo_carcasa',
            },
        ),
        migrations.CreateModel(
            name='Fluido',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('formula', models.CharField(max_length=25, null=True)),
                ('peso_molecular', models.DecimalField(decimal_places=3, max_digits=6)),
                ('estado', models.CharField(choices=[('L', 'Líquido'), ('G', 'Gaseoso')], max_length=1)),
                ('a', models.DecimalField(decimal_places=3, max_digits=6)),
                ('b', models.DecimalField(decimal_places=7, max_digits=8)),
                ('c', models.DecimalField(decimal_places=11, max_digits=12)),
                ('d', models.DecimalField(decimal_places=11, max_digits=12)),
                ('minimo', models.IntegerField()),
                ('maximo', models.IntegerField()),
            ],
            options={
                'db_table': 'fluido',
            },
        ),
        migrations.CreateModel(
            name='Intercambiador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tag', models.CharField(max_length=50, unique=True)),
                ('fabricante', models.CharField(max_length=45)),
                ('servicio', models.CharField(max_length=100)),
                ('arreglo_flujo', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'intercambiador',
            },
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'db_table': 'tema',
            },
        ),
        migrations.CreateModel(
            name='TipoIntercambiador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tipo_intercambiador',
            },
        ),
        migrations.CreateModel(
            name='TiposDeTubo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'tipos_de_tubo',
            },
        ),
        migrations.CreateModel(
            name='Unidades',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('simbolo', models.CharField(max_length=5)),
                ('valor', models.DecimalField(decimal_places=5, max_digits=10)),
                ('tipo', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'unidades',
            },
        ),
        migrations.CreateModel(
            name='PropiedadesTuboCarcasa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('area', models.DecimalField(decimal_places=5, max_digits=12)),
                ('numero_tubos', models.IntegerField(null=True)),
                ('longitud_tubos', models.IntegerField(null=True)),
                ('diametro_externo_tubos', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('diametro_interno_tubos', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('material_carcasa', models.CharField(max_length=12, null=True)),
                ('conexiones_entrada_carcasa', models.CharField(max_length=12, null=True)),
                ('conexiones_salida_carcasa', models.CharField(max_length=12, null=True)),
                ('pasos_carcasa', models.IntegerField()),
                ('material_tubo', models.CharField(max_length=12, null=True)),
                ('conexiones_entrada_tubos', models.CharField(max_length=12, null=True)),
                ('conexiones_salida_tubos', models.CharField(max_length=12, null=True)),
                ('pitch_tubos', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('fabricante_tubo', models.TextField(max_length=100, null=True)),
                ('pasos_tubo', models.IntegerField()),
                ('criticidad', models.CharField(choices=[('C', 'Crítico'), ('S', 'Semi Crítico'), ('N', 'No Crítico')], max_length=1)),
                ('arreglo_serie', models.IntegerField()),
                ('arreglo_paralelo', models.IntegerField()),
                ('q', models.DecimalField(decimal_places=3, max_digits=10)),
                ('u', models.DecimalField(decimal_places=3, max_digits=10)),
                ('ensuciamiento', models.DecimalField(decimal_places=3, max_digits=10)),
                ('area_unidad', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='area_unidad_tubocarcasa', to='intercambiadores.unidades')),
                ('diametro_tubos_unidad', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='diametros_unidad_tubocarcasa', to='intercambiadores.unidades')),
                ('fluido_carcasa', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fluido_carcasa', to='intercambiadores.fluido')),
                ('fluido_tubo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fluido_tubo', to='intercambiadores.fluido')),
                ('intercambiador', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='datos_tubo_carcasa', to='intercambiadores.intercambiador')),
                ('longitud_tubos_unidad', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='longitud_tubos_tubocarcasa', to='intercambiadores.unidades')),
                ('tipo_tubo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='intercambiadores.tiposdetubo')),
                ('unidades_pitch', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='pitch_unidad_tubocarcasa', to='intercambiadores.unidades')),
            ],
            options={
                'db_table': 'intercambiador_tubo_carcasa',
            },
        ),
        migrations.CreateModel(
            name='Planta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('complejo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='intercambiadores.complejo')),
            ],
            options={
                'db_table': 'planta',
            },
        ),
        migrations.AddField(
            model_name='intercambiador',
            name='planta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='intercambiadores.planta'),
        ),
        migrations.AddField(
            model_name='intercambiador',
            name='tema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='intercambiadores.tema'),
        ),
        migrations.AddField(
            model_name='intercambiador',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='intercambiadores.tipointercambiador'),
        ),
        migrations.AddField(
            model_name='fluido',
            name='unidad_temperatura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='intercambiadores.unidades'),
        ),
        migrations.CreateModel(
            name='EvaluacionesIntercambiador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('metodo', models.CharField(choices=[('E', 'Método Efectividad-NTU'), ('L', 'Método LMTD')], max_length=1)),
                ('temp_ex_entrada', models.DecimalField(decimal_places=2, max_digits=7)),
                ('temp_ex_salida', models.DecimalField(decimal_places=2, max_digits=7)),
                ('temp_in_entrada', models.DecimalField(decimal_places=2, max_digits=7)),
                ('temp_in_salida', models.DecimalField(decimal_places=2, max_digits=7)),
                ('flujo_masico_ex', models.DecimalField(decimal_places=5, max_digits=12)),
                ('flujo_masico_in', models.DecimalField(decimal_places=5, max_digits=12)),
                ('presion_inicial', models.DecimalField(decimal_places=3, max_digits=10)),
                ('presion_final', models.DecimalField(decimal_places=3, max_digits=10)),
                ('lmtd', models.DecimalField(decimal_places=5, max_digits=12)),
                ('area_transferencia', models.DecimalField(decimal_places=5, max_digits=12)),
                ('u', models.DecimalField(decimal_places=5, max_digits=12)),
                ('ua', models.DecimalField(decimal_places=5, max_digits=12)),
                ('ntu', models.DecimalField(decimal_places=5, max_digits=12)),
                ('efectividad', models.DecimalField(decimal_places=5, max_digits=12)),
                ('eficiencia', models.DecimalField(decimal_places=5, max_digits=12)),
                ('ensuciamiento', models.DecimalField(decimal_places=5, max_digits=12)),
                ('q', models.DecimalField(decimal_places=5, max_digits=12)),
                ('numero_tubos', models.IntegerField()),
                ('condiciones', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='intercambiadores.condicionestubocarcasa')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('intercambiador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intercambiadores.intercambiador')),
                ('temperaturas_unidad', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='temperatura_unidad_evaluacionintercambiador', to='intercambiadores.unidades')),
                ('unidad_flujo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='flujo_unidad_evaluacionintercambiador', to='intercambiadores.unidades')),
                ('unidad_presion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='presion_unidad_evaluacionintercambiador', to='intercambiadores.unidades')),
            ],
            options={
                'db_table': 'evaluaciones_intercambiadores',
            },
        ),
        migrations.AddField(
            model_name='condicionestubocarcasa',
            name='flujos_unidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='flujos_unidad_tubocarcasa', to='intercambiadores.unidades'),
        ),
        migrations.AddField(
            model_name='condicionestubocarcasa',
            name='intercambiador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='intercambiadores.propiedadestubocarcasa'),
        ),
        migrations.AddField(
            model_name='condicionestubocarcasa',
            name='temperaturas_unidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='temperaturas_condiciones_unidades_tubocarcasa', to='intercambiadores.unidades'),
        ),
        migrations.AddField(
            model_name='condicionestubocarcasa',
            name='unidad_presion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='presion_unidad_tubocarcasa', to='intercambiadores.unidades'),
        ),
    ]
