# Generated by Django 4.2.4 on 2023-09-19 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intercambiadores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tema',
            name='descripcion',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='condicionestubocarcasa',
            name='flujo_liquido_salida',
            field=models.DecimalField(decimal_places=5, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='condicionestubocarcasa',
            name='flujo_masico',
            field=models.DecimalField(decimal_places=5, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='condicionestubocarcasa',
            name='flujo_vapor_entrada',
            field=models.DecimalField(decimal_places=5, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='condicionestubocarcasa',
            name='flujo_vapor_salida',
            field=models.DecimalField(decimal_places=5, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='condicionestubocarcasa',
            name='flujos_unidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='flujos_unidad_tubocarcasa', to='intercambiadores.unidades'),
        ),
        migrations.AlterField(
            model_name='condicionestubocarcasa',
            name='temp_entrada',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='condicionestubocarcasa',
            name='temp_salida',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='condicionestubocarcasa',
            name='temperaturas_unidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='temperaturas_condiciones_unidades_tubocarcasa', to='intercambiadores.unidades'),
        ),
    ]
