# Generated by Django 4.2.4 on 2023-09-19 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intercambiadores', '0002_tema_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tema',
            name='codigo',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
