# Generated by Django 4.2.4 on 2023-09-19 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intercambiadores', '0003_alter_tema_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedadestubocarcasa',
            name='arreglo_flujo',
            field=models.CharField(choices=[('C', 'Cocorriente'), ('c', 'Contracorriente'), ('M', 'Cruzado (Mezclado)'), ('m', 'Sin Mezclar')], default='C', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='condicionestubocarcasa',
            name='flujo_masico',
            field=models.DecimalField(decimal_places=5, default=100, max_digits=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fluido',
            name='a',
            field=models.DecimalField(decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='fluido',
            name='b',
            field=models.DecimalField(decimal_places=7, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='fluido',
            name='c',
            field=models.DecimalField(decimal_places=11, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='fluido',
            name='d',
            field=models.DecimalField(decimal_places=11, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='fluido',
            name='maximo',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='fluido',
            name='minimo',
            field=models.IntegerField(null=True),
        ),
    ]
