# Generated by Django 4.2.4 on 2023-09-19 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intercambiadores', '0004_propiedadestubocarcasa_arreglo_flujo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propiedadestubocarcasa',
            name='arreglo_flujo',
        ),
        migrations.AlterField(
            model_name='intercambiador',
            name='arreglo_flujo',
            field=models.CharField(choices=[('C', 'Cocorriente'), ('c', 'Contracorriente'), ('M', 'Cruzado (Mezclado)'), ('m', 'Sin Mezclar')], max_length=1),
        ),
    ]
