# Generated by Django 4.2.4 on 2023-09-19 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intercambiadores', '0005_remove_propiedadestubocarcasa_arreglo_flujo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fluido',
            name='peso_molecular',
            field=models.DecimalField(decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='fluido',
            name='unidad_temperatura',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='intercambiadores.unidades'),
        ),
    ]
