# Generated by Django 4.2.4 on 2023-09-20 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intercambiadores', '0006_alter_fluido_peso_molecular_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propiedadestubocarcasa',
            old_name='pasos_carcasa',
            new_name='numero_pasos',
        ),
        migrations.RemoveField(
            model_name='propiedadestubocarcasa',
            name='fabricante_tubo',
        ),
        migrations.RemoveField(
            model_name='propiedadestubocarcasa',
            name='pasos_tubo',
        ),
        migrations.AlterField(
            model_name='condicionestubocarcasa',
            name='caida_presion_max',
            field=models.DecimalField(decimal_places=5, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='condicionestubocarcasa',
            name='caida_presion_min',
            field=models.DecimalField(decimal_places=5, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='condicionestubocarcasa',
            name='presion_entrada',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='propiedadestubocarcasa',
            name='ensuciamiento',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='propiedadestubocarcasa',
            name='u',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
    ]
