# Generated by Django 4.2.4 on 2023-09-20 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intercambiadores', '0007_rename_pasos_carcasa_propiedadestubocarcasa_numero_pasos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='condicionestubocarcasa',
            name='flujo_liquido_entrada',
            field=models.DecimalField(decimal_places=5, max_digits=12, null=True),
        ),
    ]
