# Generated by Django 4.2.4 on 2023-09-20 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intercambiadores', '0009_alter_condicionestubocarcasa_fouling_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propiedadestubocarcasa',
            name='numero_pasos',
        ),
        migrations.AddField(
            model_name='propiedadestubocarcasa',
            name='numero_pasos_carcasa',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='propiedadestubocarcasa',
            name='numero_pasos_tubo',
            field=models.IntegerField(default=1),
        ),
    ]
