# Generated by Django 4.2.4 on 2023-09-21 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intercambiadores', '0010_remove_propiedadestubocarcasa_numero_pasos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condicionestubocarcasa',
            name='intercambiador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='condiciones', to='intercambiadores.propiedadestubocarcasa'),
        ),
    ]
