# Generated by Django 4.2.4 on 2023-09-21 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intercambiadores', '0011_alter_condicionestubocarcasa_intercambiador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedadestubocarcasa',
            name='intercambiador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='datos_tubo_carcasa', to='intercambiadores.intercambiador'),
        ),
    ]
