# Generated by Django 4.2.4 on 2023-09-27 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intercambiadores', '0012_alter_propiedadestubocarcasa_intercambiador'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propiedadestubocarcasa',
            options={'ordering': ('intercambiador__tag',)},
        ),
        migrations.AlterField(
            model_name='condicionestubocarcasa',
            name='caida_presion_max',
            field=models.DecimalField(decimal_places=5, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='condicionestubocarcasa',
            name='caida_presion_min',
            field=models.DecimalField(decimal_places=5, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='propiedadestubocarcasa',
            name='intercambiador',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='datos_tubo_carcasa', to='intercambiadores.intercambiador'),
        ),
    ]
