# Generated by Django 4.2.4 on 2023-09-27 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intercambiadores', '0013_alter_propiedadestubocarcasa_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacionesintercambiador',
            name='nombre',
            field=models.CharField(default='Prueba Inicial', max_length=50),
            preserve_default=False,
        ),
    ]
