# Generated by Django 4.2.4 on 2023-09-29 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intercambiadores', '0014_evaluacionesintercambiador_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fluido',
            name='a',
        ),
        migrations.RemoveField(
            model_name='fluido',
            name='b',
        ),
        migrations.RemoveField(
            model_name='fluido',
            name='c',
        ),
        migrations.RemoveField(
            model_name='fluido',
            name='d',
        ),
        migrations.RemoveField(
            model_name='fluido',
            name='formula',
        ),
        migrations.RemoveField(
            model_name='fluido',
            name='maximo',
        ),
        migrations.RemoveField(
            model_name='fluido',
            name='minimo',
        ),
        migrations.RemoveField(
            model_name='fluido',
            name='unidad_temperatura',
        ),
        migrations.AddField(
            model_name='fluido',
            name='cas',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
