# Generated by Django 4.2.4 on 2023-09-29 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intercambiadores', '0015_remove_fluido_a_remove_fluido_b_remove_fluido_c_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedadestubocarcasa',
            name='fluido_carcasa_cp',
            field=models.DecimalField(decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='propiedadestubocarcasa',
            name='fluido_carcasa_etiqueta',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='propiedadestubocarcasa',
            name='fluido_tubo_cp',
            field=models.DecimalField(decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='propiedadestubocarcasa',
            name='fluido_tubo_etiqueta',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
