# Generated by Django 4.2.4 on 2023-10-02 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intercambiadores', '0016_propiedadestubocarcasa_fluido_carcasa_cp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propiedadestubocarcasa',
            name='fluido_carcasa_cp',
        ),
        migrations.RemoveField(
            model_name='propiedadestubocarcasa',
            name='fluido_carcasa_etiqueta',
        ),
        migrations.RemoveField(
            model_name='propiedadestubocarcasa',
            name='fluido_tubo_cp',
        ),
        migrations.RemoveField(
            model_name='propiedadestubocarcasa',
            name='fluido_tubo_etiqueta',
        ),
        migrations.AddField(
            model_name='condicionestubocarcasa',
            name='fluido_cp',
            field=models.DecimalField(decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='condicionestubocarcasa',
            name='fluido_etiqueta',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='propiedadestubocarcasa',
            name='fluido_carcasa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fluido_carcasa', to='intercambiadores.fluido'),
        ),
        migrations.AlterField(
            model_name='propiedadestubocarcasa',
            name='fluido_tubo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fluido_tubo', to='intercambiadores.fluido'),
        ),
    ]
