# Generated by Django 4.2.4 on 2023-10-03 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intercambiadores', '0017_remove_propiedadestubocarcasa_fluido_carcasa_cp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fluido',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='fluido',
            name='peso_molecular',
        ),
    ]
