# Generated by Django 4.2.4 on 2023-10-03 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intercambiadores', '0018_remove_fluido_estado_remove_fluido_peso_molecular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedadestubocarcasa',
            name='conexiones_entrada_carcasa',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='propiedadestubocarcasa',
            name='conexiones_entrada_tubos',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='propiedadestubocarcasa',
            name='conexiones_salida_carcasa',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='propiedadestubocarcasa',
            name='conexiones_salida_tubos',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='propiedadestubocarcasa',
            name='material_carcasa',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='propiedadestubocarcasa',
            name='material_tubo',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
