# Generated by Django 4.2.4 on 2023-10-03 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intercambiadores', '0019_alter_propiedadestubocarcasa_conexiones_entrada_carcasa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condicionestubocarcasa',
            name='caida_presion_max',
            field=models.DecimalField(decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='condicionestubocarcasa',
            name='caida_presion_min',
            field=models.DecimalField(decimal_places=5, max_digits=10, null=True),
        ),
    ]
