# Generated by Django 4.2.4 on 2023-10-05 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intercambiadores', '0020_alter_condicionestubocarcasa_caida_presion_max_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fluido',
            options={'ordering': ('nombre',)},
        ),
        migrations.RenameField(
            model_name='evaluacionesintercambiador',
            old_name='presion_final',
            new_name='caida_presion_ex',
        ),
        migrations.RenameField(
            model_name='evaluacionesintercambiador',
            old_name='presion_inicial',
            new_name='caida_presion_in',
        ),
    ]
