# Generated by Django 4.2.4 on 2023-10-05 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intercambiadores', '0021_alter_fluido_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluacionesintercambiador',
            name='area_transferencia',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
    ]
