# Generated by Django 4.2.4 on 2023-10-05 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intercambiadores', '0022_alter_evaluacionesintercambiador_area_transferencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacionesintercambiador',
            name='cp_carcasa',
            field=models.DecimalField(decimal_places=4, default=555.55, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evaluacionesintercambiador',
            name='cp_tubo',
            field=models.DecimalField(decimal_places=4, default=222.22, max_digits=10),
            preserve_default=False,
        ),
    ]
