# Generated by Django 4.2.4 on 2023-10-06 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intercambiadores', '0023_evaluacionesintercambiador_cp_carcasa_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evaluacionesintercambiador',
            options={'ordering': ('-fecha',)},
        ),
        migrations.AlterField(
            model_name='evaluacionesintercambiador',
            name='u',
            field=models.DecimalField(decimal_places=8, max_digits=15),
        ),
        migrations.AlterField(
            model_name='evaluacionesintercambiador',
            name='ua',
            field=models.DecimalField(decimal_places=5, max_digits=15),
        ),
    ]
