# Generated by Django 4.2.4 on 2023-10-10 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intercambiadores', '0025_alter_evaluacionesintercambiador_ensuciamiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unidades',
            name='valor',
        ),
        migrations.AlterField(
            model_name='evaluacionesintercambiador',
            name='temp_ex_entrada',
            field=models.DecimalField(decimal_places=5, max_digits=12),
        ),
        migrations.AlterField(
            model_name='evaluacionesintercambiador',
            name='temp_ex_salida',
            field=models.DecimalField(decimal_places=5, max_digits=12),
        ),
        migrations.AlterField(
            model_name='evaluacionesintercambiador',
            name='temp_in_entrada',
            field=models.DecimalField(decimal_places=5, max_digits=12),
        ),
        migrations.AlterField(
            model_name='evaluacionesintercambiador',
            name='temp_in_salida',
            field=models.DecimalField(decimal_places=5, max_digits=12),
        ),
    ]
