# Generated by Django 4.2.4 on 2023-10-13 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intercambiadores', '0028_alter_propiedadestubocarcasa_longitud_tubos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidades',
            name='simbolo',
            field=models.CharField(max_length=10),
        ),
    ]
