# Generated by Django 4.2.4 on 2023-10-17 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intercambiadores', '0029_alter_unidades_simbolo'),
    ]

    operations = [
        migrations.AddField(
            model_name='condicionestubocarcasa',
            name='unidad_cp',
            field=models.ForeignKey(default=29, on_delete=django.db.models.deletion.CASCADE, related_name='unidad_cp', to='intercambiadores.unidades'),
        ),
        migrations.AddField(
            model_name='propiedadestubocarcasa',
            name='ensuciamiento_unidad',
            field=models.ForeignKey(default=31, on_delete=django.db.models.deletion.CASCADE, related_name='unidad_ensuciamiento', to='intercambiadores.unidades'),
        ),
        migrations.AddField(
            model_name='propiedadestubocarcasa',
            name='q_unidad',
            field=models.ForeignKey(default=28, on_delete=django.db.models.deletion.CASCADE, related_name='unidad_q', to='intercambiadores.unidades'),
        ),
        migrations.AddField(
            model_name='propiedadestubocarcasa',
            name='u_unidad',
            field=models.ForeignKey(default=27, on_delete=django.db.models.deletion.CASCADE, related_name='unidad_u', to='intercambiadores.unidades'),
        ),
    ]
