# Generated by Django 4.2.4 on 2023-10-17 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intercambiadores', '0030_condicionestubocarcasa_unidad_cp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacionesintercambiador',
            name='cp_unidad',
            field=models.ForeignKey(default=29, on_delete=django.db.models.deletion.CASCADE, related_name='cp_unidad_evaluacionintercambiador', to='intercambiadores.unidades'),
        ),
        migrations.AlterField(
            model_name='propiedadestubocarcasa',
            name='ensuciamiento',
            field=models.DecimalField(decimal_places=8, max_digits=10, null=True),
        ),
    ]
