# Generated by Django 4.2.4 on 2023-10-23 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intercambiadores', '0031_evaluacionesintercambiador_cp_unidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condicionestubocarcasa',
            name='caida_presion_max',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='condicionestubocarcasa',
            name='caida_presion_min',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='condicionestubocarcasa',
            name='flujo_liquido_entrada',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='condicionestubocarcasa',
            name='flujo_liquido_salida',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='condicionestubocarcasa',
            name='flujo_masico',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='condicionestubocarcasa',
            name='flujo_vapor_entrada',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='condicionestubocarcasa',
            name='flujo_vapor_salida',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='condicionestubocarcasa',
            name='fouling',
            field=models.DecimalField(decimal_places=9, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='condicionestubocarcasa',
            name='presion_entrada',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='propiedadestubocarcasa',
            name='area',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='propiedadestubocarcasa',
            name='diametro_externo_tubos',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='propiedadestubocarcasa',
            name='diametro_interno_tubos',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='propiedadestubocarcasa',
            name='ensuciamiento',
            field=models.DecimalField(decimal_places=9, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='propiedadestubocarcasa',
            name='q',
            field=models.DecimalField(decimal_places=3, max_digits=12),
        ),
    ]
