# Generated by Django 4.2.4 on 2023-10-25 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intercambiadores', '0032_alter_condicionestubocarcasa_caida_presion_max_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacionesintercambiador',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='condicionestubocarcasa',
            name='cambio_de_fase',
            field=models.CharField(choices=[('S', 'Sin Cambio de Fase'), ('P', 'Cambio de Fase Parcial'), ('T', 'Cambio de Fase Total')], max_length=1),
        ),
    ]
