# Generated by Django 4.2.4 on 2023-10-30 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intercambiadores', '0033_evaluacionesintercambiador_visible_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='condicionestubocarcasa',
            old_name='fluido_cp',
            new_name='fluido_cp_gas',
        ),
        migrations.AddField(
            model_name='condicionestubocarcasa',
            name='fluido_cp_liquido',
            field=models.DecimalField(decimal_places=4, max_digits=8, null=True),
        ),
    ]
