# Generated by Django 4.2.4 on 2023-10-31 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intercambiadores', '0035_condicionestubocarcasa_tipo_cp'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacionesintercambiador',
            name='hvap',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=10),
            preserve_default=False,
        ),
    ]
