# Generated by Django 4.2.4 on 2023-10-31 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intercambiadores', '0036_evaluacionesintercambiador_hvap'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluacionesintercambiador',
            name='hvap',
        ),
        migrations.AddField(
            model_name='condicionestubocarcasa',
            name='hvap',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
    ]
