# Generated by Django 4.2.4 on 2023-11-01 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intercambiadores', '0037_remove_evaluacionesintercambiador_hvap_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='condicionestubocarcasa',
            name='tsat',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=6),
            preserve_default=False,
        ),
    ]
