# Generated by Django 4.2.4 on 2023-11-01 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intercambiadores', '0038_condicionestubocarcasa_tsat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluacionesintercambiador',
            name='cp_carcasa',
        ),
        migrations.RemoveField(
            model_name='evaluacionesintercambiador',
            name='cp_tubo',
        ),
        migrations.AddField(
            model_name='evaluacionesintercambiador',
            name='cp_carcasa_gas',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='evaluacionesintercambiador',
            name='cp_carcasa_liquido',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='evaluacionesintercambiador',
            name='cp_tubo_gas',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='evaluacionesintercambiador',
            name='cp_tubo_liquido',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='condicionestubocarcasa',
            name='tsat',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
