# Generated by Django 4.2.4 on 2023-11-01 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intercambiadores', '0039_remove_evaluacionesintercambiador_cp_carcasa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacionesintercambiador',
            name='tipo',
            field=models.CharField(choices=[['A', 'Automático'], ['M', 'Manual']], default='A', max_length=1),
            preserve_default=False,
        ),
    ]
