# Generated by Django 4.2.4 on 2023-11-03 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intercambiadores', '0040_evaluacionesintercambiador_tipo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evaluacionesintercambiador',
            old_name='tipo',
            new_name='tipo_cp_carcasa',
        ),
        migrations.AddField(
            model_name='evaluacionesintercambiador',
            name='tipo_cp_tubo',
            field=models.CharField(choices=[['A', 'Automático'], ['M', 'Manual']], default='A', max_length=1),
            preserve_default=False,
        ),
    ]
