# Generated by Django 4.2.4 on 2023-11-09 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intercambiadores', '0041_rename_tipo_evaluacionesintercambiador_tipo_cp_carcasa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condicionestubocarcasa',
            name='hvap',
            field=models.DecimalField(decimal_places=4, max_digits=15, null=True),
        ),
    ]
