# Generated by Django 4.2.4 on 2023-11-17 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intercambiadores', '0042_alter_condicionestubocarcasa_hvap'),
    ]

    operations = [
        migrations.CreateModel(
            name='CondicionesDobleTubo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PropiedadesDobleTubo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='tema',
            name='tipo_intercambiador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='intercambiadores.tipointercambiador'),
        ),
    ]
