# Generated by Django 4.2.4 on 2023-11-20 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intercambiadores', '0043_condicionesdobletubo_propiedadesdobletubo_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CondicionesDobleTubo',
        ),
        migrations.DeleteModel(
            name='PropiedadesDobleTubo',
        ),
        migrations.AlterField(
            model_name='evaluacionesintercambiador',
            name='area_transferencia',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='evaluacionesintercambiador',
            name='caida_presion_ex',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='evaluacionesintercambiador',
            name='caida_presion_in',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='evaluacionesintercambiador',
            name='efectividad',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='evaluacionesintercambiador',
            name='eficiencia',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='evaluacionesintercambiador',
            name='flujo_masico_ex',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='evaluacionesintercambiador',
            name='flujo_masico_in',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='evaluacionesintercambiador',
            name='ntu',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
        migrations.AlterField(
            model_name='evaluacionesintercambiador',
            name='temp_ex_entrada',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='evaluacionesintercambiador',
            name='temp_ex_salida',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='evaluacionesintercambiador',
            name='temp_in_entrada',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='evaluacionesintercambiador',
            name='temp_in_salida',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='evaluacionesintercambiador',
            name='u',
            field=models.DecimalField(decimal_places=4, max_digits=15),
        ),
        migrations.AlterField(
            model_name='evaluacionesintercambiador',
            name='ua',
            field=models.DecimalField(decimal_places=4, max_digits=15),
        ),
    ]
