# Generated by Django 4.2.4 on 2023-11-27 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intercambiadores', '0044_delete_condicionesdobletubo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedadestubocarcasa',
            name='q',
            field=models.DecimalField(decimal_places=3, max_digits=20),
        ),
    ]
