# Generated by Django 4.2.4 on 2023-11-27 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intercambiadores', '0045_alter_propiedadestubocarcasa_q'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedadestubocarcasa',
            name='q',
            field=models.DecimalField(decimal_places=3, max_digits=15),
        ),
    ]
