# Generated by Django 4.2.4 on 2023-11-27 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intercambiadores', '0046_alter_propiedadestubocarcasa_q'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluacionesintercambiador',
            name='ensuciamiento',
            field=models.DecimalField(decimal_places=8, max_digits=10),
        ),
        migrations.AlterField(
            model_name='evaluacionesintercambiador',
            name='lmtd',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='evaluacionesintercambiador',
            name='q',
            field=models.DecimalField(decimal_places=3, max_digits=12),
        ),
    ]
