# Generated by Django 4.2.4 on 2023-11-27 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intercambiadores', '0047_alter_evaluacionesintercambiador_ensuciamiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='intercambiador',
            name='criticidad',
            field=models.CharField(choices=[('C', 'Crítico'), ('S', 'Semi Crítico'), ('N', 'No Crítico')], default='C', max_length=1),
            preserve_default=False,
        ),
    ]
