# Generated by Django 4.2.4 on 2023-11-27 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intercambiadores', '0048_intercambiador_criticidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propiedadestubocarcasa',
            name='criticidad',
        ),
    ]
