# Generated by Django 4.2.4 on 2023-11-27 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intercambiadores', '0049_remove_propiedadestubocarcasa_criticidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluacionesintercambiador',
            name='condiciones',
        ),
        migrations.AddField(
            model_name='condicionestubocarcasa',
            name='intercambiador_x',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='condiciones_x', to='intercambiadores.intercambiador'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='condicionestubocarcasa',
            name='fluido_cp_gas',
            field=models.DecimalField(decimal_places=4, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='condicionestubocarcasa',
            name='fluido_cp_liquido',
            field=models.DecimalField(decimal_places=4, max_digits=9, null=True),
        ),
    ]
