# Generated by Django 4.2.4 on 2023-11-27 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intercambiadores', '0050_remove_evaluacionesintercambiador_condiciones_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='condicionestubocarcasa',
            name='intercambiador',
        ),
    ]
