# Generated by Django 4.2.4 on 2023-11-27 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intercambiadores', '0051_remove_condicionestubocarcasa_intercambiador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condicionestubocarcasa',
            name='intercambiador_x',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condiciones', to='intercambiadores.intercambiador'),
        ),
    ]
