# Generated by Django 4.2.4 on 2023-11-27 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intercambiadores', '0052_alter_condicionestubocarcasa_intercambiador_x'),
    ]

    operations = [
        migrations.RenameField(
            model_name='condicionestubocarcasa',
            old_name='intercambiador_x',
            new_name='intercambiador',
        ),
    ]
