# Generated by Django 4.2.4 on 2023-11-27 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intercambiadores', '0053_rename_intercambiador_x_condicionestubocarcasa_intercambiador'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropiedadesDobleTubo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('area', models.DecimalField(decimal_places=2, max_digits=12)),
                ('numero_tubos', models.IntegerField(null=True)),
                ('longitud_tubos', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('diametro_externo_ex', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('diametro_externo_in', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('material_ex', models.CharField(max_length=50, null=True)),
                ('conexiones_entrada_ex', models.CharField(max_length=50, null=True)),
                ('conexiones_salida_ex', models.CharField(max_length=50, null=True)),
                ('material_in', models.CharField(max_length=50, null=True)),
                ('conexiones_entrada_in', models.CharField(max_length=50, null=True)),
                ('conexiones_salida_in', models.CharField(max_length=50, null=True)),
                ('arreglo_serie_ex', models.IntegerField()),
                ('arreglo_paralelo_ex', models.IntegerField()),
                ('arreglo_serie_in', models.IntegerField()),
                ('arreglo_paralelo_in', models.IntegerField()),
                ('q', models.DecimalField(decimal_places=3, max_digits=15)),
                ('u', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
                ('ensuciamiento', models.DecimalField(decimal_places=9, max_digits=12, null=True)),
                ('area_unidad', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='area_unidad_dobletubo', to='intercambiadores.unidades')),
                ('diametro_tubos_unidad', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='diametros_unidad_dobletubo', to='intercambiadores.unidades')),
                ('ensuciamiento_unidad', models.ForeignKey(default=31, on_delete=django.db.models.deletion.CASCADE, related_name='unidad_ensuciamiento_dobletubo', to='intercambiadores.unidades')),
                ('fluido_ex', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fluido_ex', to='intercambiadores.fluido')),
                ('fluido_in', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fluido_in', to='intercambiadores.fluido')),
                ('intercambiador', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='datos_dobletubo', to='intercambiadores.intercambiador')),
                ('longitud_tubos_unidad', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='longitud_tubos_dobletubo', to='intercambiadores.unidades')),
                ('q_unidad', models.ForeignKey(default=28, on_delete=django.db.models.deletion.CASCADE, related_name='unidad_q_dobletubo', to='intercambiadores.unidades')),
                ('tipo_tubo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='tipo_tubo_dobletubo', to='intercambiadores.tiposdetubo')),
                ('u_unidad', models.ForeignKey(default=27, on_delete=django.db.models.deletion.CASCADE, related_name='unidad_u_dobletubo', to='intercambiadores.unidades')),
            ],
            options={
                'db_table': 'intercambiador_doble_tubo',
                'ordering': ('intercambiador__tag',),
            },
        ),
    ]
