# Generated by Django 4.2.4 on 2023-11-28 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intercambiadores', '0054_propiedadesdobletubo'),
    ]

    operations = [
        migrations.RenameModel('CondicionesTuboCarcasa', 'CondicionesIntercambiador')
    ]
