# Generated by Django 4.2.4 on 2023-11-28 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intercambiadores', '0055_auto_20231128_1349'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='condicionesintercambiador',
            table='condiciones_intercambiador',
        ),
    ]
