# Generated by Django 4.2.4 on 2023-11-28 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intercambiadores', '0056_alter_condicionesintercambiador_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propiedadestubocarcasa',
            old_name='diametro_interno_tubos',
            new_name='diametro_interno_carcasa',
        ),
        migrations.AlterField(
            model_name='condicionesintercambiador',
            name='caida_presion_max',
            field=models.DecimalField(decimal_places=4, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='condicionesintercambiador',
            name='caida_presion_min',
            field=models.DecimalField(decimal_places=4, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='condicionesintercambiador',
            name='fouling',
            field=models.DecimalField(decimal_places=8, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='condicionesintercambiador',
            name='tsat',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='propiedadestubocarcasa',
            name='u',
            field=models.DecimalField(decimal_places=3, max_digits=11, null=True),
        ),
    ]
