# Generated by Django 4.2.4 on 2023-12-13 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intercambiadores', '0058_alter_evaluacionesintercambiador_cp_carcasa_gas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacionesintercambiador',
            name='area_diseno_unidad',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='area_unidad_evaluacionintercambiador', to='intercambiadores.unidades'),
        ),
        migrations.AddField(
            model_name='evaluacionesintercambiador',
            name='lmtd_diseno_unidad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lmtd_unidad_evaluacionintercambiador', to='intercambiadores.unidades'),
        ),
        migrations.AddField(
            model_name='evaluacionesintercambiador',
            name='q_diseno_unidad',
            field=models.ForeignKey(default=29, on_delete=django.db.models.deletion.CASCADE, related_name='q_unidad_evaluacionintercambiador', to='intercambiadores.unidades'),
        ),
        migrations.AddField(
            model_name='evaluacionesintercambiador',
            name='u_diseno_unidad',
            field=models.ForeignKey(default=27, on_delete=django.db.models.deletion.CASCADE, related_name='u_unidad_evaluacionintercambiador', to='intercambiadores.unidades'),
        ),
    ]
