# Generated by Django 4.2.4 on 2023-12-13 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('intercambiadores', '0059_evaluacionesintercambiador_area_diseno_unidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacionesintercambiador',
            name='diseno_editado',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='intercambiador',
            name='creado_al',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='intercambiador',
            name='creado_por',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='intercambiador_creado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='intercambiador',
            name='editado_al',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='intercambiador',
            name='editado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intercambiador_editado_por', to=settings.AUTH_USER_MODEL),
        ),
    ]
