# Generated by Django 4.2.4 on 2023-12-13 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intercambiadores', '0060_evaluacionesintercambiador_diseno_editado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluacionesintercambiador',
            name='lmtd_diseno_unidad',
        ),
        migrations.AlterField(
            model_name='evaluacionesintercambiador',
            name='intercambiador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='intercambiadores.intercambiador'),
        ),
        migrations.AlterField(
            model_name='intercambiador',
            name='creado_al',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
