# Generated by Django 4.2.4 on 2023-12-13 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intercambiadores', '0061_remove_evaluacionesintercambiador_lmtd_diseno_unidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacionesintercambiador',
            name='ensuc_diseno_unidad',
            field=models.ForeignKey(default=31, on_delete=django.db.models.deletion.CASCADE, related_name='ensuc_unidad_evaluacionintercambiador', to='intercambiadores.unidades'),
        ),
    ]
