# Generated by Django 4.2.4 on 2023-12-14 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intercambiadores', '0062_evaluacionesintercambiador_ensuc_diseno_unidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='intercambiador',
            name='efectividad',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='intercambiador',
            name='eficiencia',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='intercambiador',
            name='ensuciamiento',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='intercambiador',
            name='lmtd',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='evaluacionesintercambiador',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
