# Generated by Django 4.2.4 on 2023-12-14 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intercambiadores', '0063_intercambiador_efectividad_intercambiador_eficiencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='intercambiador',
            name='ntu',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=7),
            preserve_default=False,
        ),
    ]
