# Generated by Django 4.2.4 on 2023-12-14 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intercambiadores', '0065_remove_intercambiador_ensuciamiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intercambiador',
            name='efectividad',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='intercambiador',
            name='eficiencia',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='intercambiador',
            name='lmtd',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='intercambiador',
            name='ntu',
            field=models.DecimalField(decimal_places=3, max_digits=7, null=True),
        ),
    ]
