# Generated by Django 4.2.4 on 2024-01-14 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intercambiadores', '0067_remove_evaluacionesintercambiador_ua_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedadesdobletubo',
            name='altura_aletas',
            field=models.DecimalField(decimal_places=2, default=5.33, max_digits=8),
        ),
        migrations.AddField(
            model_name='propiedadesdobletubo',
            name='numero_aletas',
            field=models.IntegerField(default=20),
        ),
    ]
