# Generated by Django 4.2.4 on 2024-05-15 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intercambiadores', '0068_propiedadesdobletubo_altura_aletas_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='condicionesintercambiador',
            table='intercambiadores_condicionesintercambiador',
        ),
        migrations.AlterModelTable(
            name='evaluacionesintercambiador',
            table='intercambiadores_evaluaciones',
        ),
        migrations.AlterModelTable(
            name='intercambiador',
            table='intercambiadores_intercambiador',
        ),
        migrations.AlterModelTable(
            name='propiedadesdobletubo',
            table='intercambiadores_intercambiadordobletubo',
        ),
        migrations.AlterModelTable(
            name='propiedadestubocarcasa',
            table='intercambiadores_intercambiadortubocarcasa',
        ),
        migrations.AlterModelTable(
            name='tema',
            table='intercambiadores_tema',
        ),
        migrations.AlterModelTable(
            name='tipointercambiador',
            table='intercambiadores_tipointercambiador',
        ),
        migrations.AlterModelTable(
            name='tiposdetubo',
            table='intercambiadores_tiposdetubo',
        ),
    ]
