# Generated by Django 4.2.4 on 2024-05-28 11:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('intercambiadores', '0069_alter_condicionesintercambiador_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluacionesintercambiador',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
