# Generated by Django 4.2.4 on 2024-07-08 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intercambiadores', '0070_alter_evaluacionesintercambiador_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClasesUnidades',
            fields=[
                ('tipo', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'unidad_tipo',
                'ordering': ('nombre',),
            },
        ),
    ]
