# Generated by Django 4.2.4 on 2024-07-08 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intercambiadores', '0071_clasesunidades'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='clasesunidades',
            table='unidades_clases',
        ),
    ]
