# Generated by Django 4.2.4 on 2024-08-07 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intercambiadores', '0072_alter_clasesunidades_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='intercambiador',
            name='copia',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
