# Generated by Django 4.2.4 on 2024-10-21 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intercambiadores', '0073_intercambiador_copia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planta',
            options={'ordering': ('nombre',)},
        ),
    ]
