# Generated by Django 4.2.4 on 2024-11-14 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intercambiadores', '0074_alter_planta_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planta',
            name='complejo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='plantas', to='intercambiadores.complejo'),
        ),
    ]
