# Generated by Django 4.2.4 on 2024-11-24 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intercambiadores', '0076_alter_propiedadestubocarcasa_tipo_tubo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condicionesintercambiador',
            name='flujo_liquido_entrada',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='condicionesintercambiador',
            name='flujo_liquido_salida',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='condicionesintercambiador',
            name='flujo_masico',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='condicionesintercambiador',
            name='flujo_vapor_entrada',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='condicionesintercambiador',
            name='flujo_vapor_salida',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
    ]
