# Generated by Django 4.2.4 on 2024-11-24 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intercambiadores', '0077_alter_condicionesintercambiador_flujo_liquido_entrada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedadestubocarcasa',
            name='area',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
    ]
