# Generated by Django 4.2.4 on 2024-12-03 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intercambiadores', '0078_alter_propiedadestubocarcasa_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intercambiador',
            name='criticidad',
            field=models.CharField(choices=[('C', 'Crítico'), ('S', 'Semi Crítico'), ('N', 'No Crítico'), ('', 'Desconocido')], max_length=1),
        ),
    ]
