# Generated by Django 4.2.4 on 2024-12-13 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intercambiadores', '0079_alter_intercambiador_criticidad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planta',
            options={'ordering': ('-complejo', 'nombre')},
        ),
    ]
