# Generated by Django 4.2.4 on 2024-12-17 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intercambiadores', '0080_alter_planta_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluacionesintercambiador',
            name='caida_presion_ex',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='evaluacionesintercambiador',
            name='caida_presion_in',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
