# Generated by Django 4.2.4 on 2025-01-20 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intercambiadores', '0081_alter_evaluacionesintercambiador_caida_presion_ex_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedadesdobletubo',
            name='ensuciamiento',
            field=models.DecimalField(decimal_places=9, max_digits=15, null=True),
        ),
    ]
