# Generated by Django 4.2.4 on 2025-01-20 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intercambiadores', '0082_alter_propiedadesdobletubo_ensuciamiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluacionesintercambiador',
            name='ensuciamiento',
            field=models.DecimalField(decimal_places=8, max_digits=15),
        ),
    ]
