# Generated by Django 4.2.4 on 2024-06-14 11:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('intercambiadores', '0070_alter_evaluacionesintercambiador_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Caldera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=20, unique=True)),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripción')),
                ('fabricante', models.CharField(blank=True, max_length=45, null=True)),
                ('modelo', models.CharField(blank=True, max_length=45, null=True)),
                ('creado_al', models.DateTimeField(auto_now_add=True)),
                ('editado_al', models.DateTimeField(null=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='caldera_creada_por', to=settings.AUTH_USER_MODEL)),
                ('editado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='caldera_editada_por', to=settings.AUTH_USER_MODEL)),
                ('planta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planta_caldera', to='intercambiadores.planta')),
            ],
            options={
                'db_table': 'calderas_caldera',
            },
        ),
    ]
