# Generated by Django 4.2.4 on 2024-06-18 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('intercambiadores', '0070_alter_evaluacionesintercambiador_id'),
        ('calderas', '0002_caracteristica_combustible_dimssobrecalentador_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caracteristica',
            name='clase',
        ),
        migrations.RemoveField(
            model_name='valorporcarga',
            name='tipo',
        ),
        migrations.AddField(
            model_name='corriente',
            name='nombre',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='usuario_evaluacion_caldera', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='corriente',
            name='densidad',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='corriente',
            name='flujo_masico',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='corriente',
            name='flujo_masico_unidad',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.PROTECT, related_name='flujomasico_unidad_corriente_calderas', to='intercambiadores.unidades'),
        ),
        migrations.AlterField(
            model_name='corriente',
            name='numero',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='corriente',
            name='presion',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='corriente',
            name='temp_operacion',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='sobrecalentador',
            name='flujo_unidad',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.PROTECT, related_name='flujo_unidad_sobrecalentador', to='intercambiadores.unidades'),
        ),
        migrations.CreateModel(
            name='EntradaComposicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parc_vol', models.FloatField()),
                ('parc_aire', models.FloatField()),
                ('normalizado', models.FloatField()),
                ('normalizado_aire', models.FloatField(blank=True)),
                ('composicion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='calderas.composicioncombustible')),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='composiciones_evaluacion', to='calderas.evaluacion')),
            ],
        ),
    ]
