# Generated by Django 4.2.4 on 2024-06-20 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calderas', '0003_remove_caracteristica_clase_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corriente',
            name='densidad',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='corriente',
            name='estado',
            field=models.CharField(blank=True, choices=[('L', 'Líquido'), ('V', 'Vapor')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='corriente',
            name='temp_operacion',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='corriente',
            name='tipo',
            field=models.CharField(choices=[('A', 'Vapor de Alta Presión'), ('W', 'Agua'), ('P', 'Purga'), ('B', 'Vapor de Baja Presión')], max_length=1),
        ),
    ]
