# Generated by Django 4.2.4 on 2024-06-21 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calderas', '0004_alter_corriente_densidad_alter_corriente_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caldera',
            name='dimensiones',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='calderas.dimensionescaldera'),
        ),
    ]
