# Generated by Django 4.2.4 on 2024-06-21 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calderas', '0005_alter_caldera_dimensiones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sobrecalentador',
            name='flujo_max_continuo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sobrecalentador',
            name='presion_diseno',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sobrecalentador',
            name='presion_operacion',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sobrecalentador',
            name='temp_operacion',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
