# Generated by Django 4.2.4 on 2024-06-21 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calderas', '0006_alter_sobrecalentador_flujo_max_continuo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dimensionescaldera',
            name='alto',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dimensionescaldera',
            name='ancho',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dimensionescaldera',
            name='largo',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
