# Generated by Django 4.2.4 on 2024-06-21 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calderas', '0007_alter_dimensionescaldera_alto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caldera',
            name='tipo_caldera',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
