# Generated by Django 4.2.4 on 2024-06-21 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calderas', '0008_alter_caldera_tipo_caldera'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corriente',
            name='nombre',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
