# Generated by Django 4.2.4 on 2024-06-21 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calderas', '0009_alter_corriente_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corriente',
            name='nombre',
            field=models.CharField(max_length=55, null=True),
        ),
    ]
