# Generated by Django 4.2.4 on 2024-06-21 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calderas', '0010_alter_corriente_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caracteristica',
            name='tipo_unidad',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
