# Generated by Django 4.2.4 on 2024-06-21 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intercambiadores', '0070_alter_evaluacionesintercambiador_id'),
        ('calderas', '0011_alter_caracteristica_tipo_unidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valorporcarga',
            name='unidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='intercambiadores.unidades'),
        ),
    ]
