# Generated by Django 4.2.4 on 2024-06-21 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calderas', '0012_alter_valorporcarga_unidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caracteristica',
            name='nombre',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='corriente',
            name='nombre',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
