# Generated by Django 4.2.4 on 2024-06-21 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calderas', '0013_alter_caracteristica_nombre_alter_corriente_nombre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caldera',
            options={'ordering': ('tag',)},
        ),
        migrations.AlterModelOptions(
            name='composicioncombustible',
            options={'ordering': ('-porc_vol', '-porc_vol')},
        ),
        migrations.AlterField(
            model_name='composicioncombustible',
            name='combustible',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='composicion_combustible_caldera', to='calderas.combustible'),
        ),
        migrations.AlterField(
            model_name='composicioncombustible',
            name='porc_aire',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
