# Generated by Django 4.2.4 on 2024-07-02 11:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intercambiadores', '0070_alter_evaluacionesintercambiador_id'),
        ('calderas', '0014_alter_caldera_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='composicioncombustible',
            options={'ordering': ('-porc_vol', '-porc_aire')},
        ),
        migrations.AlterModelOptions(
            name='secciontambor',
            options={'ordering': ('seccion',)},
        ),
        migrations.AddField(
            model_name='caracteristica',
            name='carga_100',
            field=models.FloatField(default=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='caracteristica',
            name='carga_25',
            field=models.FloatField(default=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='caracteristica',
            name='carga_50',
            field=models.FloatField(default=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='caracteristica',
            name='carga_75',
            field=models.FloatField(default=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='caracteristica',
            name='unidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='intercambiadores.unidades'),
        ),
        migrations.AlterField(
            model_name='caldera',
            name='tipo_caldera',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo de Caldera'),
        ),
        migrations.AlterField(
            model_name='caracteristica',
            name='caldera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='caracteristicas_caldera', to='calderas.caldera'),
        ),
        migrations.AlterField(
            model_name='chimenea',
            name='altura',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name='Altura'),
        ),
        migrations.AlterField(
            model_name='chimenea',
            name='diametro',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name='Diámetro'),
        ),
        migrations.AlterField(
            model_name='combustible',
            name='liquido',
            field=models.BooleanField(default=False, verbose_name='¿Utiliza Combustible Líquido?'),
        ),
        migrations.AlterField(
            model_name='combustible',
            name='nombre_gas',
            field=models.CharField(max_length=45, verbose_name='Nombre del Combustible Gas'),
        ),
        migrations.AlterField(
            model_name='combustible',
            name='nombre_liquido',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Nombre del Combustible Líquido'),
        ),
        migrations.AlterField(
            model_name='composicioncombustible',
            name='porc_aire',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='composicioncombustible',
            name='porc_vol',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='corriente',
            name='caldera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='corrientes_caldera', to='calderas.caldera'),
        ),
        migrations.AlterField(
            model_name='corriente',
            name='densidad',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0001)]),
        ),
        migrations.AlterField(
            model_name='corriente',
            name='flujo_masico',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.0001)]),
        ),
        migrations.AlterField(
            model_name='corriente',
            name='presion',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.0001)]),
        ),
        migrations.AlterField(
            model_name='corriente',
            name='temp_operacion',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-273.15)]),
        ),
        migrations.AlterField(
            model_name='dimensionescaldera',
            name='alto',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0001)]),
        ),
        migrations.AlterField(
            model_name='dimensionescaldera',
            name='ancho',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0001)]),
        ),
        migrations.AlterField(
            model_name='dimensionescaldera',
            name='largo',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0001)]),
        ),
        migrations.AlterField(
            model_name='dimssobrecalentador',
            name='area_total_transferencia',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name='Área Total de Transferencia'),
        ),
        migrations.AlterField(
            model_name='dimssobrecalentador',
            name='diametro_tubos',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name='Diámetro de Tubos'),
        ),
        migrations.AlterField(
            model_name='dimssobrecalentador',
            name='num_tubos',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Número de Tubos'),
        ),
        migrations.AlterField(
            model_name='economizador',
            name='area_total_transferencia',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name='Área Total de Transferencia'),
        ),
        migrations.AlterField(
            model_name='economizador',
            name='diametro_tubos',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name='Diámetro de los tubos'),
        ),
        migrations.AlterField(
            model_name='economizador',
            name='numero_tubos',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Número de Tubos'),
        ),
        migrations.AlterField(
            model_name='entradacomposicion',
            name='normalizado',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='entradacomposicion',
            name='normalizado_aire',
            field=models.FloatField(blank=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='entradacomposicion',
            name='parc_aire',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='entradacomposicion',
            name='parc_vol',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='entradasfluidos',
            name='flujo',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name='Flujo Másico'),
        ),
        migrations.AlterField(
            model_name='entradasfluidos',
            name='humedad_relativa',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='entradasfluidos',
            name='presion',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name='Presión de Operación'),
        ),
        migrations.AlterField(
            model_name='entradasfluidos',
            name='temperatura',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(-273.15)], verbose_name='Temperatura de Operación'),
        ),
        migrations.AlterField(
            model_name='especificacionescaldera',
            name='area_transferencia_calor',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name='Área de Transferencia de Calor'),
        ),
        migrations.AlterField(
            model_name='especificacionescaldera',
            name='calor_intercambiado',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name='Calor Intercambiado'),
        ),
        migrations.AlterField(
            model_name='especificacionescaldera',
            name='capacidad',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name='Capacidad de la Caldera'),
        ),
        migrations.AlterField(
            model_name='especificacionescaldera',
            name='carga',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name='Carga de la Caldera'),
        ),
        migrations.AlterField(
            model_name='especificacionescaldera',
            name='eficiencia_termica',
            field=models.FloatField(blank=True, null=True, verbose_name='Eficiencia Térmica'),
        ),
        migrations.AlterField(
            model_name='especificacionescaldera',
            name='material',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Material de la Caldera'),
        ),
        migrations.AlterField(
            model_name='especificacionescaldera',
            name='presion_diseno',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name='Presión de Diseño'),
        ),
        migrations.AlterField(
            model_name='especificacionescaldera',
            name='presion_operacion',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name='Presión de Operación'),
        ),
        migrations.AlterField(
            model_name='especificacionescaldera',
            name='temp_diseno',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-273.15)], verbose_name='Temperatura de Diseño'),
        ),
        migrations.AlterField(
            model_name='especificacionescaldera',
            name='temp_operacion',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-273.15)], verbose_name='Temperatura de Operación'),
        ),
        migrations.AlterField(
            model_name='secciontambor',
            name='diametro',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name='Diámetro'),
        ),
        migrations.AlterField(
            model_name='secciontambor',
            name='longitud',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name='Longitud'),
        ),
        migrations.AlterField(
            model_name='secciontambor',
            name='tambor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='secciones_tambor', to='calderas.tambor'),
        ),
        migrations.AlterField(
            model_name='sobrecalentador',
            name='flujo_max_continuo',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name='Flujo Máximo Continuo'),
        ),
        migrations.AlterField(
            model_name='sobrecalentador',
            name='presion_diseno',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name='Presión de Diseño'),
        ),
        migrations.AlterField(
            model_name='sobrecalentador',
            name='presion_operacion',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name='Presión de Operación'),
        ),
        migrations.AlterField(
            model_name='sobrecalentador',
            name='temp_operacion',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-273.15)], verbose_name='Temperatura de Operación'),
        ),
        migrations.AlterField(
            model_name='tambor',
            name='material',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Material del Tambor'),
        ),
        migrations.AlterField(
            model_name='tambor',
            name='presion_diseno',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name='Presión de Diseño'),
        ),
        migrations.AlterField(
            model_name='tambor',
            name='presion_operacion',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1e-05)], verbose_name='Presión de Operación'),
        ),
        migrations.AlterField(
            model_name='tambor',
            name='temp_diseno',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-273.15)], verbose_name='Temperatura de Diseño'),
        ),
        migrations.AlterField(
            model_name='tambor',
            name='temp_operacion',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-273.15)], verbose_name='Temperatura de Operación'),
        ),
        migrations.DeleteModel(
            name='ValorPorCarga',
        ),
    ]
