# Generated by Django 4.2.4 on 2024-07-09 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calderas', '0017_alter_corriente_options_evaluacion_activo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluacion',
            name='caldera',
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='equipo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='equipo_evaluacion_caldera', to='calderas.caldera'),
            preserve_default=False,
        ),
    ]
