# Generated by Django 4.2.4 on 2024-07-10 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calderas', '0018_remove_evaluacion_caldera_evaluacion_equipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entradasfluidos',
            name='nombre_fluido',
        ),
        migrations.AddField(
            model_name='entradasfluidos',
            name='tipo',
            field=models.CharField(choices=[('G', 'Gas'), ('A', 'Aire'), ('H', 'Horno'), ('W', 'Agua de Entrada a la Caldera'), ('V', 'Vapor Producido')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entradasfluidos',
            name='tipo_fluido',
            field=models.CharField(choices=[('G', 'Gas'), ('A', 'Aire'), ('H', 'Horno'), ('W', 'Agua de Entrada a la Caldera'), ('V', 'Vapor Producido')], max_length=1),
        ),
    ]
