# Generated by Django 4.2.4 on 2024-07-10 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calderas', '0019_remove_entradasfluidos_nombre_fluido_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entradasfluidos',
            name='tipo',
        ),
    ]
