# Generated by Django 4.2.4 on 2024-07-12 13:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intercambiadores', '0072_alter_clasesunidades_table'),
        ('calderas', '0020_remove_entradasfluidos_tipo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evaluacion',
            options={'ordering': ('-fecha',)},
        ),
        migrations.RemoveField(
            model_name='salidaladoagua',
            name='eficiencia',
        ),
        migrations.AddField(
            model_name='entradasfluidos',
            name='flujo_unidad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='flujo_unidad_entrada_fluidos_caldera', to='intercambiadores.unidades'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entradasfluidos',
            name='presion_unidad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='presion_unidad_entrada_fluidos_caldera', to='intercambiadores.unidades'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entradasfluidos',
            name='temperatura_unidad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='temperatura_unidad_entrada_fluidos_caldera', to='intercambiadores.unidades'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='eficiencia',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entradasfluidos',
            name='flujo',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name='Flujo'),
        ),
    ]
