# Generated by Django 4.2.4 on 2024-07-12 14:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('calderas', '0021_alter_evaluacion_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalidaBalances',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('n_gas', models.FloatField()),
                ('n_aire', models.FloatField()),
                ('m_gas', models.FloatField()),
                ('m_aire', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='evaluacion',
            name='salida_balance_molar',
        ),
        migrations.RemoveField(
            model_name='salidabalanceenergia',
            name='energia_unidad',
        ),
        migrations.RemoveField(
            model_name='salidaflujosentrada',
            name='flujo_masico_unidad',
        ),
        migrations.RemoveField(
            model_name='salidaflujosentrada',
            name='flujo_vol_unidad',
        ),
        migrations.DeleteModel(
            name='SalidaBalanceMolar',
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='salida_balances',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='calderas.salidabalances'),
            preserve_default=False,
        ),
    ]
