# Generated by Django 4.2.4 on 2024-07-15 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intercambiadores', '0072_alter_clasesunidades_table'),
        ('calderas', '0022_salidabalances_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salidaflujosentrada',
            old_name='flujo_aire_entrada',
            new_name='flujo_m_aire_entrada',
        ),
        migrations.RenameField(
            model_name='salidaflujosentrada',
            old_name='flujo_gas_entrada',
            new_name='flujo_m_gas_entrada',
        ),
        migrations.AddField(
            model_name='salidaflujosentrada',
            name='flujo_n_aire_entrada',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salidaflujosentrada',
            name='flujo_n_gas_entrada',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entradasfluidos',
            name='flujo_unidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='flujo_unidad_entrada_fluidos_caldera', to='intercambiadores.unidades'),
        ),
    ]
