# Generated by Django 4.2.4 on 2024-07-15 08:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calderas', '0023_rename_flujo_aire_entrada_salidaflujosentrada_flujo_m_aire_entrada_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entradacomposicion',
            name='normalizado',
        ),
        migrations.RemoveField(
            model_name='entradacomposicion',
            name='normalizado_aire',
        ),
        migrations.AlterField(
            model_name='entradacomposicion',
            name='parc_aire',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='fecha',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='nombre',
            field=models.CharField(max_length=45, verbose_name='Nombre de la Evaluación'),
        ),
    ]
