# Generated by Django 4.2.4 on 2024-07-15 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calderas', '0025_alter_entradasfluidos_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salidafracciones',
            name='so2',
        ),
        migrations.RemoveField(
            model_name='salidaladoagua',
            name='flujo_unidad',
        ),
    ]
