# Generated by Django 4.2.4 on 2024-07-20 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calderas', '0026_remove_salidafracciones_so2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salidafracciones',
            name='so2',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
