# Generated by Django 4.2.4 on 2024-08-09 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calderas', '0028_salidabalanceenergia_energia_total_salida'),
    ]

    operations = [
        migrations.AddField(
            model_name='caldera',
            name='copia',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
