# Generated by Django 4.2.4 on 2024-08-12 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calderas', '0029_caldera_copia'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacion',
            name='metodo',
            field=models.CharField(choices=[('D', 'Directo'), ('I', 'Indirecto')], default='D', max_length=1),
            preserve_default=False,
        ),
    ]
