# Generated by Django 4.2.4 on 2024-08-12 11:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intercambiadores', '0073_intercambiador_copia'),
        ('calderas', '0030_evaluacion_metodo'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradasfluidos',
            name='velocidad',
            field=models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name='Presión de Operación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entradasfluidos',
            name='velocidad_unidad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='velocidad_unidad_entrada_fluidos_caldera', to='intercambiadores.unidades'),
            preserve_default=False,
        ),
    ]
