# Generated by Django 4.2.4 on 2024-08-12 13:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intercambiadores', '0073_intercambiador_copia'),
        ('calderas', '0031_entradasfluidos_velocidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradasfluidos',
            name='area',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0001)]),
        ),
        migrations.AddField(
            model_name='entradasfluidos',
            name='area_unidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='area_unidad_entrada_fluidos_caldera', to='intercambiadores.unidades'),
        ),
        migrations.AlterField(
            model_name='entradasfluidos',
            name='velocidad',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0001)]),
        ),
        migrations.AlterField(
            model_name='entradasfluidos',
            name='velocidad_unidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='velocidad_unidad_entrada_fluidos_caldera', to='intercambiadores.unidades'),
        ),
    ]
