# Generated by Django 4.2.4 on 2024-08-14 11:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calderas', '0033_perdidasindirecto_alter_entradasfluidos_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacion',
            name='o2_gas_combustion',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
