# Generated by Django 4.2.4 on 2024-08-14 14:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calderas', '0034_evaluacion_o2_gas_combustion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradasfluidos',
            name='presion',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name='Presión de Operación'),
        ),
        migrations.AlterField(
            model_name='entradasfluidos',
            name='temperatura',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-273.15)], verbose_name='Temperatura de Operación'),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='o2_gas_combustion',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='% O2 Gases Combustión'),
        ),
    ]
