# Generated by Django 4.2.4 on 2024-09-26 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intercambiadores', '0073_intercambiador_copia'),
        ('calderas', '0035_alter_entradasfluidos_presion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradasfluidos',
            name='presion_unidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='presion_unidad_entrada_fluidos_caldera', to='intercambiadores.unidades'),
        ),
        migrations.AlterField(
            model_name='entradasfluidos',
            name='tipo_fluido',
            field=models.CharField(choices=[('G', 'Gas'), ('A', 'Aire'), ('H', 'Horno'), ('S', 'Superficie de la Caldera'), ('W', 'Agua de Entrada a la Caldera'), ('V', 'Vapor Producido')], max_length=1),
        ),
    ]
