# Generated by Django 4.2.4 on 2024-12-13 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calderas', '0036_alter_entradasfluidos_presion_unidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caracteristica',
            name='carga_100',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='caracteristica',
            name='carga_25',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='caracteristica',
            name='carga_50',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='caracteristica',
            name='carga_75',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
